pub const TRANSACTION_STATUS_FINAL: &str = "FINAL";
pub const TRANSACTION_STATUS_EXECUTED: &str = "EXECUTED";
pub const TRANSACTION_STATUS_EXECUTED_OPTIMISTIC: &str = "EXECUTED_OPTIMISTIC";

pub(crate) const STORAGE_AMOUNT_PER_BYTE: u128 = 10_000_000_000_000_000_000;
