port: 3000
address: 0.0.0.0
metrics:
  prefix: dynode

jwt:
  secret: ""

webhook:
  enabled: false
  url: ""
  token: ""

monitoring:
  enabled: true
  profile: wallet
  interval: 10m
  trigger:
    failures: 15 # consecutive or rate minimum
    rate: 50 # percent in window
    window: 1m
    latency: 1500ms

request:
  timeout: 3s

headers:
  forward:
    - accept
    - content-type
    - content-encoding
    - content-length
    - grpc-accept-encoding
    - grpc-encoding
    - grpc-message
    - grpc-status
    - grpc-status-details-bin
    - te
  domains:
    public-eth.nownodes.io:
      - user-agent

retry:
  enabled: true
  max_attempts: 3
  errors:
    status_codes: [401, 403, 429, 502, 503, 504]
    error_messages:
      - "daily request limit"
      - "rate limit"
      - "Exceeded the quota usage"
      - "Unauthorized"

chain_types:
  ethereum:
    allowlist:
      - rpc_method: eth_chainId
      - rpc_method: eth_sendRawTransaction
      - rpc_method: eth_blockNumber
      - rpc_method: eth_call
  bitcoin:
    allowlist:
      - path: /api/v2/address/**
        method: GET
      - path: /api/v2/sendtx/
        method: POST
  cosmos:
    chains:
      thorchain:
        allowlist:
          - path: /thorchain/inbound_addresses
            method: GET
          - path: /thorchain/quote/swap
            method: GET
          - path: /thorchain/tx/status/**
            method: GET
      mayachain:
        allowlist:
          - path: /mayachain/inbound_addresses
            method: GET
          - path: /mayachain/quote/swap
            method: GET
          - path: /mayachain/tx/status/**
            method: GET
