[package]
name = "gem_ankr"
version = { workspace = true }
edition = { workspace = true }

[features]
testkit = []

[dependencies]
gem_client = { path = "../gem_client" }
gem_jsonrpc = { path = "../gem_jsonrpc", features = ["client"] }
serde_serializers = { path = "../serde_serializers", features = ["bigint"] }

num-bigint = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
gem_jsonrpc = { path = "../gem_jsonrpc", features = ["testkit"] }
tokio = { workspace = true }
