// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

use primitives::{Asset, AssetType, Currency, RecentActivityType};
use std::str::FromStr;

#[uniffi::remote(Enum)]
pub enum AssetType {
    NATIVE,
    ERC20,
    BEP20,
    SPL,
    SPL2022,
    TRC20,
    TIP20,
    TOKEN,
    IBC,
    JETTON,
    SYNTH,
    ASA,
    PERPETUAL,
    SPOT,
}

uniffi::custom_type!(Currency, String, {
    remote,
    lower: |value| value.as_ref().to_string(),
    try_lift: |value| Currency::from_str(&value).map_err(|_| uniffi::deps::anyhow::Error::msg("Invalid Currency")),
});

#[uniffi::remote(Enum)]
pub enum RecentActivityType {
    Search,
    Transfer,
    Receive,
    FiatBuy,
    FiatSell,
    Swap,
    SwapSelect,
    Perpetual,
}

#[uniffi::remote(Record)]
pub struct Asset {
    pub id: primitives::AssetId,
    pub name: String,
    pub symbol: String,
    pub decimals: i32,
    pub asset_type: AssetType,
}
