// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

use primitives::{
    Asset, AssetType, Currency, FeePriority, Latency, LatencyType, PerpetualProvider, PortfolioType, RecentActivityType, SimulationPayloadField, SimulationPayloadFieldDisplay,
    SimulationPayloadFieldKind, SimulationPayloadFieldType, TpslType, WalletConnectionVerificationStatus, WalletSource, WalletType,
};
use std::str::FromStr;

#[uniffi::remote(Enum)]
pub enum AssetType {
    NATIVE,
    ERC20,
    BEP20,
    SPL,
    SPL2022,
    TRC20,
    TIP20,
    TOKEN,
    IBC,
    JETTON,
    SYNTH,
    ASA,
    PERPETUAL,
    SPOT,
}

uniffi::custom_type!(Currency, String, {
    remote,
    lower: |value| value.as_ref().to_string(),
    try_lift: |value| Currency::from_str(&value).map_err(|_| uniffi::deps::anyhow::Error::msg("Invalid Currency")),
});

#[uniffi::remote(Enum)]
pub enum FeePriority {
    Normal,
    Fast,
}

#[uniffi::remote(Enum)]
pub enum LatencyType {
    Fast,
    Normal,
    Slow,
}

#[uniffi::remote(Enum)]
pub enum PerpetualProvider {
    Hypercore,
}

#[uniffi::remote(Enum)]
pub enum PortfolioType {
    Wallet,
    Perpetuals,
}

#[uniffi::remote(Enum)]
pub enum RecentActivityType {
    Search,
    Transfer,
    Receive,
    FiatBuy,
    FiatSell,
    Swap,
    SwapSelect,
    Perpetual,
}

#[uniffi::remote(Enum)]
pub enum SimulationPayloadFieldDisplay {
    Primary,
    Secondary,
}

#[uniffi::remote(Enum)]
pub enum SimulationPayloadFieldKind {
    Contract,
    Method,
    Token,
    Spender,
    Value,
    Custom,
}

#[uniffi::remote(Enum)]
pub enum SimulationPayloadFieldType {
    Text,
    Address,
    Timestamp,
}

#[uniffi::remote(Enum)]
pub enum TpslType {
    TakeProfit,
    StopLoss,
}

#[uniffi::remote(Enum)]
pub enum WalletConnectionVerificationStatus {
    Verified,
    Unknown,
    Invalid,
    Malicious,
}

#[uniffi::remote(Enum)]
pub enum WalletSource {
    Create,
    Import,
}

#[uniffi::remote(Enum)]
pub enum WalletType {
    Multicoin,
    Single,
    PrivateKey,
    View,
}

#[uniffi::remote(Record)]
pub struct Asset {
    pub id: primitives::AssetId,
    pub name: String,
    pub symbol: String,
    pub decimals: i32,
    pub asset_type: AssetType,
}

#[uniffi::remote(Record)]
pub struct Latency {
    pub latency_type: LatencyType,
    pub value: f64,
}

#[uniffi::remote(Record)]
pub struct SimulationPayloadField {
    pub kind: SimulationPayloadFieldKind,
    pub label: Option<String>,
    pub value: String,
    pub field_type: SimulationPayloadFieldType,
    pub display: SimulationPayloadFieldDisplay,
}
