package com.gemwallet.android.ui.components.image

import androidx.annotation.DrawableRes
import com.gemwallet.android.domains.asset.getIconUrl
import com.gemwallet.android.domains.asset.getSupportIconUrl
import com.gemwallet.android.domains.asset.iconChain
import com.gemwallet.android.domains.asset.supportIconChain
import com.gemwallet.android.ui.R
import com.wallet.core.primitives.Asset
import com.wallet.core.primitives.AssetId
import com.wallet.core.primitives.Chain

// Generated by scripts/convert-chain-icons.sh. Do not edit.
@DrawableRes
fun Chain.iconResource(): Int? = when (string) {
    "abstract" -> R.drawable.chain_abstract
    "algorand" -> R.drawable.chain_algorand
    "aptos" -> R.drawable.chain_aptos
    "arbitrum" -> R.drawable.chain_arbitrum
    "avalanchec" -> R.drawable.chain_avalanchec
    "base" -> R.drawable.chain_base
    "berachain" -> R.drawable.chain_berachain
    "bitcoin" -> R.drawable.chain_bitcoin
    "bitcoincash" -> R.drawable.chain_bitcoincash
    "blast" -> R.drawable.chain_blast
    "cardano" -> R.drawable.chain_cardano
    "celestia" -> R.drawable.chain_celestia
    "celo" -> R.drawable.chain_celo
    "cosmos" -> R.drawable.chain_cosmos
    "doge" -> R.drawable.chain_doge
    "ethereum" -> R.drawable.chain_ethereum
    "fantom" -> R.drawable.chain_fantom
    "gnosis" -> R.drawable.chain_gnosis
    "hypercore" -> R.drawable.chain_hypercore
    "hyperliquid" -> R.drawable.chain_hyperliquid
    "injective" -> R.drawable.chain_injective
    "ink" -> R.drawable.chain_ink
    "linea" -> R.drawable.chain_linea
    "litecoin" -> R.drawable.chain_litecoin
    "manta" -> R.drawable.chain_manta
    "mantle" -> R.drawable.chain_mantle
    "mayachain" -> R.drawable.chain_mayachain
    "monad" -> R.drawable.chain_monad
    "near" -> R.drawable.chain_near
    "noble" -> R.drawable.chain_noble
    "opbnb" -> R.drawable.chain_opbnb
    "optimism" -> R.drawable.chain_optimism
    "osmosis" -> R.drawable.chain_osmosis
    "plasma" -> R.drawable.chain_plasma
    "polkadot" -> R.drawable.chain_polkadot
    "polygon" -> R.drawable.chain_polygon
    "robinhood" -> R.drawable.chain_robinhood
    "sei" -> R.drawable.chain_sei
    "smartchain" -> R.drawable.chain_smartchain
    "solana" -> R.drawable.chain_solana
    "sonic" -> R.drawable.chain_sonic
    "stable" -> R.drawable.chain_stable
    "stellar" -> R.drawable.chain_stellar
    "sui" -> R.drawable.chain_sui
    "tempo" -> R.drawable.chain_tempo
    "thorchain" -> R.drawable.chain_thorchain
    "ton" -> R.drawable.chain_ton
    "tron" -> R.drawable.chain_tron
    "unichain" -> R.drawable.chain_unichain
    "world" -> R.drawable.chain_world
    "xlayer" -> R.drawable.chain_xlayer
    "xrp" -> R.drawable.chain_xrp
    "zcash" -> R.drawable.chain_zcash
    "zksync" -> R.drawable.chain_zksync
    else -> null
}

fun Chain.iconModel(): Any = iconChain().iconResource() ?: getIconUrl()

fun AssetId.iconModel(): Any = iconChain()?.iconResource() ?: getIconUrl()

fun AssetId.supportIconModel(): Any? = supportIconChain()?.iconResource() ?: getSupportIconUrl()

fun Asset.iconModel(): Any = id.iconModel()

fun Asset.supportIconModel(): Any? = id.supportIconModel()
