#!/usr/bin/env bash
# Converts the chain SVGs into vector drawables so the app renders them from
# resources instead of decoding SVG at runtime. Run after adding a chain icon.
set -euo pipefail

studio="/Applications/Android Studio.app/Contents"
jbr="$studio/jbr/Contents/Home/bin"
classpath="$studio/plugins/android/lib/*:$studio/lib/*"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
icons="$root/app/src/main/assets/chains/icons"
drawables="$root/ui/src/main/res/drawable"
mapping="$root/ui/src/main/kotlin/com/gemwallet/android/ui/components/image/ChainIcon.kt"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

cat > "$work/Convert.java" <<'JAVA'
import com.android.ide.common.vectordrawable.Svg2Vector;
import java.io.*;
import java.nio.file.*;

public class Convert {
    public static void main(String[] args) throws Exception {
        try (OutputStream stream = Files.newOutputStream(Paths.get(args[1]))) {
            String errors = Svg2Vector.parseSvgToXml(Paths.get(args[0]), stream);
            if (errors != null && !errors.isEmpty()) {
                System.out.println(Paths.get(args[0]).getFileName() + ": " + errors.replace('\n', ' '));
            }
        }
    }
}
JAVA

"$jbr/javac" -cp "$classpath" -d "$work" "$work/Convert.java"

names=()
for svg in "$icons"/*.svg; do
    name="$(basename "$svg" .svg)"
    "$jbr/java" -cp "$work:$classpath" Convert "$svg" "$drawables/chain_$name.xml"
    names+=("$name")
done

{
    echo "package com.gemwallet.android.ui.components.image"
    echo
    echo "import androidx.annotation.DrawableRes"
    echo "import com.gemwallet.android.domains.asset.getIconUrl"
    echo "import com.gemwallet.android.domains.asset.getSupportIconUrl"
    echo "import com.gemwallet.android.domains.asset.iconChain"
    echo "import com.gemwallet.android.domains.asset.supportIconChain"
    echo "import com.gemwallet.android.ui.R"
    echo "import com.wallet.core.primitives.Asset"
    echo "import com.wallet.core.primitives.AssetId"
    echo "import com.wallet.core.primitives.Chain"
    echo
    echo "// Generated by scripts/convert-chain-icons.sh. Do not edit."
    echo "@DrawableRes"
    echo "fun Chain.iconResource(): Int? = when (string) {"
    for name in "${names[@]}"; do
        echo "    \"$name\" -> R.drawable.chain_$name"
    done
    echo "    else -> null"
    echo "}"
    echo
    echo "fun Chain.iconModel(): Any = iconChain().iconResource() ?: getIconUrl()"
    echo
    echo "fun AssetId.iconModel(): Any = iconChain()?.iconResource() ?: getIconUrl()"
    echo
    echo "fun AssetId.supportIconModel(): Any? = supportIconChain()?.iconResource() ?: getSupportIconUrl()"
    echo
    echo "fun Asset.iconModel(): Any = id.iconModel()"
    echo
    echo "fun Asset.supportIconModel(): Any? = id.supportIconModel()"
} > "$mapping"

echo "converted ${#names[@]} icons"
