#!/usr/bin/env bash
# Converts the SVGs the iOS app ships into Android vector drawables, so both
# platforms draw the same artwork and Android renders it from resources instead
# of decoding SVG at runtime. Run after adding a chain or provider icon.
set -euo pipefail

studio="/Applications/Android Studio.app/Contents"
jbr="$studio/jbr/Contents/Home/bin"
classpath="$studio/plugins/android/lib/*:$studio/lib/*"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
catalog="$root/../ios/Packages/Style/Sources/Resources/Assets.xcassets"
drawables="$root/ui/src/main/res/drawable"
mapping="$root/ui/src/main/kotlin/com/gemwallet/android/ui/components/image/ChainIcon.kt"
icon_size=48
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

cat > "$work/Convert.java" <<'JAVA'
import com.android.ide.common.vectordrawable.Svg2Vector;
import java.io.*;
import java.nio.file.*;

public class Convert {
    public static void main(String[] args) throws Exception {
        try (OutputStream stream = Files.newOutputStream(Paths.get(args[1]))) {
            String errors = Svg2Vector.parseSvgToXml(Paths.get(args[0]), stream);
            if (errors != null && !errors.isEmpty()) {
                System.out.println(Paths.get(args[0]).getFileName() + ": " + errors.replace('\n', ' '));
            }
        }
    }
}
JAVA

"$jbr/javac" -cp "$classpath" -d "$work" "$work/Convert.java"

names=()
convert_set() {
    local catalog_set="$1" prefix="$2"
    names=()
    rm -f "$drawables/$prefix"*.xml
    for svg in "$catalog/$catalog_set"/*.imageset/*.svg; do
        local name
        name="$(basename "$(dirname "$svg")" .imageset)"
        "$jbr/java" -cp "$work:$classpath" Convert "$svg" "$drawables/$prefix$name.xml"
        sed -i '' -E 's/android:(width|height)="[0-9.]+dp"/android:\1="'"$icon_size"'dp"/' "$drawables/$prefix$name.xml"
        names+=("$name")
    done
}

convert_set chains chain_
chain_names=("${names[@]}")
convert_set swap_providers swap_provider_
swap_names=("${names[@]}")
convert_set fiat fiat_provider_
fiat_names=("${names[@]}")

{
    echo "package com.gemwallet.android.ui.components.image"
    echo
    echo "import androidx.annotation.DrawableRes"
    echo "import com.gemwallet.android.domains.asset.iconChain"
    echo "import com.gemwallet.android.domains.asset.remoteIconUrl"
    echo "import com.gemwallet.android.domains.asset.supportIconChain"
    echo "import com.gemwallet.android.ui.R"
    echo "import com.wallet.core.primitives.Asset"
    echo "import com.wallet.core.primitives.AssetId"
    echo "import com.wallet.core.primitives.Chain"
    echo
    echo "// Generated by scripts/convert-icons.sh. Do not edit."
    echo "@DrawableRes"
    echo "fun Chain.iconResource(): Int? = when (string) {"
    for name in "${chain_names[@]}"; do
        echo "    \"$name\" -> R.drawable.chain_$name"
    done
    echo "    else -> null"
    echo "}"
    echo
    echo "fun Chain.iconModel(): Any? = iconChain().iconResource()"
    echo
    echo "fun AssetId.iconModel(): Any? = iconChain()?.iconResource() ?: remoteIconUrl()"
    echo
    echo "fun AssetId.supportIconModel(): Any? = supportIconChain()?.iconResource()"
    echo
    echo "fun Asset.iconModel(): Any? = id.iconModel()"
    echo
    echo "fun Asset.supportIconModel(): Any? = id.supportIconModel()"
} > "$mapping"

echo "converted ${#chain_names[@]} chain, ${#swap_names[@]} swap and ${#fiat_names[@]} fiat icons"
