[package]
name = "gem_evm"
version = { workspace = true }
edition = { workspace = true }

[features]
default = []
rpc = ["dep:async-trait", "dep:chain_traits", "dep:futures", "dep:gem_client", "gem_jsonrpc/client"]
indexer = ["rpc", "dep:alchemy", "dep:ankr", "dep:blockscout"]
reqwest = ["rpc", "gem_jsonrpc/reqwest", "gem_client/reqwest"]
signer = ["dep:alloy-consensus", "dep:signer"]
chain_integration_tests = ["indexer", "reqwest", "primitives/testkit", "settings/testkit"]
testkit = ["gem_client?/testkit", "gem_jsonrpc/testkit"]

[dependencies]
primitives = { path = "../primitives" }
serde_serializers = { path = "../serde_serializers", features = ["bigint"] }
gem_jsonrpc = { path = "../gem_jsonrpc" }
alchemy = { path = "../alchemy", features = ["rpc"], optional = true }
ankr = { path = "../ankr", optional = true }
blockscout = { path = "../blockscout", optional = true }
gem_client = { path = "../gem_client", optional = true }
gem_hash = { path = "../gem_hash" }
signer = { path = "../signer", optional = true }

hex = { workspace = true }
futures = { workspace = true, optional = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true, features = ["eip712-serde"] }
alloy-consensus = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
bigdecimal = { workspace = true }
url = { workspace = true }

# rpc feature
chrono = { workspace = true }
async-trait = { workspace = true, optional = true }
chain_traits = { path = "../chain_traits", optional = true }

[dev-dependencies]
chain_traits = { path = "../chain_traits", features = ["testkit"] }
primitives = { path = "../primitives", features = ["testkit"] }
gem_client = { path = "../gem_client", features = ["testkit"] }
gem_jsonrpc = { path = "../gem_jsonrpc", features = ["testkit"] }
ankr = { path = "../ankr", features = ["testkit"] }
blockscout = { path = "../blockscout", features = ["testkit"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
num-bigint = { workspace = true }
settings = { path = "../settings", features = ["testkit"] }
async-trait = { workspace = true }
