// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

import BigInt
import Foundation
import Primitives

public extension Account {
    static func mock(
        chain: Chain = .bitcoin,
        address: String = "",
        derivationPath: String = "",
        extendedPublicKey: String? = nil,
    ) -> Account {
        Account(
            chain: chain,
            address: address,
            derivationPath: derivationPath,
            extendedPublicKey: extendedPublicKey,
        )
    }
}

public extension AddressName {
    static func mock(
        chain: Chain = .bitcoin,
        address: String = "",
        name: String = "",
        type: AddressType = .address,
        status: VerificationStatus = .verified,
        imageUrl: String? = nil,
    ) -> AddressName {
        AddressName(
            chain: chain,
            address: address,
            name: name,
            type: type,
            status: status,
            imageUrl: imageUrl,
        )
    }
}

public extension ApplicationMetadata {
    static func mock(
        name: String = "",
        description: String = "",
        url: String = "",
        icon: String = "",
        source: ApplicationMetadataSource = .walletConnect,
    ) -> ApplicationMetadata {
        ApplicationMetadata(
            name: name,
            description: description,
            url: url,
            icon: icon,
            source: source,
        )
    }
}

public extension Asset {
    static func mock(
        id: AssetId = .mock(),
        name: String = "",
        symbol: String = "",
        decimals: Int32 = 0,
        type: AssetType = .native,
    ) -> Asset {
        Asset(
            id: id,
            name: name,
            symbol: symbol,
            decimals: decimals,
            type: type,
        )
    }
}

public extension AssetBalance {
    static func mock(
        assetId: AssetId = .mock(),
        balance: Balance = .mock(),
        isActive: Bool = false,
    ) -> AssetBalance {
        AssetBalance(
            assetId: assetId,
            balance: balance,
            isActive: isActive,
        )
    }
}

public extension AssetBasic {
    static func mock(
        asset: Asset = .mock(),
        properties: AssetProperties = .mock(),
        score: AssetScore = .mock(),
        price: Price? = nil,
    ) -> AssetBasic {
        AssetBasic(
            asset: asset,
            properties: properties,
            score: score,
            price: price,
        )
    }
}

public extension AssetData {
    static func mock(
        asset: Asset = .mock(),
        balance: Balance = .mock(),
        account: Account = .mock(),
        price: Price? = nil,
        priceAlerts: [PriceAlert] = [],
        metadata: AssetMetaData = .mock(),
        associations: [AssetAssociation] = [],
    ) -> AssetData {
        AssetData(
            asset: asset,
            balance: balance,
            account: account,
            price: price,
            priceAlerts: priceAlerts,
            metadata: metadata,
            associations: associations,
        )
    }
}

public extension AssetFull {
    static func mock(
        asset: Asset = .mock(),
        properties: AssetProperties = .mock(),
        score: AssetScore = .mock(),
        tags: [String] = [],
        links: [AssetLink] = [],
        associations: [AssetAssociation] = [],
        perpetuals: [PerpetualBasic] = [],
        price: Price? = nil,
        market: AssetMarket? = nil,
    ) -> AssetFull {
        AssetFull(
            asset: asset,
            properties: properties,
            score: score,
            tags: tags,
            links: links,
            associations: associations,
            perpetuals: perpetuals,
            price: price,
            market: market,
        )
    }
}

public extension AssetLink {
    static func mock(
        name: String = "",
        url: String = "",
    ) -> AssetLink {
        AssetLink(
            name: name,
            url: url,
        )
    }
}

public extension AssetMarket {
    static func mock(
        marketCap: Double? = nil,
        marketCapFdv: Double? = nil,
        marketCapRank: Int32? = nil,
        totalVolume: Double? = nil,
        circulatingSupply: Double? = nil,
        totalSupply: Double? = nil,
        maxSupply: Double? = nil,
        allTimeHighValue: ChartValuePercentage? = nil,
        allTimeLowValue: ChartValuePercentage? = nil,
    ) -> AssetMarket {
        AssetMarket(
            marketCap: marketCap,
            marketCapFdv: marketCapFdv,
            marketCapRank: marketCapRank,
            totalVolume: totalVolume,
            circulatingSupply: circulatingSupply,
            totalSupply: totalSupply,
            maxSupply: maxSupply,
            allTimeHighValue: allTimeHighValue,
            allTimeLowValue: allTimeLowValue,
        )
    }
}

public extension AssetMetaData {
    static func mock(
        isEnabled: Bool = false,
        isBalanceEnabled: Bool = false,
        isBuyEnabled: Bool = false,
        isSellEnabled: Bool = false,
        isSwapEnabled: Bool = false,
        isStakeEnabled: Bool = false,
        isEarnEnabled: Bool = false,
        isPinned: Bool = false,
        isActive: Bool = false,
        stakingApr: Double? = nil,
        earnApr: Double? = nil,
        rankScore: Int32 = 0,
    ) -> AssetMetaData {
        AssetMetaData(
            isEnabled: isEnabled,
            isBalanceEnabled: isBalanceEnabled,
            isBuyEnabled: isBuyEnabled,
            isSellEnabled: isSellEnabled,
            isSwapEnabled: isSwapEnabled,
            isStakeEnabled: isStakeEnabled,
            isEarnEnabled: isEarnEnabled,
            isPinned: isPinned,
            isActive: isActive,
            stakingApr: stakingApr,
            earnApr: earnApr,
            rankScore: rankScore,
        )
    }
}

public extension AssetPrice {
    static func mock(
        assetId: AssetId = .mock(),
        price: Double = 0,
        priceChangePercentage24h: Double = 0,
        updatedAt: Date = Date(timeIntervalSince1970: 0),
    ) -> AssetPrice {
        AssetPrice(
            assetId: assetId,
            price: price,
            priceChangePercentage24h: priceChangePercentage24h,
            updatedAt: updatedAt,
        )
    }
}

public extension AssetProperties {
    static func mock(
        isEnabled: Bool = false,
        isBuyable: Bool = false,
        isSellable: Bool = false,
        isSwapable: Bool = false,
        isStakeable: Bool = false,
        stakingApr: Double? = nil,
        isEarnable: Bool = false,
        earnApr: Double? = nil,
        hasImage: Bool = false,
    ) -> AssetProperties {
        AssetProperties(
            isEnabled: isEnabled,
            isBuyable: isBuyable,
            isSellable: isSellable,
            isSwapable: isSwapable,
            isStakeable: isStakeable,
            stakingApr: stakingApr,
            isEarnable: isEarnable,
            earnApr: earnApr,
            hasImage: hasImage,
        )
    }
}

public extension AssetScore {
    static func mock(
        rank: Int32 = 0,
    ) -> AssetScore {
        AssetScore(
            rank: rank,
        )
    }
}

public extension Balance {
    static func mock(
        available: BigIntValue = 0,
        frozen: BigIntValue = 0,
        locked: BigIntValue = 0,
        staked: BigIntValue = 0,
        pending: BigIntValue = 0,
        pendingUnconfirmed: BigIntValue = 0,
        rewards: BigIntValue = 0,
        reserved: BigIntValue = 0,
        earn: BigIntValue = 0,
        withdrawable: BigIntValue = 0,
        metadata: BalanceMetadata? = nil,
    ) -> Balance {
        Balance(
            available: available,
            frozen: frozen,
            locked: locked,
            staked: staked,
            pending: pending,
            pendingUnconfirmed: pendingUnconfirmed,
            rewards: rewards,
            reserved: reserved,
            earn: earn,
            withdrawable: withdrawable,
            metadata: metadata,
        )
    }
}

public extension Banner {
    static func mock(
        walletId: WalletId? = nil,
        asset: Asset? = nil,
        event: BannerEvent = .stake,
        state: BannerState = .active,
    ) -> Banner {
        Banner(
            walletId: walletId,
            asset: asset,
            event: event,
            state: state,
        )
    }
}

public extension BlockExplorerLink {
    static func mock(
        name: String = "",
        link: String = "",
    ) -> BlockExplorerLink {
        BlockExplorerLink(
            name: name,
            link: link,
        )
    }
}

public extension ChainAssetData {
    static func mock(
        assetData: AssetData = .mock(),
        feeAssetData: AssetData = .mock(),
    ) -> ChainAssetData {
        ChainAssetData(
            assetData: assetData,
            feeAssetData: feeAssetData,
        )
    }
}

public extension ChartCandleStick {
    static func mock(
        date: Date = Date(timeIntervalSince1970: 0),
        open: Double = 0,
        high: Double = 0,
        low: Double = 0,
        close: Double = 0,
        volume: Double = 0,
    ) -> ChartCandleStick {
        ChartCandleStick(
            date: date,
            open: open,
            high: high,
            low: low,
            close: close,
            volume: volume,
        )
    }
}

public extension ChartDateValue {
    static func mock(
        date: Date = Date(timeIntervalSince1970: 0),
        value: Double = 0,
    ) -> ChartDateValue {
        ChartDateValue(
            date: date,
            value: value,
        )
    }
}

public extension ChartValuePercentage {
    static func mock(
        date: Date = Date(timeIntervalSince1970: 0),
        value: Float = 0,
        percentage: Float = 0,
    ) -> ChartValuePercentage {
        ChartValuePercentage(
            date: date,
            value: value,
            percentage: percentage,
        )
    }
}

public extension Contact {
    static func mock(
        id: String = "",
        name: String = "",
        description: String? = nil,
        imageUrl: String? = nil,
        createdAt: Date = Date(timeIntervalSince1970: 0),
        updatedAt: Date = Date(timeIntervalSince1970: 0),
    ) -> Contact {
        Contact(
            id: id,
            name: name,
            description: description,
            imageUrl: imageUrl,
            createdAt: createdAt,
            updatedAt: updatedAt,
        )
    }
}

public extension ContactAddress {
    static func mock(
        id: String = "",
        contactId: String = "",
        address: String = "",
        chain: Chain = .bitcoin,
        memo: String? = nil,
    ) -> ContactAddress {
        ContactAddress(
            id: id,
            contactId: contactId,
            address: address,
            chain: chain,
            memo: memo,
        )
    }
}

public extension ContactData {
    static func mock(
        contact: Contact = .mock(),
        addresses: [ContactAddress] = [],
    ) -> ContactData {
        ContactData(
            contact: contact,
            addresses: addresses,
        )
    }
}

public extension CoreListItem {
    static func mock(
        id: String = "",
        title: String = "",
        subtitle: String? = nil,
        value: String? = nil,
        subvalue: String? = nil,
        icon: CoreListItemIcon? = nil,
        badge: CoreListItemBadge? = nil,
        url: String? = nil,
    ) -> CoreListItem {
        CoreListItem(
            id: id,
            title: title,
            subtitle: subtitle,
            value: value,
            subvalue: subvalue,
            icon: icon,
            badge: badge,
            url: url,
        )
    }
}

public extension Delegation {
    static func mock(
        base: DelegationBase = .mock(),
        validator: DelegationValidator = .mock(),
        price: Price? = nil,
    ) -> Delegation {
        Delegation(
            base: base,
            validator: validator,
            price: price,
        )
    }
}

public extension DelegationBase {
    static func mock(
        assetId: AssetId = .mock(),
        state: DelegationState = .active,
        balance: BigIntValue = 0,
        shares: BigIntValue = 0,
        rewards: BigIntValue = 0,
        completionDate: Date? = nil,
        delegationId: String = "",
        validatorId: String = "",
    ) -> DelegationBase {
        DelegationBase(
            assetId: assetId,
            state: state,
            balance: balance,
            shares: shares,
            rewards: rewards,
            completionDate: completionDate,
            delegationId: delegationId,
            validatorId: validatorId,
        )
    }
}

public extension DelegationValidator {
    static func mock(
        chain: Chain = .bitcoin,
        id: String = "",
        name: String = "",
        isActive: Bool = false,
        commission: Double = 0,
        apr: Double = 0,
        providerType: StakeProviderType = .stake,
    ) -> DelegationValidator {
        DelegationValidator(
            chain: chain,
            id: id,
            name: name,
            isActive: isActive,
            commission: commission,
            apr: apr,
            providerType: providerType,
        )
    }
}

public extension Device {
    static func mock(
        id: String = "",
        platform: Platform = .ios,
        platformStore: PlatformStore = .appStore,
        os: String = "",
        model: String = "",
        token: String = "",
        locale: DeviceLocale = .ar,
        version: String = "",
        currency: Currency = .mxn,
        isPushEnabled: Bool = false,
        isPriceAlertsEnabled: Bool? = nil,
        subscriptionsVersion: Int32 = 0,
    ) -> Device {
        Device(
            id: id,
            platform: platform,
            platformStore: platformStore,
            os: os,
            model: model,
            token: token,
            locale: locale,
            version: version,
            currency: currency,
            isPushEnabled: isPushEnabled,
            isPriceAlertsEnabled: isPriceAlertsEnabled,
            subscriptionsVersion: subscriptionsVersion,
        )
    }
}

public extension FiatRate {
    static func mock(
        symbol: Currency = .mxn,
        rate: Double = 0,
    ) -> FiatRate {
        FiatRate(
            symbol: symbol,
            rate: rate,
        )
    }
}

public extension FiatTransaction {
    static func mock(
        id: String = "",
        assetId: AssetId = .mock(),
        transactionType: FiatQuoteType = .buy,
        provider: FiatProviderName = .mercuryo,
        status: FiatTransactionStatus = .complete,
        fiatAmount: Double = 0,
        fiatCurrency: String = "",
        value: String = "0",
        createdAt: Date = Date(timeIntervalSince1970: 0),
        updatedAt: Date = Date(timeIntervalSince1970: 0),
    ) -> FiatTransaction {
        FiatTransaction(
            id: id,
            assetId: assetId,
            transactionType: transactionType,
            provider: provider,
            status: status,
            fiatAmount: fiatAmount,
            fiatCurrency: fiatCurrency,
            value: value,
            createdAt: createdAt,
            updatedAt: updatedAt,
        )
    }
}

public extension FiatTransactionAssetData {
    static func mock(
        id: String = "",
        asset: Asset = .mock(),
        transactionType: FiatQuoteType = .buy,
        provider: FiatProviderName = .mercuryo,
        status: FiatTransactionStatus = .complete,
        fiatAmount: Double = 0,
        fiatCurrency: String = "",
        value: String = "0",
        createdAt: Date = Date(timeIntervalSince1970: 0),
        detailsUrl: String? = nil,
    ) -> FiatTransactionAssetData {
        FiatTransactionAssetData(
            id: id,
            asset: asset,
            transactionType: transactionType,
            provider: provider,
            status: status,
            fiatAmount: fiatAmount,
            fiatCurrency: fiatCurrency,
            value: value,
            createdAt: createdAt,
            detailsUrl: detailsUrl,
        )
    }
}

public extension FiatTransactionData {
    static func mock(
        transaction: FiatTransaction = .mock(),
        detailsUrl: String? = nil,
    ) -> FiatTransactionData {
        FiatTransactionData(
            transaction: transaction,
            detailsUrl: detailsUrl,
        )
    }
}

public extension InAppNotification {
    static func mock(
        walletId: WalletId = .mock(),
        readAt: Date? = nil,
        createdAt: Date = Date(timeIntervalSince1970: 0),
        item: CoreListItem = .mock(),
    ) -> InAppNotification {
        InAppNotification(
            walletId: walletId,
            readAt: readAt,
            createdAt: createdAt,
            item: item,
        )
    }
}

public extension Latency {
    static func mock(
        latencyType: LatencyType = .fast,
        value: Double = 0,
    ) -> Latency {
        Latency(
            latencyType: latencyType,
            value: value,
        )
    }
}

public extension NFTAsset {
    static func mock(
        id: NFTAssetId = .mock(),
        collectionId: NFTCollectionId = .mock(),
        contractAddress: String? = nil,
        tokenId: String = "",
        tokenType: NFTType = .erc721,
        name: String = "",
        description: String? = nil,
        chain: Chain = .bitcoin,
        resource: NFTResource = .mock(),
        images: NFTImages = .mock(),
        attributes: [NFTAttribute] = [],
    ) -> NFTAsset {
        NFTAsset(
            id: id,
            collectionId: collectionId,
            contractAddress: contractAddress,
            tokenId: tokenId,
            tokenType: tokenType,
            name: name,
            description: description,
            chain: chain,
            resource: resource,
            images: images,
            attributes: attributes,
        )
    }
}

public extension NFTAssetData {
    static func mock(
        collection: NFTCollection = .mock(),
        asset: NFTAsset = .mock(),
    ) -> NFTAssetData {
        NFTAssetData(
            collection: collection,
            asset: asset,
        )
    }
}

public extension NFTCollection {
    static func mock(
        id: NFTCollectionId = .mock(),
        name: String = "",
        description: String? = nil,
        chain: Chain = .bitcoin,
        contractAddress: String = "",
        images: NFTImages = .mock(),
        status: VerificationStatus = .verified,
        links: [AssetLink] = [],
    ) -> NFTCollection {
        NFTCollection(
            id: id,
            name: name,
            description: description,
            chain: chain,
            contractAddress: contractAddress,
            images: images,
            status: status,
            links: links,
        )
    }
}

public extension NFTData {
    static func mock(
        collection: NFTCollection = .mock(),
        assets: [NFTAsset] = [],
    ) -> NFTData {
        NFTData(
            collection: collection,
            assets: assets,
        )
    }
}

public extension NFTImages {
    static func mock(
        preview: NFTResource = .mock(),
    ) -> NFTImages {
        NFTImages(
            preview: preview,
        )
    }
}

public extension NFTResource {
    static func mock(
        url: String = "",
        mimeType: String = "",
    ) -> NFTResource {
        NFTResource(
            url: url,
            mimeType: mimeType,
        )
    }
}

public extension Perpetual {
    static func mock(
        id: PerpetualId = .mock(),
        name: String = "",
        provider: PerpetualProvider = .hypercore,
        assetId: AssetId = .mock(),
        identifier: String = "",
        price: Double = 0,
        pricePercentChange24h: Double = 0,
        openInterest: Double = 0,
        volume24h: Double = 0,
        funding: Double = 0,
        maxLeverage: UInt8 = 0,
        isIsolatedOnly: Bool = false,
    ) -> Perpetual {
        Perpetual(
            id: id,
            name: name,
            provider: provider,
            assetId: assetId,
            identifier: identifier,
            price: price,
            pricePercentChange24h: pricePercentChange24h,
            openInterest: openInterest,
            volume24h: volume24h,
            funding: funding,
            maxLeverage: maxLeverage,
            isIsolatedOnly: isIsolatedOnly,
        )
    }
}

public extension PerpetualData {
    static func mock(
        perpetual: Perpetual = .mock(),
        asset: Asset = .mock(),
        metadata: PerpetualMetadata = .mock(),
    ) -> PerpetualData {
        PerpetualData(
            perpetual: perpetual,
            asset: asset,
            metadata: metadata,
        )
    }
}

public extension PerpetualMetadata {
    static func mock(
        isPinned: Bool = false,
    ) -> PerpetualMetadata {
        PerpetualMetadata(
            isPinned: isPinned,
        )
    }
}

public extension PerpetualPosition {
    static func mock(
        id: String = "",
        perpetualId: PerpetualId = .mock(),
        assetId: AssetId = .mock(),
        size: Double = 0,
        sizeValue: Double = 0,
        leverage: UInt8 = 0,
        entryPrice: Double = 0,
        liquidationPrice: Double? = nil,
        marginType: PerpetualMarginType = .cross,
        direction: PerpetualDirection = .short,
        marginAmount: Double = 0,
        takeProfit: PerpetualTriggerOrder? = nil,
        stopLoss: PerpetualTriggerOrder? = nil,
        pnl: Double = 0,
        funding: Float? = nil,
    ) -> PerpetualPosition {
        PerpetualPosition(
            id: id,
            perpetualId: perpetualId,
            assetId: assetId,
            size: size,
            sizeValue: sizeValue,
            leverage: leverage,
            entryPrice: entryPrice,
            liquidationPrice: liquidationPrice,
            marginType: marginType,
            direction: direction,
            marginAmount: marginAmount,
            takeProfit: takeProfit,
            stopLoss: stopLoss,
            pnl: pnl,
            funding: funding,
        )
    }
}

public extension PerpetualPositionData {
    static func mock(
        perpetual: Perpetual = .mock(),
        asset: Asset = .mock(),
        position: PerpetualPosition = .mock(),
    ) -> PerpetualPositionData {
        PerpetualPositionData(
            perpetual: perpetual,
            asset: asset,
            position: position,
        )
    }
}

public extension Price {
    static func mock(
        price: Double = 0,
        priceChangePercentage24h: Double = 0,
        updatedAt: Date = Date(timeIntervalSince1970: 0),
    ) -> Price {
        Price(
            price: price,
            priceChangePercentage24h: priceChangePercentage24h,
            updatedAt: updatedAt,
        )
    }
}

public extension PriceAlert {
    static func mock(
        assetId: AssetId = .mock(),
        currency: Currency = .mxn,
        price: Double? = nil,
        pricePercentChange: Double? = nil,
        priceDirection: PriceAlertDirection? = nil,
        lastNotifiedAt: Date? = nil,
    ) -> PriceAlert {
        PriceAlert(
            assetId: assetId,
            currency: currency,
            price: price,
            pricePercentChange: pricePercentChange,
            priceDirection: priceDirection,
            lastNotifiedAt: lastNotifiedAt,
        )
    }
}

public extension PriceAlertData {
    static func mock(
        asset: Asset = .mock(),
        price: Price? = nil,
        priceAlert: PriceAlert = .mock(),
        rankScore: Int32 = 0,
    ) -> PriceAlertData {
        PriceAlertData(
            asset: asset,
            price: price,
            priceAlert: priceAlert,
            rankScore: rankScore,
        )
    }
}

public extension RecentAsset {
    static func mock(
        asset: Asset = .mock(),
        createdAt: Date = Date(timeIntervalSince1970: 0),
    ) -> RecentAsset {
        RecentAsset(
            asset: asset,
            createdAt: createdAt,
        )
    }
}

public extension SupportAgent {
    static func mock(
        name: String = "",
    ) -> SupportAgent {
        SupportAgent(
            name: name,
        )
    }
}

public extension SupportMessage {
    static func mock(
        id: String = "",
        content: String = "",
        sender: SupportMessageSender = .user,
        status: SupportMessageStatus = .sending,
        createdAt: Date = Date(timeIntervalSince1970: 0),
        images: [SupportMessageImage] = [],
    ) -> SupportMessage {
        SupportMessage(
            id: id,
            content: content,
            sender: sender,
            status: status,
            createdAt: createdAt,
            images: images,
        )
    }
}

public extension SupportMessageImage {
    static func mock(
        id: String = "",
        url: String = "",
        thumbnailUrl: String? = nil,
        fileName: String? = nil,
        fileSize: UInt64? = nil,
        width: Int32? = nil,
        height: Int32? = nil,
    ) -> SupportMessageImage {
        SupportMessageImage(
            id: id,
            url: url,
            thumbnailUrl: thumbnailUrl,
            fileName: fileName,
            fileSize: fileSize,
            width: width,
            height: height,
        )
    }
}

public extension Transaction {
    static func mock(
        id: TransactionId = .mock(),
        assetId: AssetId = .mock(),
        from: String = "",
        to: String = "",
        contract: String? = nil,
        type: TransactionType = .transfer,
        state: TransactionState = .pending,
        blockNumber: String? = nil,
        sequence: String? = nil,
        fee: String = "0",
        feeAssetId: AssetId = .mock(),
        value: String = "0",
        memo: String? = nil,
        direction: TransactionDirection = .selfTransfer,
        utxoInputs: [TransactionUtxoInput]? = nil,
        utxoOutputs: [TransactionUtxoInput]? = nil,
        metadata: AnyCodableValue? = nil,
        createdAt: Date = Date(timeIntervalSince1970: 0),
    ) -> Transaction {
        Transaction(
            id: id,
            assetId: assetId,
            from: from,
            to: to,
            contract: contract,
            type: type,
            state: state,
            blockNumber: blockNumber,
            sequence: sequence,
            fee: fee,
            feeAssetId: feeAssetId,
            value: value,
            memo: memo,
            direction: direction,
            utxoInputs: utxoInputs,
            utxoOutputs: utxoOutputs,
            metadata: metadata,
            createdAt: createdAt,
        )
    }
}

public extension TransactionExtended {
    static func mock(
        recordId: UInt64 = 0,
        transaction: Transaction = .mock(),
        asset: Asset = .mock(),
        feeAsset: Asset = .mock(),
        price: Price? = nil,
        feePrice: Price? = nil,
        assets: [Asset] = [],
        prices: [AssetPrice] = [],
        fromAddress: AddressName? = nil,
        toAddress: AddressName? = nil,
        confirmationEtaSeconds: UInt32? = nil,
    ) -> TransactionExtended {
        TransactionExtended(
            recordId: recordId,
            transaction: transaction,
            asset: asset,
            feeAsset: feeAsset,
            price: price,
            feePrice: feePrice,
            assets: assets,
            prices: prices,
            fromAddress: fromAddress,
            toAddress: toAddress,
            confirmationEtaSeconds: confirmationEtaSeconds,
        )
    }
}

public extension TransactionListItem {
    static func mock(
        transaction: Transaction = .mock(),
        asset: Asset = .mock(),
        assets: [Asset] = [],
        fromAddress: AddressName? = nil,
        toAddress: AddressName? = nil,
    ) -> TransactionListItem {
        TransactionListItem(
            transaction: transaction,
            asset: asset,
            assets: assets,
            fromAddress: fromAddress,
            toAddress: toAddress,
        )
    }
}

public extension TransactionSwapMetadata {
    static func mock(
        fromAsset: AssetId = .mock(),
        fromValue: String = "0",
        toAsset: AssetId = .mock(),
        toValue: String = "0",
        provider: String? = nil,
    ) -> TransactionSwapMetadata {
        TransactionSwapMetadata(
            fromAsset: fromAsset,
            fromValue: fromValue,
            toAsset: toAsset,
            toValue: toValue,
            provider: provider,
        )
    }
}

public extension TransactionsFilter {
    static func mock(
        assetId: AssetId? = nil,
        chains: [Chain] = [],
        transactionTypes: [TransactionType] = [],
        states: [TransactionState] = [],
        assetRankGreaterThan: Int32? = nil,
    ) -> TransactionsFilter {
        TransactionsFilter(
            assetId: assetId,
            chains: chains,
            transactionTypes: transactionTypes,
            states: states,
            assetRankGreaterThan: assetRankGreaterThan,
        )
    }
}

public extension WCPairingProposal {
    static func mock(
        pairingId: String = "",
        proposal: WalletConnectionSessionProposal = .mock(),
        verificationStatus: WalletConnectionVerificationStatus = .verified,
    ) -> WCPairingProposal {
        WCPairingProposal(
            pairingId: pairingId,
            proposal: proposal,
            verificationStatus: verificationStatus,
        )
    }
}

public extension Wallet {
    static func mock(
        id: WalletId = .mock(),
        externalId: String? = nil,
        name: String = "",
        index: Int32 = 0,
        type: WalletType = .multicoin,
        accounts: [Account] = [],
        isPinned: Bool = false,
        imageUrl: String? = nil,
        source: WalletSource = .create,
    ) -> Wallet {
        Wallet(
            id: id,
            externalId: externalId,
            name: name,
            index: index,
            type: type,
            accounts: accounts,
            isPinned: isPinned,
            imageUrl: imageUrl,
            source: source,
        )
    }
}

public extension WalletConnection {
    static func mock(
        session: WalletConnectionSession = .mock(),
        wallet: Wallet = .mock(),
    ) -> WalletConnection {
        WalletConnection(
            session: session,
            wallet: wallet,
        )
    }
}

public extension WalletConnectionSession {
    static func mock(
        id: String = "",
        sessionId: String = "",
        state: WalletConnectionState = .started,
        chains: [Chain] = [],
        createdAt: Date = Date(timeIntervalSince1970: 0),
        expireAt: Date = Date(timeIntervalSince1970: 0),
        metadata: ApplicationMetadata = .mock(),
    ) -> WalletConnectionSession {
        WalletConnectionSession(
            id: id,
            sessionId: sessionId,
            state: state,
            chains: chains,
            createdAt: createdAt,
            expireAt: expireAt,
            metadata: metadata,
        )
    }
}

public extension WalletConnectionSessionProposal {
    static func mock(
        defaultWallet: Wallet = .mock(),
        wallets: [Wallet] = [],
        metadata: ApplicationMetadata = .mock(),
    ) -> WalletConnectionSessionProposal {
        WalletConnectionSessionProposal(
            defaultWallet: defaultWallet,
            wallets: wallets,
            metadata: metadata,
        )
    }
}
