// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

import Foundation
import Primitives

public extension AddressName {
    static func mock(
        chain: Chain = .bitcoin,
        address: String = "",
        name: String = "",
        type: AddressType = .address,
        status: VerificationStatus = .verified,
        imageUrl: String? = nil,
    ) -> AddressName {
        AddressName(
            chain: chain,
            address: address,
            name: name,
            type: type,
            status: status,
            imageUrl: imageUrl,
        )
    }
}

public extension Asset {
    static func mock(
        id: AssetId = .mock(),
        name: String = "",
        symbol: String = "",
        decimals: Int32 = 0,
        type: AssetType = .native,
    ) -> Asset {
        Asset(
            id: id,
            name: name,
            symbol: symbol,
            decimals: decimals,
            type: type,
        )
    }
}

public extension AssetScore {
    static func mock(
        rank: Int32 = 0,
    ) -> AssetScore {
        AssetScore(
            rank: rank,
        )
    }
}

public extension NFTAsset {
    static func mock(
        id: NFTAssetId = .mock(),
        collectionId: NFTCollectionId = .mock(),
        contractAddress: String? = nil,
        tokenId: String = "",
        tokenType: NFTType = .erc721,
        name: String = "",
        description: String? = nil,
        chain: Chain = .bitcoin,
        resource: NFTResource = .mock(),
        images: NFTImages = .mock(),
        attributes: [NFTAttribute] = [],
    ) -> NFTAsset {
        NFTAsset(
            id: id,
            collectionId: collectionId,
            contractAddress: contractAddress,
            tokenId: tokenId,
            tokenType: tokenType,
            name: name,
            description: description,
            chain: chain,
            resource: resource,
            images: images,
            attributes: attributes,
        )
    }
}

public extension NFTAssetData {
    static func mock(
        collection: NFTCollection = .mock(),
        asset: NFTAsset = .mock(),
    ) -> NFTAssetData {
        NFTAssetData(
            collection: collection,
            asset: asset,
        )
    }
}

public extension NFTCollection {
    static func mock(
        id: NFTCollectionId = .mock(),
        name: String = "",
        description: String? = nil,
        chain: Chain = .bitcoin,
        contractAddress: String = "",
        images: NFTImages = .mock(),
        status: VerificationStatus = .verified,
        links: [AssetLink] = [],
    ) -> NFTCollection {
        NFTCollection(
            id: id,
            name: name,
            description: description,
            chain: chain,
            contractAddress: contractAddress,
            images: images,
            status: status,
            links: links,
        )
    }
}

public extension NFTData {
    static func mock(
        collection: NFTCollection = .mock(),
        assets: [NFTAsset] = [],
    ) -> NFTData {
        NFTData(
            collection: collection,
            assets: assets,
        )
    }
}

public extension NFTImages {
    static func mock(
        preview: NFTResource = .mock(),
    ) -> NFTImages {
        NFTImages(
            preview: preview,
        )
    }
}

public extension NFTResource {
    static func mock(
        url: String = "",
        mimeType: String = "",
    ) -> NFTResource {
        NFTResource(
            url: url,
            mimeType: mimeType,
        )
    }
}

public extension NameRecord {
    static func mock(
        name: String = "",
        chain: Chain = .bitcoin,
        address: String = "",
        provider: NameProvider = .ud,
    ) -> NameRecord {
        NameRecord(
            name: name,
            chain: chain,
            address: address,
            provider: provider,
        )
    }
}

public extension PriceAlert {
    static func mock(
        assetId: AssetId = .mock(),
        currency: Currency = .mxn,
        price: Double? = nil,
        pricePercentChange: Double? = nil,
        priceDirection: PriceAlertDirection? = nil,
        lastNotifiedAt: Date? = nil,
    ) -> PriceAlert {
        PriceAlert(
            assetId: assetId,
            currency: currency,
            price: price,
            pricePercentChange: pricePercentChange,
            priceDirection: priceDirection,
            lastNotifiedAt: lastNotifiedAt,
        )
    }
}

public extension TotalFiatValue {
    static func mock(
        value: Double = 0,
        pnlAmount: Double = 0,
        pnlPercentage: Double = 0,
    ) -> TotalFiatValue {
        TotalFiatValue(
            value: value,
            pnlAmount: pnlAmount,
            pnlPercentage: pnlPercentage,
        )
    }
}
