// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

import Foundation
import Primitives

public extension Account {
    static func mock(
        chain: Chain = .bitcoin,
        address: String = "",
        derivationPath: String = "",
        extendedPublicKey: String? = nil,
    ) -> Account {
        Account(
            chain: chain,
            address: address,
            derivationPath: derivationPath,
            extendedPublicKey: extendedPublicKey,
        )
    }
}

public extension AddressName {
    static func mock(
        chain: Chain = .bitcoin,
        address: String = "",
        name: String = "",
        type: AddressType = .address,
        status: VerificationStatus = .verified,
        imageUrl: String? = nil,
    ) -> AddressName {
        AddressName(
            chain: chain,
            address: address,
            name: name,
            type: type,
            status: status,
            imageUrl: imageUrl,
        )
    }
}

public extension Asset {
    static func mock(
        id: AssetId = .mock(),
        name: String = "",
        symbol: String = "",
        decimals: Int32 = 0,
        type: AssetType = .native,
    ) -> Asset {
        Asset(
            id: id,
            name: name,
            symbol: symbol,
            decimals: decimals,
            type: type,
        )
    }
}

public extension AssetBasic {
    static func mock(
        asset: Asset = .mock(),
        properties: AssetProperties = .mock(),
        score: AssetScore = .mock(),
        price: Price? = nil,
    ) -> AssetBasic {
        AssetBasic(
            asset: asset,
            properties: properties,
            score: score,
            price: price,
        )
    }
}

public extension AssetFull {
    static func mock(
        asset: Asset = .mock(),
        properties: AssetProperties = .mock(),
        score: AssetScore = .mock(),
        tags: [String] = [],
        links: [AssetLink] = [],
        associations: [AssetAssociation] = [],
        perpetuals: [PerpetualBasic] = [],
        price: Price? = nil,
        market: AssetMarket? = nil,
    ) -> AssetFull {
        AssetFull(
            asset: asset,
            properties: properties,
            score: score,
            tags: tags,
            links: links,
            associations: associations,
            perpetuals: perpetuals,
            price: price,
            market: market,
        )
    }
}

public extension AssetLink {
    static func mock(
        name: String = "",
        url: String = "",
    ) -> AssetLink {
        AssetLink(
            name: name,
            url: url,
        )
    }
}

public extension AssetMarket {
    static func mock(
        marketCap: Double? = nil,
        marketCapFdv: Double? = nil,
        marketCapRank: Int32? = nil,
        totalVolume: Double? = nil,
        circulatingSupply: Double? = nil,
        totalSupply: Double? = nil,
        maxSupply: Double? = nil,
        allTimeHighValue: ChartValuePercentage? = nil,
        allTimeLowValue: ChartValuePercentage? = nil,
    ) -> AssetMarket {
        AssetMarket(
            marketCap: marketCap,
            marketCapFdv: marketCapFdv,
            marketCapRank: marketCapRank,
            totalVolume: totalVolume,
            circulatingSupply: circulatingSupply,
            totalSupply: totalSupply,
            maxSupply: maxSupply,
            allTimeHighValue: allTimeHighValue,
            allTimeLowValue: allTimeLowValue,
        )
    }
}

public extension AssetMetaData {
    static func mock(
        isEnabled: Bool = false,
        isBalanceEnabled: Bool = false,
        isBuyEnabled: Bool = false,
        isSellEnabled: Bool = false,
        isSwapEnabled: Bool = false,
        isStakeEnabled: Bool = false,
        isEarnEnabled: Bool = false,
        isPinned: Bool = false,
        isActive: Bool = false,
        stakingApr: Double? = nil,
        earnApr: Double? = nil,
        rankScore: Int32 = 0,
    ) -> AssetMetaData {
        AssetMetaData(
            isEnabled: isEnabled,
            isBalanceEnabled: isBalanceEnabled,
            isBuyEnabled: isBuyEnabled,
            isSellEnabled: isSellEnabled,
            isSwapEnabled: isSwapEnabled,
            isStakeEnabled: isStakeEnabled,
            isEarnEnabled: isEarnEnabled,
            isPinned: isPinned,
            isActive: isActive,
            stakingApr: stakingApr,
            earnApr: earnApr,
            rankScore: rankScore,
        )
    }
}

public extension AssetPrice {
    static func mock(
        assetId: AssetId = .mock(),
        price: Double = 0,
        priceChangePercentage24h: Double = 0,
        updatedAt: Date = Date(timeIntervalSince1970: 0),
    ) -> AssetPrice {
        AssetPrice(
            assetId: assetId,
            price: price,
            priceChangePercentage24h: priceChangePercentage24h,
            updatedAt: updatedAt,
        )
    }
}

public extension AssetProperties {
    static func mock(
        isEnabled: Bool = false,
        isBuyable: Bool = false,
        isSellable: Bool = false,
        isSwapable: Bool = false,
        isStakeable: Bool = false,
        stakingApr: Double? = nil,
        isEarnable: Bool = false,
        earnApr: Double? = nil,
        hasImage: Bool = false,
    ) -> AssetProperties {
        AssetProperties(
            isEnabled: isEnabled,
            isBuyable: isBuyable,
            isSellable: isSellable,
            isSwapable: isSwapable,
            isStakeable: isStakeable,
            stakingApr: stakingApr,
            isEarnable: isEarnable,
            earnApr: earnApr,
            hasImage: hasImage,
        )
    }
}

public extension AssetScore {
    static func mock(
        rank: Int32 = 0,
    ) -> AssetScore {
        AssetScore(
            rank: rank,
        )
    }
}

public extension ChartCandleStick {
    static func mock(
        date: Date = Date(timeIntervalSince1970: 0),
        open: Double = 0,
        high: Double = 0,
        low: Double = 0,
        close: Double = 0,
        volume: Double = 0,
    ) -> ChartCandleStick {
        ChartCandleStick(
            date: date,
            open: open,
            high: high,
            low: low,
            close: close,
            volume: volume,
        )
    }
}

public extension ChartDateValue {
    static func mock(
        date: Date = Date(timeIntervalSince1970: 0),
        value: Double = 0,
    ) -> ChartDateValue {
        ChartDateValue(
            date: date,
            value: value,
        )
    }
}

public extension NFTAsset {
    static func mock(
        id: NFTAssetId = .mock(),
        collectionId: NFTCollectionId = .mock(),
        contractAddress: String? = nil,
        tokenId: String = "",
        tokenType: NFTType = .erc721,
        name: String = "",
        description: String? = nil,
        chain: Chain = .bitcoin,
        resource: NFTResource = .mock(),
        images: NFTImages = .mock(),
        attributes: [NFTAttribute] = [],
    ) -> NFTAsset {
        NFTAsset(
            id: id,
            collectionId: collectionId,
            contractAddress: contractAddress,
            tokenId: tokenId,
            tokenType: tokenType,
            name: name,
            description: description,
            chain: chain,
            resource: resource,
            images: images,
            attributes: attributes,
        )
    }
}

public extension NFTAssetData {
    static func mock(
        collection: NFTCollection = .mock(),
        asset: NFTAsset = .mock(),
    ) -> NFTAssetData {
        NFTAssetData(
            collection: collection,
            asset: asset,
        )
    }
}

public extension NFTCollection {
    static func mock(
        id: NFTCollectionId = .mock(),
        name: String = "",
        description: String? = nil,
        chain: Chain = .bitcoin,
        contractAddress: String = "",
        images: NFTImages = .mock(),
        status: VerificationStatus = .verified,
        links: [AssetLink] = [],
    ) -> NFTCollection {
        NFTCollection(
            id: id,
            name: name,
            description: description,
            chain: chain,
            contractAddress: contractAddress,
            images: images,
            status: status,
            links: links,
        )
    }
}

public extension NFTData {
    static func mock(
        collection: NFTCollection = .mock(),
        assets: [NFTAsset] = [],
    ) -> NFTData {
        NFTData(
            collection: collection,
            assets: assets,
        )
    }
}

public extension NFTImages {
    static func mock(
        preview: NFTResource = .mock(),
    ) -> NFTImages {
        NFTImages(
            preview: preview,
        )
    }
}

public extension NFTResource {
    static func mock(
        url: String = "",
        mimeType: String = "",
    ) -> NFTResource {
        NFTResource(
            url: url,
            mimeType: mimeType,
        )
    }
}

public extension NameRecord {
    static func mock(
        name: String = "",
        chain: Chain = .bitcoin,
        address: String = "",
        provider: NameProvider = .ud,
    ) -> NameRecord {
        NameRecord(
            name: name,
            chain: chain,
            address: address,
            provider: provider,
        )
    }
}

public extension Perpetual {
    static func mock(
        id: PerpetualId = .mock(),
        name: String = "",
        provider: PerpetualProvider = .hypercore,
        assetId: AssetId = .mock(),
        identifier: String = "",
        price: Double = 0,
        pricePercentChange24h: Double = 0,
        openInterest: Double = 0,
        volume24h: Double = 0,
        funding: Double = 0,
        maxLeverage: UInt8 = 0,
        isIsolatedOnly: Bool = false,
    ) -> Perpetual {
        Perpetual(
            id: id,
            name: name,
            provider: provider,
            assetId: assetId,
            identifier: identifier,
            price: price,
            pricePercentChange24h: pricePercentChange24h,
            openInterest: openInterest,
            volume24h: volume24h,
            funding: funding,
            maxLeverage: maxLeverage,
            isIsolatedOnly: isIsolatedOnly,
        )
    }
}

public extension PerpetualAccountSummary {
    static func mock(
        accountValue: Double = 0,
        accountLeverage: Double = 0,
        marginUsage: Double = 0,
        unrealizedPnl: Double = 0,
    ) -> PerpetualAccountSummary {
        PerpetualAccountSummary(
            accountValue: accountValue,
            accountLeverage: accountLeverage,
            marginUsage: marginUsage,
            unrealizedPnl: unrealizedPnl,
        )
    }
}

public extension PerpetualData {
    static func mock(
        perpetual: Perpetual = .mock(),
        asset: Asset = .mock(),
        metadata: PerpetualMetadata = .mock(),
    ) -> PerpetualData {
        PerpetualData(
            perpetual: perpetual,
            asset: asset,
            metadata: metadata,
        )
    }
}

public extension PerpetualMetadata {
    static func mock(
        isPinned: Bool = false,
    ) -> PerpetualMetadata {
        PerpetualMetadata(
            isPinned: isPinned,
        )
    }
}

public extension PerpetualPortfolio {
    static func mock(
        day: PerpetualPortfolioTimeframeData? = nil,
        week: PerpetualPortfolioTimeframeData? = nil,
        month: PerpetualPortfolioTimeframeData? = nil,
        allTime: PerpetualPortfolioTimeframeData? = nil,
        accountSummary: PerpetualAccountSummary? = nil,
    ) -> PerpetualPortfolio {
        PerpetualPortfolio(
            day: day,
            week: week,
            month: month,
            allTime: allTime,
            accountSummary: accountSummary,
        )
    }
}

public extension PerpetualPortfolioTimeframeData {
    static func mock(
        accountValueHistory: [ChartDateValue] = [],
        pnlHistory: [ChartDateValue] = [],
        volume: Double = 0,
    ) -> PerpetualPortfolioTimeframeData {
        PerpetualPortfolioTimeframeData(
            accountValueHistory: accountValueHistory,
            pnlHistory: pnlHistory,
            volume: volume,
        )
    }
}

public extension PerpetualPosition {
    static func mock(
        id: String = "",
        perpetualId: PerpetualId = .mock(),
        assetId: AssetId = .mock(),
        size: Double = 0,
        sizeValue: Double = 0,
        leverage: UInt8 = 0,
        entryPrice: Double = 0,
        liquidationPrice: Double? = nil,
        marginType: PerpetualMarginType = .cross,
        direction: PerpetualDirection = .short,
        marginAmount: Double = 0,
        takeProfit: PerpetualTriggerOrder? = nil,
        stopLoss: PerpetualTriggerOrder? = nil,
        pnl: Double = 0,
        funding: Float? = nil,
    ) -> PerpetualPosition {
        PerpetualPosition(
            id: id,
            perpetualId: perpetualId,
            assetId: assetId,
            size: size,
            sizeValue: sizeValue,
            leverage: leverage,
            entryPrice: entryPrice,
            liquidationPrice: liquidationPrice,
            marginType: marginType,
            direction: direction,
            marginAmount: marginAmount,
            takeProfit: takeProfit,
            stopLoss: stopLoss,
            pnl: pnl,
            funding: funding,
        )
    }
}

public extension PerpetualPositionData {
    static func mock(
        perpetual: Perpetual = .mock(),
        asset: Asset = .mock(),
        position: PerpetualPosition = .mock(),
    ) -> PerpetualPositionData {
        PerpetualPositionData(
            perpetual: perpetual,
            asset: asset,
            position: position,
        )
    }
}

public extension Price {
    static func mock(
        price: Double = 0,
        priceChangePercentage24h: Double = 0,
        updatedAt: Date = Date(timeIntervalSince1970: 0),
    ) -> Price {
        Price(
            price: price,
            priceChangePercentage24h: priceChangePercentage24h,
            updatedAt: updatedAt,
        )
    }
}

public extension PriceAlert {
    static func mock(
        assetId: AssetId = .mock(),
        currency: Currency = .mxn,
        price: Double? = nil,
        pricePercentChange: Double? = nil,
        priceDirection: PriceAlertDirection? = nil,
        lastNotifiedAt: Date? = nil,
    ) -> PriceAlert {
        PriceAlert(
            assetId: assetId,
            currency: currency,
            price: price,
            pricePercentChange: pricePercentChange,
            priceDirection: priceDirection,
            lastNotifiedAt: lastNotifiedAt,
        )
    }
}

public extension TotalFiatValue {
    static func mock(
        value: Double = 0,
        pnlAmount: Double = 0,
        pnlPercentage: Double = 0,
    ) -> TotalFiatValue {
        TotalFiatValue(
            value: value,
            pnlAmount: pnlAmount,
            pnlPercentage: pnlPercentage,
        )
    }
}

public extension Transaction {
    static func mock(
        id: TransactionId = .mock(),
        assetId: AssetId = .mock(),
        from: String = "",
        to: String = "",
        contract: String? = nil,
        type: TransactionType = .transfer,
        state: TransactionState = .pending,
        blockNumber: String? = nil,
        sequence: String? = nil,
        fee: String = "0",
        feeAssetId: AssetId = .mock(),
        value: String = "0",
        memo: String? = nil,
        direction: TransactionDirection = .selfTransfer,
        utxoInputs: [TransactionUtxoInput]? = nil,
        utxoOutputs: [TransactionUtxoInput]? = nil,
        metadata: AnyCodableValue? = nil,
        createdAt: Date = Date(timeIntervalSince1970: 0),
    ) -> Transaction {
        Transaction(
            id: id,
            assetId: assetId,
            from: from,
            to: to,
            contract: contract,
            type: type,
            state: state,
            blockNumber: blockNumber,
            sequence: sequence,
            fee: fee,
            feeAssetId: feeAssetId,
            value: value,
            memo: memo,
            direction: direction,
            utxoInputs: utxoInputs,
            utxoOutputs: utxoOutputs,
            metadata: metadata,
            createdAt: createdAt,
        )
    }
}

public extension TransactionExtended {
    static func mock(
        recordId: UInt64 = 0,
        transaction: Transaction = .mock(),
        asset: Asset = .mock(),
        feeAsset: Asset = .mock(),
        price: Price? = nil,
        feePrice: Price? = nil,
        assets: [Asset] = [],
        prices: [AssetPrice] = [],
        fromAddress: AddressName? = nil,
        toAddress: AddressName? = nil,
        confirmationEtaSeconds: UInt32? = nil,
    ) -> TransactionExtended {
        TransactionExtended(
            recordId: recordId,
            transaction: transaction,
            asset: asset,
            feeAsset: feeAsset,
            price: price,
            feePrice: feePrice,
            assets: assets,
            prices: prices,
            fromAddress: fromAddress,
            toAddress: toAddress,
            confirmationEtaSeconds: confirmationEtaSeconds,
        )
    }
}

public extension TransactionListItem {
    static func mock(
        transaction: Transaction = .mock(),
        asset: Asset = .mock(),
        assets: [Asset] = [],
        fromAddress: AddressName? = nil,
        toAddress: AddressName? = nil,
    ) -> TransactionListItem {
        TransactionListItem(
            transaction: transaction,
            asset: asset,
            assets: assets,
            fromAddress: fromAddress,
            toAddress: toAddress,
        )
    }
}

public extension TransactionPerpetualMetadata {
    static func mock(
        pnl: Double = 0,
        price: Double = 0,
        direction: PerpetualDirection = .short,
        isLiquidation: Bool? = nil,
        provider: PerpetualProvider? = nil,
    ) -> TransactionPerpetualMetadata {
        TransactionPerpetualMetadata(
            pnl: pnl,
            price: price,
            direction: direction,
            isLiquidation: isLiquidation,
            provider: provider,
        )
    }
}

public extension TransactionSwapMetadata {
    static func mock(
        fromAsset: AssetId = .mock(),
        fromValue: String = "0",
        toAsset: AssetId = .mock(),
        toValue: String = "0",
        provider: String? = nil,
    ) -> TransactionSwapMetadata {
        TransactionSwapMetadata(
            fromAsset: fromAsset,
            fromValue: fromValue,
            toAsset: toAsset,
            toValue: toValue,
            provider: provider,
        )
    }
}

public extension Wallet {
    static func mock(
        id: WalletId = .mock(),
        externalId: String? = nil,
        name: String = "",
        index: Int32 = 0,
        type: WalletType = .multicoin,
        accounts: [Account] = [],
        isPinned: Bool = false,
        imageUrl: String? = nil,
        source: WalletSource = .create,
    ) -> Wallet {
        Wallet(
            id: id,
            externalId: externalId,
            name: name,
            index: index,
            type: type,
            accounts: accounts,
            isPinned: isPinned,
            imageUrl: imageUrl,
            source: source,
        )
    }
}
