[package]
name = "gem_blockscout"
version = { workspace = true }
edition = { workspace = true }

[features]
testkit = []

[dependencies]
gem_client = { path = "../gem_client" }
serde_serializers = { path = "../serde_serializers", features = ["bigint"] }

num-bigint = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
gem_client = { path = "../gem_client", features = ["testkit"] }
tokio = { workspace = true }
