// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

package com.gemwallet.android.testkit

import com.wallet.core.primitives.Account
import com.wallet.core.primitives.AddressName
import com.wallet.core.primitives.AddressType
import com.wallet.core.primitives.Asset
import com.wallet.core.primitives.AssetAssociation
import com.wallet.core.primitives.AssetBasic
import com.wallet.core.primitives.AssetFull
import com.wallet.core.primitives.AssetId
import com.wallet.core.primitives.AssetLink
import com.wallet.core.primitives.AssetMarket
import com.wallet.core.primitives.AssetMetaData
import com.wallet.core.primitives.AssetPrice
import com.wallet.core.primitives.AssetProperties
import com.wallet.core.primitives.AssetScore
import com.wallet.core.primitives.AssetType
import com.wallet.core.primitives.Chain
import com.wallet.core.primitives.ChartCandleStick
import com.wallet.core.primitives.ChartDateValue
import com.wallet.core.primitives.ChartValuePercentage
import com.wallet.core.primitives.Currency
import com.wallet.core.primitives.JsonValue
import com.wallet.core.primitives.NFTAsset
import com.wallet.core.primitives.NFTAssetData
import com.wallet.core.primitives.NFTAssetId
import com.wallet.core.primitives.NFTAttribute
import com.wallet.core.primitives.NFTCollection
import com.wallet.core.primitives.NFTCollectionId
import com.wallet.core.primitives.NFTData
import com.wallet.core.primitives.NFTImages
import com.wallet.core.primitives.NFTResource
import com.wallet.core.primitives.NFTType
import com.wallet.core.primitives.NameProvider
import com.wallet.core.primitives.NameRecord
import com.wallet.core.primitives.Perpetual
import com.wallet.core.primitives.PerpetualAccountSummary
import com.wallet.core.primitives.PerpetualBasic
import com.wallet.core.primitives.PerpetualData
import com.wallet.core.primitives.PerpetualDirection
import com.wallet.core.primitives.PerpetualId
import com.wallet.core.primitives.PerpetualMarginType
import com.wallet.core.primitives.PerpetualMetadata
import com.wallet.core.primitives.PerpetualPortfolio
import com.wallet.core.primitives.PerpetualPortfolioTimeframeData
import com.wallet.core.primitives.PerpetualPosition
import com.wallet.core.primitives.PerpetualPositionData
import com.wallet.core.primitives.PerpetualProvider
import com.wallet.core.primitives.PerpetualTriggerOrder
import com.wallet.core.primitives.Price
import com.wallet.core.primitives.PriceAlert
import com.wallet.core.primitives.PriceAlertDirection
import com.wallet.core.primitives.SerializedDate
import com.wallet.core.primitives.TotalFiatValue
import com.wallet.core.primitives.Transaction
import com.wallet.core.primitives.TransactionDirection
import com.wallet.core.primitives.TransactionExtended
import com.wallet.core.primitives.TransactionId
import com.wallet.core.primitives.TransactionListItem
import com.wallet.core.primitives.TransactionPerpetualMetadata
import com.wallet.core.primitives.TransactionState
import com.wallet.core.primitives.TransactionSwapMetadata
import com.wallet.core.primitives.TransactionType
import com.wallet.core.primitives.TransactionUtxoInput
import com.wallet.core.primitives.VerificationStatus
import com.wallet.core.primitives.Wallet
import com.wallet.core.primitives.WalletId
import com.wallet.core.primitives.WalletSource
import com.wallet.core.primitives.WalletType

fun mockAccount(
    chain: Chain = Chain.Bitcoin,
    address: String = "",
    derivationPath: String = "",
    extendedPublicKey: String? = null,
) = Account(
    chain = chain,
    address = address,
    derivationPath = derivationPath,
    extendedPublicKey = extendedPublicKey,
)

fun mockAddressName(
    chain: Chain = Chain.Bitcoin,
    address: String = "",
    name: String = "",
    type: AddressType = AddressType.Address,
    status: VerificationStatus = VerificationStatus.Verified,
    imageUrl: String? = null,
) = AddressName(
    chain = chain,
    address = address,
    name = name,
    type = type,
    status = status,
    imageUrl = imageUrl,
)

fun mockAsset(
    id: AssetId = mockAssetId(),
    name: String = "",
    symbol: String = "",
    decimals: Int = 0,
    type: AssetType = AssetType.NATIVE,
) = Asset(
    id = id,
    name = name,
    symbol = symbol,
    decimals = decimals,
    type = type,
)

fun mockAssetBasic(
    asset: Asset = mockAsset(),
    properties: AssetProperties = mockAssetProperties(),
    score: AssetScore = mockAssetScore(),
    price: Price? = null,
) = AssetBasic(
    asset = asset,
    properties = properties,
    score = score,
    price = price,
)

fun mockAssetFull(
    asset: Asset = mockAsset(),
    properties: AssetProperties = mockAssetProperties(),
    score: AssetScore = mockAssetScore(),
    tags: List<String> = emptyList(),
    links: List<AssetLink> = emptyList(),
    associations: List<AssetAssociation> = emptyList(),
    perpetuals: List<PerpetualBasic> = emptyList(),
    price: Price? = null,
    market: AssetMarket? = null,
) = AssetFull(
    asset = asset,
    properties = properties,
    score = score,
    tags = tags,
    links = links,
    associations = associations,
    perpetuals = perpetuals,
    price = price,
    market = market,
)

fun mockAssetLink(
    name: String = "",
    url: String = "",
) = AssetLink(
    name = name,
    url = url,
)

fun mockAssetMarket(
    marketCap: Double? = null,
    marketCapFdv: Double? = null,
    marketCapRank: Int? = null,
    totalVolume: Double? = null,
    circulatingSupply: Double? = null,
    totalSupply: Double? = null,
    maxSupply: Double? = null,
    allTimeHighValue: ChartValuePercentage? = null,
    allTimeLowValue: ChartValuePercentage? = null,
) = AssetMarket(
    marketCap = marketCap,
    marketCapFdv = marketCapFdv,
    marketCapRank = marketCapRank,
    totalVolume = totalVolume,
    circulatingSupply = circulatingSupply,
    totalSupply = totalSupply,
    maxSupply = maxSupply,
    allTimeHighValue = allTimeHighValue,
    allTimeLowValue = allTimeLowValue,
)

fun mockAssetMetaData(
    isEnabled: Boolean = false,
    isBalanceEnabled: Boolean = false,
    isBuyEnabled: Boolean = false,
    isSellEnabled: Boolean = false,
    isSwapEnabled: Boolean = false,
    isStakeEnabled: Boolean = false,
    isEarnEnabled: Boolean = false,
    isPinned: Boolean = false,
    isActive: Boolean = false,
    stakingApr: Double? = null,
    earnApr: Double? = null,
    rankScore: Int = 0,
) = AssetMetaData(
    isEnabled = isEnabled,
    isBalanceEnabled = isBalanceEnabled,
    isBuyEnabled = isBuyEnabled,
    isSellEnabled = isSellEnabled,
    isSwapEnabled = isSwapEnabled,
    isStakeEnabled = isStakeEnabled,
    isEarnEnabled = isEarnEnabled,
    isPinned = isPinned,
    isActive = isActive,
    stakingApr = stakingApr,
    earnApr = earnApr,
    rankScore = rankScore,
)

fun mockAssetPrice(
    assetId: AssetId = mockAssetId(),
    price: Double = 0.0,
    priceChangePercentage24h: Double = 0.0,
    updatedAt: SerializedDate = 0L,
) = AssetPrice(
    assetId = assetId,
    price = price,
    priceChangePercentage24h = priceChangePercentage24h,
    updatedAt = updatedAt,
)

fun mockAssetProperties(
    isEnabled: Boolean = false,
    isBuyable: Boolean = false,
    isSellable: Boolean = false,
    isSwapable: Boolean = false,
    isStakeable: Boolean = false,
    stakingApr: Double? = null,
    isEarnable: Boolean = false,
    earnApr: Double? = null,
    hasImage: Boolean = false,
) = AssetProperties(
    isEnabled = isEnabled,
    isBuyable = isBuyable,
    isSellable = isSellable,
    isSwapable = isSwapable,
    isStakeable = isStakeable,
    stakingApr = stakingApr,
    isEarnable = isEarnable,
    earnApr = earnApr,
    hasImage = hasImage,
)

fun mockAssetScore(
    rank: Int = 0,
) = AssetScore(
    rank = rank,
)

fun mockChartCandleStick(
    date: SerializedDate = 0L,
    open: Double = 0.0,
    high: Double = 0.0,
    low: Double = 0.0,
    close: Double = 0.0,
    volume: Double = 0.0,
) = ChartCandleStick(
    date = date,
    open = open,
    high = high,
    low = low,
    close = close,
    volume = volume,
)

fun mockChartDateValue(
    date: SerializedDate = 0L,
    value: Double = 0.0,
) = ChartDateValue(
    date = date,
    value = value,
)

fun mockNftAsset(
    id: NFTAssetId = mockNftAssetId(),
    collectionId: NFTCollectionId = mockNftCollectionId(),
    contractAddress: String? = null,
    tokenId: String = "",
    tokenType: NFTType = NFTType.ERC721,
    name: String = "",
    description: String? = null,
    chain: Chain = Chain.Bitcoin,
    resource: NFTResource = mockNftResource(),
    images: NFTImages = mockNftImages(),
    attributes: List<NFTAttribute> = emptyList(),
) = NFTAsset(
    id = id,
    collectionId = collectionId,
    contractAddress = contractAddress,
    tokenId = tokenId,
    tokenType = tokenType,
    name = name,
    description = description,
    chain = chain,
    resource = resource,
    images = images,
    attributes = attributes,
)

fun mockNftAssetData(
    collection: NFTCollection = mockNftCollection(),
    asset: NFTAsset = mockNftAsset(),
) = NFTAssetData(
    collection = collection,
    asset = asset,
)

fun mockNftCollection(
    id: NFTCollectionId = mockNftCollectionId(),
    name: String = "",
    description: String? = null,
    chain: Chain = Chain.Bitcoin,
    contractAddress: String = "",
    images: NFTImages = mockNftImages(),
    status: VerificationStatus = VerificationStatus.Verified,
    links: List<AssetLink> = emptyList(),
) = NFTCollection(
    id = id,
    name = name,
    description = description,
    chain = chain,
    contractAddress = contractAddress,
    images = images,
    status = status,
    links = links,
)

fun mockNftData(
    collection: NFTCollection = mockNftCollection(),
    assets: List<NFTAsset> = emptyList(),
) = NFTData(
    collection = collection,
    assets = assets,
)

fun mockNftImages(
    preview: NFTResource = mockNftResource(),
) = NFTImages(
    preview = preview,
)

fun mockNftResource(
    url: String = "",
    mimeType: String = "",
) = NFTResource(
    url = url,
    mimeType = mimeType,
)

fun mockNameRecord(
    name: String = "",
    chain: Chain = Chain.Bitcoin,
    address: String = "",
    provider: NameProvider = NameProvider.Ud,
) = NameRecord(
    name = name,
    chain = chain,
    address = address,
    provider = provider,
)

fun mockPerpetual(
    id: PerpetualId = mockPerpetualId(),
    name: String = "",
    provider: PerpetualProvider = PerpetualProvider.Hypercore,
    assetId: AssetId = mockAssetId(),
    identifier: String = "",
    price: Double = 0.0,
    pricePercentChange24h: Double = 0.0,
    openInterest: Double = 0.0,
    volume24h: Double = 0.0,
    funding: Double = 0.0,
    maxLeverage: UByte = 0u,
    isIsolatedOnly: Boolean = false,
) = Perpetual(
    id = id,
    name = name,
    provider = provider,
    assetId = assetId,
    identifier = identifier,
    price = price,
    pricePercentChange24h = pricePercentChange24h,
    openInterest = openInterest,
    volume24h = volume24h,
    funding = funding,
    maxLeverage = maxLeverage,
    isIsolatedOnly = isIsolatedOnly,
)

fun mockPerpetualAccountSummary(
    accountValue: Double = 0.0,
    accountLeverage: Double = 0.0,
    marginUsage: Double = 0.0,
    unrealizedPnl: Double = 0.0,
) = PerpetualAccountSummary(
    accountValue = accountValue,
    accountLeverage = accountLeverage,
    marginUsage = marginUsage,
    unrealizedPnl = unrealizedPnl,
)

fun mockPerpetualData(
    perpetual: Perpetual = mockPerpetual(),
    asset: Asset = mockAsset(),
    metadata: PerpetualMetadata = mockPerpetualMetadata(),
) = PerpetualData(
    perpetual = perpetual,
    asset = asset,
    metadata = metadata,
)

fun mockPerpetualMetadata(
    isPinned: Boolean = false,
) = PerpetualMetadata(
    isPinned = isPinned,
)

fun mockPerpetualPortfolio(
    day: PerpetualPortfolioTimeframeData? = null,
    week: PerpetualPortfolioTimeframeData? = null,
    month: PerpetualPortfolioTimeframeData? = null,
    allTime: PerpetualPortfolioTimeframeData? = null,
    accountSummary: PerpetualAccountSummary? = null,
) = PerpetualPortfolio(
    day = day,
    week = week,
    month = month,
    allTime = allTime,
    accountSummary = accountSummary,
)

fun mockPerpetualPortfolioTimeframeData(
    accountValueHistory: List<ChartDateValue> = emptyList(),
    pnlHistory: List<ChartDateValue> = emptyList(),
    volume: Double = 0.0,
) = PerpetualPortfolioTimeframeData(
    accountValueHistory = accountValueHistory,
    pnlHistory = pnlHistory,
    volume = volume,
)

fun mockPerpetualPosition(
    id: String = "",
    perpetualId: PerpetualId = mockPerpetualId(),
    assetId: AssetId = mockAssetId(),
    size: Double = 0.0,
    sizeValue: Double = 0.0,
    leverage: UByte = 0u,
    entryPrice: Double = 0.0,
    liquidationPrice: Double? = null,
    marginType: PerpetualMarginType = PerpetualMarginType.Cross,
    direction: PerpetualDirection = PerpetualDirection.Short,
    marginAmount: Double = 0.0,
    takeProfit: PerpetualTriggerOrder? = null,
    stopLoss: PerpetualTriggerOrder? = null,
    pnl: Double = 0.0,
    funding: Float? = null,
) = PerpetualPosition(
    id = id,
    perpetualId = perpetualId,
    assetId = assetId,
    size = size,
    sizeValue = sizeValue,
    leverage = leverage,
    entryPrice = entryPrice,
    liquidationPrice = liquidationPrice,
    marginType = marginType,
    direction = direction,
    marginAmount = marginAmount,
    takeProfit = takeProfit,
    stopLoss = stopLoss,
    pnl = pnl,
    funding = funding,
)

fun mockPerpetualPositionData(
    perpetual: Perpetual = mockPerpetual(),
    asset: Asset = mockAsset(),
    position: PerpetualPosition = mockPerpetualPosition(),
) = PerpetualPositionData(
    perpetual = perpetual,
    asset = asset,
    position = position,
)

fun mockPrice(
    price: Double = 0.0,
    priceChangePercentage24h: Double = 0.0,
    updatedAt: SerializedDate = 0L,
) = Price(
    price = price,
    priceChangePercentage24h = priceChangePercentage24h,
    updatedAt = updatedAt,
)

fun mockPriceAlert(
    assetId: AssetId = mockAssetId(),
    currency: Currency = Currency.MXN,
    price: Double? = null,
    pricePercentChange: Double? = null,
    priceDirection: PriceAlertDirection? = null,
    lastNotifiedAt: SerializedDate? = null,
) = PriceAlert(
    assetId = assetId,
    currency = currency,
    price = price,
    pricePercentChange = pricePercentChange,
    priceDirection = priceDirection,
    lastNotifiedAt = lastNotifiedAt,
)

fun mockTotalFiatValue(
    value: Double = 0.0,
    pnlAmount: Double = 0.0,
    pnlPercentage: Double = 0.0,
) = TotalFiatValue(
    value = value,
    pnlAmount = pnlAmount,
    pnlPercentage = pnlPercentage,
)

fun mockTransaction(
    id: TransactionId = mockTransactionId(),
    assetId: AssetId = mockAssetId(),
    from: String = "",
    to: String = "",
    contract: String? = null,
    type: TransactionType = TransactionType.Transfer,
    state: TransactionState = TransactionState.Pending,
    blockNumber: String? = null,
    sequence: String? = null,
    fee: String = "0",
    feeAssetId: AssetId = mockAssetId(),
    value: String = "0",
    memo: String? = null,
    direction: TransactionDirection = TransactionDirection.SelfTransfer,
    utxoInputs: List<TransactionUtxoInput>? = null,
    utxoOutputs: List<TransactionUtxoInput>? = null,
    metadata: JsonValue? = null,
    createdAt: SerializedDate = 0L,
) = Transaction(
    id = id,
    assetId = assetId,
    from = from,
    to = to,
    contract = contract,
    type = type,
    state = state,
    blockNumber = blockNumber,
    sequence = sequence,
    fee = fee,
    feeAssetId = feeAssetId,
    value = value,
    memo = memo,
    direction = direction,
    utxoInputs = utxoInputs,
    utxoOutputs = utxoOutputs,
    metadata = metadata,
    createdAt = createdAt,
)

fun mockTransactionExtended(
    recordId: Long = 0,
    transaction: Transaction = mockTransaction(),
    asset: Asset = mockAsset(),
    feeAsset: Asset = mockAsset(),
    price: Price? = null,
    feePrice: Price? = null,
    assets: List<Asset> = emptyList(),
    prices: List<AssetPrice> = emptyList(),
    fromAddress: AddressName? = null,
    toAddress: AddressName? = null,
    confirmationEtaSeconds: UInt? = null,
) = TransactionExtended(
    recordId = recordId,
    transaction = transaction,
    asset = asset,
    feeAsset = feeAsset,
    price = price,
    feePrice = feePrice,
    assets = assets,
    prices = prices,
    fromAddress = fromAddress,
    toAddress = toAddress,
    confirmationEtaSeconds = confirmationEtaSeconds,
)

fun mockTransactionListItem(
    transaction: Transaction = mockTransaction(),
    asset: Asset = mockAsset(),
    assets: List<Asset> = emptyList(),
    fromAddress: AddressName? = null,
    toAddress: AddressName? = null,
) = TransactionListItem(
    transaction = transaction,
    asset = asset,
    assets = assets,
    fromAddress = fromAddress,
    toAddress = toAddress,
)

fun mockTransactionPerpetualMetadata(
    pnl: Double = 0.0,
    price: Double = 0.0,
    direction: PerpetualDirection = PerpetualDirection.Short,
    isLiquidation: Boolean? = null,
    provider: PerpetualProvider? = null,
) = TransactionPerpetualMetadata(
    pnl = pnl,
    price = price,
    direction = direction,
    isLiquidation = isLiquidation,
    provider = provider,
)

fun mockTransactionSwapMetadata(
    fromAsset: AssetId = mockAssetId(),
    fromValue: String = "0",
    toAsset: AssetId = mockAssetId(),
    toValue: String = "0",
    provider: String? = null,
) = TransactionSwapMetadata(
    fromAsset = fromAsset,
    fromValue = fromValue,
    toAsset = toAsset,
    toValue = toValue,
    provider = provider,
)

fun mockWallet(
    id: WalletId = mockWalletId(),
    externalId: String? = null,
    name: String = "",
    index: Int = 0,
    type: WalletType = WalletType.Multicoin,
    accounts: List<Account> = emptyList(),
    isPinned: Boolean = false,
    imageUrl: String? = null,
    source: WalletSource = WalletSource.Create,
) = Wallet(
    id = id,
    externalId = externalId,
    name = name,
    index = index,
    type = type,
    accounts = accounts,
    isPinned = isPinned,
    imageUrl = imageUrl,
    source = source,
)
