// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

package com.gemwallet.android.testkit

import com.wallet.core.primitives.AddressName
import com.wallet.core.primitives.AddressType
import com.wallet.core.primitives.Asset
import com.wallet.core.primitives.AssetId
import com.wallet.core.primitives.AssetLink
import com.wallet.core.primitives.AssetScore
import com.wallet.core.primitives.AssetType
import com.wallet.core.primitives.Chain
import com.wallet.core.primitives.Currency
import com.wallet.core.primitives.NFTAsset
import com.wallet.core.primitives.NFTAssetData
import com.wallet.core.primitives.NFTAssetId
import com.wallet.core.primitives.NFTAttribute
import com.wallet.core.primitives.NFTCollection
import com.wallet.core.primitives.NFTCollectionId
import com.wallet.core.primitives.NFTData
import com.wallet.core.primitives.NFTImages
import com.wallet.core.primitives.NFTResource
import com.wallet.core.primitives.NFTType
import com.wallet.core.primitives.NameProvider
import com.wallet.core.primitives.NameRecord
import com.wallet.core.primitives.PriceAlert
import com.wallet.core.primitives.PriceAlertDirection
import com.wallet.core.primitives.SerializedDate
import com.wallet.core.primitives.TotalFiatValue
import com.wallet.core.primitives.VerificationStatus

fun mockAddressName(
    chain: Chain = Chain.Bitcoin,
    address: String = "",
    name: String = "",
    type: AddressType = AddressType.Address,
    status: VerificationStatus = VerificationStatus.Verified,
    imageUrl: String? = null,
) = AddressName(
    chain = chain,
    address = address,
    name = name,
    type = type,
    status = status,
    imageUrl = imageUrl,
)

fun mockAsset(
    id: AssetId = mockAssetId(),
    name: String = "",
    symbol: String = "",
    decimals: Int = 0,
    type: AssetType = AssetType.NATIVE,
) = Asset(
    id = id,
    name = name,
    symbol = symbol,
    decimals = decimals,
    type = type,
)

fun mockAssetScore(
    rank: Int = 0,
) = AssetScore(
    rank = rank,
)

fun mockNftAsset(
    id: NFTAssetId = mockNftAssetId(),
    collectionId: NFTCollectionId = mockNftCollectionId(),
    contractAddress: String? = null,
    tokenId: String = "",
    tokenType: NFTType = NFTType.ERC721,
    name: String = "",
    description: String? = null,
    chain: Chain = Chain.Bitcoin,
    resource: NFTResource = mockNftResource(),
    images: NFTImages = mockNftImages(),
    attributes: List<NFTAttribute> = emptyList(),
) = NFTAsset(
    id = id,
    collectionId = collectionId,
    contractAddress = contractAddress,
    tokenId = tokenId,
    tokenType = tokenType,
    name = name,
    description = description,
    chain = chain,
    resource = resource,
    images = images,
    attributes = attributes,
)

fun mockNftAssetData(
    collection: NFTCollection = mockNftCollection(),
    asset: NFTAsset = mockNftAsset(),
) = NFTAssetData(
    collection = collection,
    asset = asset,
)

fun mockNftCollection(
    id: NFTCollectionId = mockNftCollectionId(),
    name: String = "",
    description: String? = null,
    chain: Chain = Chain.Bitcoin,
    contractAddress: String = "",
    images: NFTImages = mockNftImages(),
    status: VerificationStatus = VerificationStatus.Verified,
    links: List<AssetLink> = emptyList(),
) = NFTCollection(
    id = id,
    name = name,
    description = description,
    chain = chain,
    contractAddress = contractAddress,
    images = images,
    status = status,
    links = links,
)

fun mockNftData(
    collection: NFTCollection = mockNftCollection(),
    assets: List<NFTAsset> = emptyList(),
) = NFTData(
    collection = collection,
    assets = assets,
)

fun mockNftImages(
    preview: NFTResource = mockNftResource(),
) = NFTImages(
    preview = preview,
)

fun mockNftResource(
    url: String = "",
    mimeType: String = "",
) = NFTResource(
    url = url,
    mimeType = mimeType,
)

fun mockNameRecord(
    name: String = "",
    chain: Chain = Chain.Bitcoin,
    address: String = "",
    provider: NameProvider = NameProvider.Ud,
) = NameRecord(
    name = name,
    chain = chain,
    address = address,
    provider = provider,
)

fun mockPriceAlert(
    assetId: AssetId = mockAssetId(),
    currency: Currency = Currency.MXN,
    price: Double? = null,
    pricePercentChange: Double? = null,
    priceDirection: PriceAlertDirection? = null,
    lastNotifiedAt: SerializedDate? = null,
) = PriceAlert(
    assetId = assetId,
    currency = currency,
    price = price,
    pricePercentChange = pricePercentChange,
    priceDirection = priceDirection,
    lastNotifiedAt = lastNotifiedAt,
)

fun mockTotalFiatValue(
    value: Double = 0.0,
    pnlAmount: Double = 0.0,
    pnlPercentage: Double = 0.0,
) = TotalFiatValue(
    value = value,
    pnlAmount = pnlAmount,
    pnlPercentage = pnlPercentage,
)
