[package]
name = "nft"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
futures.workspace = true
async-trait = { workspace = true }

primitives = { path = "../primitives" }
alchemy = { path = "../alchemy", features = ["nft"] }
blockscout = { path = "../blockscout" }
gem_client = { path = "../gem_client", features = ["reqwest"] }
gem_evm = { path = "../gem_evm" }
gem_ton = { path = "../gem_ton", features = ["rpc"] }
settings = { path = "../settings" }

[dev-dependencies]
tokio = { workspace = true }
blockscout = { path = "../blockscout", features = ["testkit"] }
gem_ton = { path = "../gem_ton", features = ["rpc", "testkit"] }
primitives = { path = "../primitives", features = ["testkit"] }

[features]
nft_integration_tests = ["settings/testkit"]
