[package]
name = "coinmarketcap"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
gem_client = { path = "../gem_client", features = ["reqwest"] }
primitives = { path = "../primitives" }
reqwest = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
gem_client = { path = "../gem_client", features = ["testkit"] }
