[package]
name = "pusher"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
gem_client = { path = "../gem_client", features = ["reqwest"] }
push_notification = { path = "../push_notification" }

[dev-dependencies]
primitives = { path = "../primitives", features = ["testkit"] }
