[package]
name = "pricer"
edition = { workspace = true }
version = { workspace = true }

[features]
testkit = []

[dependencies]
serde_json = { workspace = true }
chrono = { workspace = true }

config_keys = { path = "../config_keys" }
primitives = { path = "../primitives" }
push_notification = { path = "../push_notification" }
prices = { path = "../prices" }
number_formatter = { path = "../number_formatter" }
storage = { path = "../storage" }
localizer = { path = "../../crates/localizer" }
cacher = { path = "../../crates/cacher" }
gem_tracing = { path = "../tracing" }

[dev-dependencies]
primitives = { path = "../primitives", features = ["testkit"] }
