// Generated by `just generate-models`. Do not edit.
// Declared in gemstone/src/models/json_bridge.rs.

package com.gemwallet.android.serializer

import kotlinx.serialization.encodeToString
import com.wallet.core.primitives.StreamEvent
import com.wallet.core.primitives.StreamMessage

fun StreamEvent.toJson(): String = jsonEncoder.encodeToString<StreamEvent>(this)

fun StreamMessage.toJson(): String = jsonEncoder.encodeToString<StreamMessage>(this)
