// Generated by `just generate-models`. Do not edit.
// Declared in gemstone/src/models/json_bridge.rs.

package com.gemwallet.android.serializer

import kotlinx.serialization.encodeToString
import com.wallet.core.primitives.Payment
import com.wallet.core.primitives.PaymentAmount
import com.wallet.core.primitives.PaymentLink
import com.wallet.core.primitives.PerpetualModifyPositionType
import com.wallet.core.primitives.PerpetualType
import com.wallet.core.primitives.SolanaNftStandard
import com.wallet.core.primitives.StreamEvent
import com.wallet.core.primitives.StreamMessage
import com.wallet.core.primitives.TronStakeData

fun Payment.toJson(): String = jsonEncoder.encodeToString<Payment>(this)

fun PaymentAmount.toJson(): String = jsonEncoder.encodeToString<PaymentAmount>(this)

fun PaymentLink.toJson(): String = jsonEncoder.encodeToString<PaymentLink>(this)

fun PerpetualModifyPositionType.toJson(): String = jsonEncoder.encodeToString<PerpetualModifyPositionType>(this)

fun PerpetualType.toJson(): String = jsonEncoder.encodeToString<PerpetualType>(this)

fun SolanaNftStandard.toJson(): String = jsonEncoder.encodeToString<SolanaNftStandard>(this)

fun StreamEvent.toJson(): String = jsonEncoder.encodeToString<StreamEvent>(this)

fun StreamMessage.toJson(): String = jsonEncoder.encodeToString<StreamMessage>(this)

fun TronStakeData.toJson(): String = jsonEncoder.encodeToString<TronStakeData>(this)
