list:
    just --list

bootstrap: install-rust install-toolchains install-ndk

install-rust:
    @echo Install Rust
    @cd ../core && just install-rust

install-toolchains:
    @echo Install toolchains for uniffi
    @cd ../core && just gemstone install-android-targets

install-typeshare:
    @echo "==> Install typeshare-cli"
    @cd ../core && just install-typeshare

install-ndk:
    @cd ../core && just gemstone install-ndk

clean:
    @./gradlew clean

build:
    @./gradlew assembleGoogleDebug

build-test:
    @./gradlew assembleGoogleDebugAndroidTest

test:
    @./gradlew testGoogleDebugUnitTest

test-integration:
    @./gradlew connectedGoogleDebugAndroidTest

lint:
    @./gradlew lint -x :gemstone:lintDebug

provision-emulator:
    @bash ./scripts/android_emulator.sh provision

start-emulator:
    @bash ./scripts/android_emulator.sh setup

stop-emulator:
    @bash ./scripts/android_emulator.sh shutdown

mobsfscan:
    @command -v uv >/dev/null || { \
        echo "uv is not installed. Install it via 'curl -LsSf https://astral.sh/uv/install.sh | sh'."; \
        exit 1; }
    uv tool run mobsfscan -- --type android --config .mobsf --exit-warning

release:
    @./gradlew clean :app:bundleGoogleRelease assembleUniversalRelease assembleHuaweiRelease assembleSolanaRelease assembleSamsungRelease --no-configuration-cache

localize:
    @sh ../core/scripts/localize.sh android ui/src/main/res

generate: generate-models

generate-models: install-typeshare
    @echo "==> Generate typeshare for Android"
    @cd ../core && cargo run --package generate --bin generate android ../android/gemcore/src/main/kotlin/com/wallet/core

bump TARGET="patch":
	@cd .. && just bump {{TARGET}}
