[package]
name = "jupiter"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
gem_client = { path = "../gem_client", features = ["reqwest"] }
reqwest = { workspace = true }

[dev-dependencies]
gem_client = { path = "../gem_client", features = ["testkit"] }
tokio = { workspace = true }
async-trait = { workspace = true }
