[package]
name = "gem_optimism"
version = { workspace = true }
edition = { workspace = true }

[features]
default = []
rpc = ["gem_evm/rpc", "dep:async-trait", "dep:gem_client", "dep:alloy-sol-types"]

[dependencies]
primitives = { path = "../primitives" }
gem_evm = { path = "../gem_evm" }

gem_client = { path = "../gem_client", optional = true }
async-trait = { workspace = true, optional = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true, optional = true }
num-bigint = { workspace = true }

[dev-dependencies]
primitives = { path = "../primitives", features = ["testkit"] }
