// lib.rs

pub type UInt64 = u64;

mod access_token_cacher;
pub use self::access_token_cacher::{AccessTokenCacher, AccessTokenFuture};

#[macro_use]
pub mod string_serde;

mod async_result;
pub use self::async_result::try_in_order;

pub mod localize;
pub use self::localize::Localize;

pub mod auth;
pub use self::auth::{AuthMessage, AuthNonce, AuthPayload, AuthenticatedRequest};
pub mod app_constants;
pub use self::app_constants::{GEM_ANDROID_PACKAGE_ID, GEM_API_HOST, GEM_IOS_BUNDLE_ID, GEM_NODES_ASIA_HOST, GEM_NODES_EUROPE_HOST, GEM_NODES_HOST};
pub mod auth_status;
pub use self::auth_status::AuthStatus;
pub mod chain;
pub use self::chain::Chain;
pub mod chain_request;
pub use self::chain_request::{ChainRequest, ChainRequestProtocol, ChainRequestType};
pub mod chain_config;
pub mod chain_stake;
pub use self::chain_stake::StakeChain;
pub mod chain_nft;
pub use self::chain_nft::NFTChain;
pub mod chain_type;
pub use self::chain_type::ChainType;
pub mod chain_transaction_timeout;
pub use self::chain_transaction_timeout::{chain_transaction_timeout, swap_transaction_timeout};
pub mod chain_evm;
pub use self::chain_evm::EVMChain;
pub mod chain_bitcoin;
pub use self::chain_bitcoin::{BITCOINCASH_PREFIX, BitcoinChain};
pub mod name;
pub use self::name::NameProvider;
pub mod node;
pub use self::node::Node;
pub mod node_check;
pub use self::node_check::{NodeCheckProfile, NodeCheckReport, NodeCheckRequest, NodeCheckResult, NodeCheckStatus, node_check_request};
pub mod node_status;
pub use self::node_status::NodeStatus;
pub mod node_sync_status;
pub use self::node_sync_status::{NodeStatusState, NodeSyncStatus};
pub mod latency_type;
pub use self::latency_type::{Latency, LatencyType};
pub mod service_status;
pub use self::service_status::ServiceStatusState;
pub mod price;
pub use self::price::Price;
pub mod price_change;
pub use self::price_change::PriceChangeCalculator;
pub mod price_config;
pub use self::price_config::PriceConfig;
pub mod price_data;
pub use self::price_data::PriceData;
pub mod price_provider;
pub use self::price_provider::PriceProvider;
pub mod price_id;
mod provider_scoped_id;
pub use self::price_id::PriceId;
pub mod asset;
pub mod asset_association;
pub use self::asset_association::{AssetAssociation, AssetAssociationType};
pub mod config;
pub use self::config::{ConfigResponse, ConfigVersions, Release, SwapConfig};
pub mod config_key;
pub use self::config_key::ConfigKey;
pub mod config_param_key;
pub use self::config_param_key::{ConfigParamKey, RateLimit, RateLimitKey, RateLimitWindow};
pub mod duration;
pub use self::duration::{DAY, HOUR, MINUTE, MONTH, SECONDS_PER_DAY, SECONDS_PER_HOUR, SECONDS_PER_MINUTE, SECONDS_PER_WEEK, WEEK, parse_duration};
pub mod currency;
pub use self::asset::{Asset, AssetVecExt, ChainAsset};
pub use self::currency::Currency;
pub mod asset_id;
pub use self::asset_id::{AssetId, AssetIdVecExt, CHAIN_SEPARATOR, TOKEN_ID_SEPARATOR};
pub use crate::asset::AssetHashSetExt;
pub mod asset_score;
pub use self::asset_score::AssetScore;
pub mod asset_type;
pub use self::asset_type::{AssetSubtype, AssetType};
pub mod asset_price;
pub use self::asset_price::{AssetMarket, AssetPrice, AssetPrices, AssetPricesRequest, ChartPeriod, ChartTimeframe, ChartValue, Charts};
pub mod asset_fiat_value;
pub use self::asset_fiat_value::AssetFiatValue;
pub mod total_fiat_value;
pub use self::total_fiat_value::TotalFiatValue;
pub mod balance_calculator;
pub use self::balance_calculator::BalanceCalculator;
pub mod banner;
pub use self::banner::{Banner, BannerEvent, BannerState};
pub mod total_value_type;
pub use self::total_value_type::TotalValueType;
pub mod asset_price_info;
pub use self::asset_price_info::AssetPriceInfo;
pub mod asset_details;
pub use self::asset_details::{AssetBasic, AssetFull, AssetLink, AssetMarketPrice, AssetPriceMetadata, AssetProperties};
pub mod appearance;
pub mod asset_constants;
pub use self::appearance::Appearance;
pub mod contract_constants;
pub mod fiat_assets;
pub mod fiat_quote;
pub mod known_assets;
pub use self::fiat_quote::{FiatAssetSymbol, FiatQuote, FiatQuoteError, FiatQuoteResponse, FiatQuoteUrl, FiatQuoteUrlData, FiatQuotes};
pub mod fiat_transaction;
pub use self::fiat_assets::FiatAsset;
pub use self::fiat_assets::FiatAssets;
pub use self::fiat_transaction::{FiatQuoteType, FiatTransaction, FiatTransactionAssetData, FiatTransactionData, FiatTransactionStatus, FiatTransactionUpdate};
pub mod fiat_provider;
pub use self::fiat_provider::{FiatProvider, FiatProviderCountry, FiatProviderName};
pub mod fiat_quote_request;
pub use self::fiat_quote_request::FiatQuoteRequest;
pub mod fiat_rate;
pub use self::fiat_rate::FiatRate;
pub mod fiat_provider_id;
pub use self::fiat_provider_id::FiatProviderId;
pub mod platform;
pub use self::platform::Platform;
pub mod platform_store;
pub use self::platform_store::PlatformStore;
pub mod payment;
pub use self::payment::{Payment, PaymentAmount, PaymentLink, PaymentRequest};
pub mod payment_type;
pub use self::payment_type::PaymentType;
pub mod contact;
pub use self::contact::Contact;
pub mod device;
pub use self::device::Device;
pub mod device_locale;
pub use self::device_locale::DeviceLocale;
pub mod device_token;
pub use self::device_token::DeviceToken;
pub mod defi;
pub use self::defi::{DefiPosition, DefiPositionAsset, DefiPositionMetadata, DefiPositionType, DefiProtocol, DefiProvider};
pub mod pagination;
pub use self::pagination::{MAX_QUERY_LIMIT, MAX_QUERY_PAGES};
pub mod transaction;
pub use self::transaction::{Transaction, TransactionsResponse};
pub mod transaction_type;
pub use self::transaction_type::TransactionType;
pub mod transaction_extended;
pub use self::transaction_extended::TransactionExtended;
pub mod tag_visibility;
pub use self::tag_visibility::TagVisibility;
pub mod time;
pub use self::time::{unix_milliseconds, unix_seconds, unix_timestamp};
pub mod transaction_state;
pub use self::transaction_state::TransactionState;
pub mod job_configuration;
pub use self::job_configuration::JobConfiguration;
pub mod username_status;
pub use self::username_status::UsernameStatus;
pub mod qr_scan_type;
pub use self::qr_scan_type::QRScanType;
pub mod scan_receive_mode;
pub use self::scan_receive_mode::ScanReceiveMode;
pub mod recent_activity_type;
pub use self::recent_activity_type::RecentActivityType;
pub mod transaction_direction;
pub use self::transaction_direction::TransactionDirection;
pub mod subscription;
pub mod transaction_utxo;
pub use self::subscription::{AddressChains, DeviceSubscription, WalletSubscription, WalletSubscriptionChains};
pub use self::transaction_utxo::TransactionUtxoInput;
pub mod address;
pub use self::address::{Address, AddressError};
pub mod address_formatter;
pub use self::address_formatter::{AddressFormatStyle, AddressFormatter};
pub mod address_name;
pub use self::address_name::AddressName;
pub mod verification_status;
pub use self::verification_status::VerificationStatus;
pub mod address_status;
pub use self::address_status::AddressStatus;
pub mod wallet_configuration;
pub use self::wallet_configuration::{WalletConfiguration, WalletConfigurationResult};
pub mod utxo;
pub use self::utxo::UTXO;
pub mod push_notification;
pub use self::push_notification::{
    PushNotification, PushNotificationAsset, PushNotificationReward, PushNotificationSupport, PushNotificationSwapAsset, PushNotificationTransaction, PushNotificationTypes,
    PushNotificationWalletAsset,
};
pub mod gorush;
pub use self::gorush::{FailedNotification, GorushNotification, GorushNotifications, PushErrorLog};
pub mod admin;
pub use self::admin::{AdminDevice, AdminWalletOverview};
pub mod scan;
pub use self::scan::{AddressType, ScanAddress, ScanAddressTarget, ScanTransaction, ScanTransactionPayload};
pub mod hex;
pub use self::hex::{HexError, decode_hex, decode_hex_array};
pub mod transaction_metadata_types;
pub use self::transaction_metadata_types::{
    TransactionNFTTransferMetadata, TransactionPerpetualMetadata, TransactionResourceTypeMetadata, TransactionSmartContractMetadata, TransactionSwapMetadata,
    TransactionWalletConnectMetadata,
};
pub mod wallet_connect_namespace;
pub use self::wallet_connect_namespace::WalletConnectCAIP2;
pub mod wallet_connect;
pub use self::wallet_connect::{WCEthereumTransaction, WalletConnectLink, WalletConnectRequest};
pub mod account;
pub use self::account::Account;
pub mod application_metadata;
pub use self::application_metadata::{ApplicationMetadata, ApplicationMetadataSource};
pub mod wallet;
pub use self::wallet::{Wallet, WalletSource};
pub mod wallet_type;
pub use self::wallet_type::WalletType;
pub mod webhook_kind;
pub use self::webhook_kind::WebhookKind;
pub mod image_type;
pub use self::image_type::{ImageType, MIME_TYPE_PNG};
pub mod wallet_id;
pub use self::wallet_id::WalletId;
pub mod wallet_connector;
pub use self::wallet_connector::{
    WCPairingProposal, WalletConnection, WalletConnectionEvents, WalletConnectionMethods, WalletConnectionSession, WalletConnectionSessionProposal, WalletConnectionState,
    WalletConnectionVerificationStatus,
};
pub mod nft;
pub use self::nft::{NFTAsset, NFTAssetData, NFTAssetId, NFTAttribute, NFTAttributeType, NFTCollection, NFTCollectionId, NFTData, NFTImages, NFTResource, NFTType, ReportNft};
pub mod price_alert;
pub use self::price_alert::{DevicePriceAlert, PriceAlert, PriceAlertDirection, PriceAlertNotificationType, PriceAlertType, PriceAlerts};
pub mod rewards;
pub use self::rewards::{ReferralCode, ReferralLeader, ReferralLeaderboard, RewardEvent, RewardEventType, RewardLevel, RewardStatus, Rewards};
pub mod tag;
pub use self::tag::AssetTag;
pub mod chain_cosmos;
pub use self::chain_cosmos::CosmosDenom;
pub mod payment_decoder;
pub use self::payment_decoder::PaymentURLDecoder;

pub mod image_formatter;
pub use self::image_formatter::ImageFormatter;
pub mod block_explorer;
pub mod explorers;
pub mod validator;
pub use self::validator::StakeValidator;
pub mod solana_nft;
pub use self::solana_nft::SolanaNftStandard;
pub mod solana_token_program;
pub use self::solana_token_program::SolanaTokenProgramId;
pub mod solana_types;
pub use self::solana_types::{SolanaAccountMeta, SolanaInstruction};
pub mod fee;
pub mod fee_priority_value;
pub mod gas_price_type;
pub use self::fee::{CustomFee, FeePriority, FeeRate, FeeUnitType, GasPriceType, SOLANA_PRIORITY_FEE_SCALE};
pub use self::fee_priority_value::PriorityFeeValue;
pub mod response;
pub use self::response::{RequestError, ResponseError, ResponseResult};
pub mod link_type;
pub use self::link_type::LinkType;
pub mod markets;
pub use self::markets::{MarketDominance, Markets, MarketsAssets};
pub mod list_provider;
pub use self::list_provider::ListProviderName;
pub mod list_id;
pub use self::list_id::ListId;
pub mod diff;
pub use self::diff::Diff;
pub mod priority;
pub use self::priority::{PrioritizedProvider, sort_by_priority_then_amount};
pub mod swap_provider;
pub use self::swap_provider::SwapProvider;
pub mod swap;
pub mod websocket;
pub use self::websocket::WebSocketPricePayload;
pub mod stream;
pub use self::stream::{StreamBalanceUpdate, StreamEvent, StreamMessage, StreamMessagePrices, StreamTransactionsUpdate, StreamWalletUpdate, device_stream_channel};
pub mod support;
pub use self::support::{
    SupportAction, SupportAgent, SupportMessage, SupportMessageImage, SupportMessageInput, SupportMessageSender, SupportMessageStatus, SupportStreamEvent, SupportTyping,
    SupportTypingStatus,
};
pub mod asset_balance;
pub use self::asset_balance::{AddressBalances, AssetBalance, Balance};
pub mod chain_address;
pub use self::chain_address::ChainAddress;
pub mod json_rpc;
pub use self::json_rpc::JsonRpcResult;
pub mod node_config;
pub mod transaction_id;
pub use self::transaction_id::TransactionId;
mod transaction_id_request;
pub use self::transaction_id_request::TransactionIdRequest;
pub mod asset_address;
pub use self::asset_address::AssetAddress;
pub mod graphql;
pub mod perpetual;
pub use self::perpetual::{
    AccountDataType, CancelOrderData, Perpetual, PerpetualAccountMode, PerpetualBalance, PerpetualBasic, PerpetualConfirmData, PerpetualDirection, PerpetualMarketData,
    PerpetualModifyConfirmData, PerpetualModifyPositionType, PerpetualPositionData, PerpetualPositionsSummary, PerpetualReduceData, PerpetualSearchData, PerpetualType,
    TPSLOrderData,
};
pub mod search;
pub use self::search::{AssetList, SearchResponse};
pub mod perpetual_id;
pub use self::perpetual_id::PerpetualId;
pub mod perpetual_provider;
pub use self::perpetual_provider::PerpetualProvider;
pub mod perpetual_position;
pub use self::perpetual_position::{PerpetualMarginType, PerpetualOrderType, PerpetualPosition, PerpetualTriggerOrder};
pub mod portfolio;
pub use self::portfolio::{
    ChartValuePercentage, PerpetualAccountSummary, PerpetualPortfolio, PerpetualPortfolioTimeframeData, PortfolioAllocation, PortfolioAsset, PortfolioAssets,
    PortfolioAssetsRequest, PortfolioChartData, PortfolioChartType, PortfolioData, PortfolioMarginUsage, PortfolioStatistic, PortfolioType,
};
pub use chrono;
pub mod tpsl_type;
pub use self::tpsl_type::TpslType;
pub mod autoclose_validator;
pub use self::autoclose_validator::{AutocloseEstimator, AutocloseValidation, AutocloseValidator};
pub mod chart;
pub use self::chart::{ChartCandleStick, ChartDateValue};
pub mod delegation;
pub use self::delegation::{Delegation, DelegationBase, DelegationState, DelegationValidator};
pub mod contract_call_data;
pub use self::contract_call_data::ContractCallData;
pub mod stake_type;
pub use self::stake_type::{RedelegateData, Resource, StakeType, TronStakeData, TronUnfreeze, TronVote};
pub mod stake_provider_type;
pub use self::stake_provider_type::StakeProviderType;
pub mod yield_provider;
pub use self::yield_provider::YieldProvider;
pub mod earn_type;
pub use self::earn_type::EarnType;
pub mod transaction_state_request;
pub use self::transaction_state_request::TransactionStateRequest;
pub mod transaction_update;
pub use self::transaction_update::{TransactionChange, TransactionMetadata, TransactionUpdate};
pub mod transaction_preload_input;
pub use self::transaction_preload_input::TransactionPreloadInput;
pub mod transaction_fee;
pub use self::transaction_fee::{FeeOption, TransactionFee};
pub mod transaction_load_metadata;
pub use self::transaction_load_metadata::{HyperliquidOrder, TransactionLoadMetadata};
pub mod transaction_input_type;
pub use self::transaction_input_type::{SignerInput, TransactionInputType, TransactionLoadData, TransactionLoadInput};
pub mod transfer_amount;
pub use self::transfer_amount::{TransferAmount, TransferAmountError, TransferAmountInput};
pub mod transfer_data_extra;
pub use self::transfer_data_extra::TransferDataExtra;
pub mod transaction_data_output;
pub use self::transaction_data_output::{TransferDataOutputAction, TransferDataOutputType};
pub mod broadcast_options;
pub use self::broadcast_options::BroadcastOptions;
pub mod secure_preferences;
pub use self::secure_preferences::{InMemoryPreferences, Preferences, PreferencesExt};

pub mod signer_error;
pub use self::signer_error::SignerError;
pub mod date_ext;
pub use self::date_ext::{DurationExt, NaiveDateTimeExt, now};
pub mod number_incrementer;
pub use self::number_incrementer::NumberIncrementer;
pub mod chain_signer;
pub use self::chain_signer::ChainSigner;
pub mod notification_type;
pub use self::notification_type::NotificationType;
pub mod notification_data;
pub use self::notification_data::{NotificationData, NotificationRewardsMetadata, NotificationRewardsRedeemMetadata};
pub mod deeplink;
pub use self::deeplink::Deeplink;
pub mod url_action;
pub use self::url_action::UrlAction;
pub mod url_scheme;
pub use self::url_scheme::{GEM_URL_SCHEME, HTTP_URL_SCHEME, HTTPS_URL_SCHEME, WALLET_CONNECT_URL_SCHEME};
pub mod list_item;
mod url_query;
pub use self::list_item::{CoreEmoji, CoreListItem, CoreListItemBadge, CoreListItemIcon};
pub mod notification;
pub use self::notification::InAppNotification;
pub mod simulation;
pub use self::simulation::{
    SimulationBalanceChange, SimulationHeader, SimulationInput, SimulationPayloadField, SimulationPayloadFieldDisplay, SimulationPayloadFieldKind, SimulationPayloadFieldType,
    SimulationResult, SimulationSeverity, SimulationWarning, SimulationWarningApproval, SimulationWarningType, promote_single_secondary_payload_field,
};
pub mod ip_usage_type;
pub use self::ip_usage_type::IpUsageType;
pub mod connection_component;
pub use self::connection_component::ConnectionComponent;
pub mod connection_status;
pub use self::connection_status::ConnectionStatus;
pub mod metrics;
pub use self::metrics::{ConsumerStatus, ParserStatus, ReportedError};
pub mod value_access;
pub use self::value_access::{JsonDecode, ValueAccess};

#[cfg(any(test, feature = "testkit"))]
pub mod testkit;
