[package]
name = "daemon"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
tokio = { workspace = true, features = ["signal"] }
rocket = { workspace = true }
futures = { workspace = true }
strum = { workspace = true }
async-trait = { workspace = true }

prometheus-client = { workspace = true }
metrics = { path = "../../crates/metrics" }
gem_tracing = { path = "../../crates/gem_tracing" }
settings = { path = "../../crates/settings" }
prices = { path = "../../crates/prices" }
config_keys = { path = "../../crates/config_keys" }
primitives = { path = "../../crates/primitives" }
job_runner = { path = "../../crates/job_runner" }
services = { path = "../../crates/services" }
streamer = { path = "../../crates/streamer" }
chain_providers = { path = "../../crates/chain_providers" }
chain_traits = { path = "../../crates/chain_traits" }

[dev-dependencies]
num-bigint = { workspace = true }
primitives = { path = "../../crates/primitives", features = ["testkit"] }
