folder: ../../assets/blockchains
delay: 1s
image:
  size: 256
  types:
    - png
    - jpeg
    - jpg
    - svg
  request:
    timeout: 10s
    retries: 2
coingecko:
  top:
    count: 250
coinmarketcap:
  top:
    count: 250
  trending:
    count: 10
jupiter:
  top:
    count: 250
  trending:
    count: 10
    interval: 24h
