// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "Transfer",
    platforms: [
        .iOS(.v17),
        .macOS(.v15),
    ],
    products: [
        .library(
            name: "Transfer",
            targets: ["Transfer"],
        ),
        .library(
            name: "TransferTestKit",
            targets: ["TransferTestKit"],
        ),
    ],
    dependencies: [
        .package(name: "Primitives", path: "../../Packages/Primitives"),
        .package(name: "Gemstone", path: "../../Packages/Gemstone"),
        .package(name: "Formatters", path: "../../Packages/Formatters"),
        .package(name: "Localization", path: "../../Packages/Localization"),
        .package(name: "Style", path: "../../Packages/Style"),
        .package(name: "Components", path: "../../Packages/Components"),
        .package(name: "PrimitivesComponents", path: "../../Packages/PrimitivesComponents"),
        .package(name: "GemstonePrimitives", path: "../../Packages/GemstonePrimitives"),
        .package(name: "Keystore", path: "../../Packages/Keystore"),
        .package(name: "Blockchain", path: "../../Packages/Blockchain"),
        .package(name: "Signer", path: "../../Packages/Signer"),
        .package(name: "Preferences", path: "../../Packages/Preferences"),
        .package(name: "Validators", path: "../../Packages/Validators"),
        .package(name: "Store", path: "../../Packages/Store"),

        .package(name: "Stake", path: "../Stake"),
        .package(name: "WalletConnector", path: "../WalletConnector"),
        .package(name: "InfoSheet", path: "../InfoSheet"),
        .package(name: "Swap", path: "../Swap"),
        .package(name: "Perpetuals", path: "../Perpetuals"),

        .package(name: "ChainServices", path: "../../Packages/ChainServices"),
        .package(name: "FeatureServices", path: "../../Packages/FeatureServices"),
        .package(name: "GemstoneServices", path: "../../Packages/GemstoneServices"),
        .package(name: "GemstoneStore", path: "../../Packages/GemstoneStore"),
        .package(name: "GemAPI", path: "../../Packages/GemAPI"),
    ],
    targets: [
        .target(
            name: "Transfer",
            dependencies: [
                "Primitives",
                "Formatters",
                .product(name: "GemstoneFormatters", package: "Formatters"),
                "Localization",
                "Style",
                "Components",
                "PrimitivesComponents",
                "GemstonePrimitives",
                "Keystore",
                "Blockchain",
                "Signer",
                "Preferences",
                "Store",
                "Validators",

                "Stake",
                "WalletConnector",
                "InfoSheet",
                "Swap",
                "Perpetuals",

                .product(name: "ChainService", package: "ChainServices"),
                .product(name: "WalletSessionService", package: "FeatureServices"),
                .product(name: "NodeService", package: "ChainServices"),
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                .product(name: "ExplorerService", package: "ChainServices"),
                .product(name: "ActivityService", package: "FeatureServices"),
            ],
            path: "Sources",
        ),
        .target(
            name: "TransferTestKit",
            dependencies: [
                "Transfer",
                "Primitives",
                .product(name: "PrimitivesTestKit", package: "Primitives"),
            ],
            path: "TestKit",
        ),
        .testTarget(
            name: "TransferTests",
            dependencies: [
                .product(name: "GemstoneStore", package: "GemstoneStore"),
                "Transfer",
                "TransferTestKit",
                "Gemstone",
                "GemstonePrimitives",
                .product(name: "PrimitivesTestKit", package: "Primitives"),
                .product(name: "BlockchainTestKit", package: "Blockchain"),
                .product(name: "SwapServiceTestKit", package: "FeatureServices"),
                .product(name: "KeystoreTestKit", package: "Keystore"),
                .product(name: "WalletSessionService", package: "FeatureServices"),
                .product(name: "WalletSessionServiceTestKit", package: "FeatureServices"),
                .product(name: "NodeServiceTestKit", package: "ChainServices"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                .product(name: "ActivityServiceTestKit", package: "FeatureServices"),
                .product(name: "GemAPITestKit", package: "GemAPI"),
                .product(name: "ChainServiceTestKit", package: "ChainServices"),
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "StakeServiceTestKit", package: "ChainServices"),
                .product(name: "SignerTestKit", package: "Signer"),
                .product(name: "Signer", package: "Signer"),
            ],
            path: "Tests",
        ),
    ],
)
