mod config;
mod error;
mod ip_security_client;
mod redemption;
mod redemption_client;
mod referral;
mod rewards_abuse_checker;
mod rewards_client;
mod rewards_consumer;
mod rewards_eligibility_checker;
mod rewards_redemption_consumer;
mod risk;
mod summary;
mod username;

#[cfg(test)]
pub(crate) use config::AbuseDetectionConfig;
pub use config::{ReferralVerificationConfig, username_rules};
pub use error::RewardsServiceError;
pub use ip_security_client::IpSecurityClient;
pub use redemption::redeem_points;
pub use redemption_client::RewardsRedemptionClient;
pub use referral::{referral_use_facts, use_or_verify_referral};
pub use rewards_abuse_checker::RewardsAbuseChecker;
pub use rewards_client::RewardsClient;
pub use rewards_consumer::RewardsConsumer;
pub use rewards_eligibility_checker::RewardsEligibilityChecker;
pub use rewards_redemption_consumer::{RedemptionRetryConfig, RewardsRedemptionConsumer};
pub use risk::{RiskAssessment, assess_referral_risk};
pub use summary::rewards_by_wallet_id;
pub use username::create_username;
