// Generated by `just generate-models`. Do not edit.
// Declared in core/gemstone/src/constants.rs.

package com.gemwallet.android.ext

import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds

object GemConstants {
    val searchDebounce: Duration = 250.milliseconds
    val nodeCheckDebounce: Duration = 250.milliseconds
    val swapQuoteDebounce: Duration = 250.milliseconds
    val swapQuoteRefreshInterval: Duration = 30.seconds
    val fiatQuoteDebounce: Duration = 250.milliseconds
    val fiatQuoteRefreshInterval: Duration = 300.seconds
    val fiatQuoteCurrency: com.wallet.core.primitives.Currency = com.wallet.core.primitives.Currency.USD
    val connectionBannerSettleDelay: Duration = 10.seconds
    val connectionBannerEnabled: Boolean = false
    val offlineDebounce: Duration = 500.milliseconds
    val pingInterval: Duration = 30.seconds
    val scanTimeout: Duration = 3.seconds
    val serviceStatusTimeout: Duration = 30.seconds
    val transactionsListLimit: Int = 1000
    val assetResultsLimit: Int = 100
    val recentAssetsLimit: Int = 10
    val supportAttachmentMaxDimension: Int = 2048
    val supportAttachmentJpegQuality: Int = 90
    val walletConnectUserRejectedErrorCode: Int = 4001
    val walletConnectUserRejectedErrorMessage: String = "User rejected the request"
    val walletBannerEvents: List<com.wallet.core.primitives.BannerEvent> = listOf<com.wallet.core.primitives.BannerEvent>(com.wallet.core.primitives.BannerEvent.AccountBlockedMultiSignature, com.wallet.core.primitives.BannerEvent.Onboarding)
    val perpetualActivityTypes: List<com.wallet.core.primitives.TransactionType> = listOf<com.wallet.core.primitives.TransactionType>(com.wallet.core.primitives.TransactionType.PerpetualOpenPosition, com.wallet.core.primitives.TransactionType.PerpetualClosePosition, com.wallet.core.primitives.TransactionType.PerpetualModifyPosition)
    val acceptTermsItems: List<uniffi.gemstone.GemAcceptTermsItem> = listOf<uniffi.gemstone.GemAcceptTermsItem>(uniffi.gemstone.GemAcceptTermsItem.SELF_CUSTODY, uniffi.gemstone.GemAcceptTermsItem.RECOVERY, uniffi.gemstone.GemAcceptTermsItem.RESPONSIBILITY)
    val securityReminderItems: List<uniffi.gemstone.GemSecurityReminderItem> = listOf<uniffi.gemstone.GemSecurityReminderItem>(uniffi.gemstone.GemSecurityReminderItem.KEEP_SAFE, uniffi.gemstone.GemSecurityReminderItem.DO_NOT_SHARE, uniffi.gemstone.GemSecurityReminderItem.NO_RECOVERY)
    val lockPeriods: List<uniffi.gemstone.GemLockPeriod> = listOf<uniffi.gemstone.GemLockPeriod>(uniffi.gemstone.GemLockPeriod.IMMEDIATE, uniffi.gemstone.GemLockPeriod.ONE_MINUTE, uniffi.gemstone.GemLockPeriod.FIVE_MINUTES, uniffi.gemstone.GemLockPeriod.FIFTEEN_MINUTES, uniffi.gemstone.GemLockPeriod.ONE_HOUR, uniffi.gemstone.GemLockPeriod.SIX_HOURS)
    val walletAvatarEmojis: List<String> = listOf<String>("💎", "🦄", "🚀", "❤️", "😍", "🔥", "💩", "😭", "🏆", "🏴‍☠️", "✅", "⚠️", "💰", "🎁", "🎈", "🌈", "⭐️", "👑", "💔", "🔒", "🏦", "🥷", "👨‍💻", "🛢", "🔑", "🛡", "📈", "📉", "💥", "👽", "🔮", "⚡️", "🌍", "⏳", "🤖", "🛰", "🐉", "🐙", "🦅", "👀", "💪", "🔷", "👻", "🌪", "🕶", "👾", "🕵️‍♂️", "⌛️", "✨", "🍀", "☠️", "💀", "🕸", "🕷", "🎰", "☄️", "🏔", "🏜", "🌊", "🎆", "🎖", "🔭", "⛽️", "🏭", "🌉", "🏰", "🔨", "🧰", "💼", "🏷", "♟", "⚓️", "🎡", "🎢", "🎃", "📦")
}
