// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

package com.gemwallet.android.ext

fun uniffi.gemstone.AssetType.toPrimitives(): com.wallet.core.primitives.AssetType = when (this) {
    uniffi.gemstone.AssetType.NATIVE -> com.wallet.core.primitives.AssetType.NATIVE
    uniffi.gemstone.AssetType.ERC20 -> com.wallet.core.primitives.AssetType.ERC20
    uniffi.gemstone.AssetType.BEP20 -> com.wallet.core.primitives.AssetType.BEP20
    uniffi.gemstone.AssetType.SPL -> com.wallet.core.primitives.AssetType.SPL
    uniffi.gemstone.AssetType.SPL2022 -> com.wallet.core.primitives.AssetType.SPL2022
    uniffi.gemstone.AssetType.TRC20 -> com.wallet.core.primitives.AssetType.TRC20
    uniffi.gemstone.AssetType.TIP20 -> com.wallet.core.primitives.AssetType.TIP20
    uniffi.gemstone.AssetType.TOKEN -> com.wallet.core.primitives.AssetType.TOKEN
    uniffi.gemstone.AssetType.IBC -> com.wallet.core.primitives.AssetType.IBC
    uniffi.gemstone.AssetType.JETTON -> com.wallet.core.primitives.AssetType.JETTON
    uniffi.gemstone.AssetType.SYNTH -> com.wallet.core.primitives.AssetType.SYNTH
    uniffi.gemstone.AssetType.ASA -> com.wallet.core.primitives.AssetType.ASA
    uniffi.gemstone.AssetType.PERPETUAL -> com.wallet.core.primitives.AssetType.PERPETUAL
    uniffi.gemstone.AssetType.SPOT -> com.wallet.core.primitives.AssetType.SPOT
}

fun com.wallet.core.primitives.AssetType.toGem(): uniffi.gemstone.AssetType = when (this) {
    com.wallet.core.primitives.AssetType.NATIVE -> uniffi.gemstone.AssetType.NATIVE
    com.wallet.core.primitives.AssetType.ERC20 -> uniffi.gemstone.AssetType.ERC20
    com.wallet.core.primitives.AssetType.BEP20 -> uniffi.gemstone.AssetType.BEP20
    com.wallet.core.primitives.AssetType.SPL -> uniffi.gemstone.AssetType.SPL
    com.wallet.core.primitives.AssetType.SPL2022 -> uniffi.gemstone.AssetType.SPL2022
    com.wallet.core.primitives.AssetType.TRC20 -> uniffi.gemstone.AssetType.TRC20
    com.wallet.core.primitives.AssetType.TIP20 -> uniffi.gemstone.AssetType.TIP20
    com.wallet.core.primitives.AssetType.TOKEN -> uniffi.gemstone.AssetType.TOKEN
    com.wallet.core.primitives.AssetType.IBC -> uniffi.gemstone.AssetType.IBC
    com.wallet.core.primitives.AssetType.JETTON -> uniffi.gemstone.AssetType.JETTON
    com.wallet.core.primitives.AssetType.SYNTH -> uniffi.gemstone.AssetType.SYNTH
    com.wallet.core.primitives.AssetType.ASA -> uniffi.gemstone.AssetType.ASA
    com.wallet.core.primitives.AssetType.PERPETUAL -> uniffi.gemstone.AssetType.PERPETUAL
    com.wallet.core.primitives.AssetType.SPOT -> uniffi.gemstone.AssetType.SPOT
}

fun uniffi.gemstone.Currency.toCurrency(): com.wallet.core.primitives.Currency = com.wallet.core.primitives.Currency.entries.firstOrNull { it.string == this }
    ?: throw IllegalStateException("Core returned a Currency this build does not know: $this")

fun com.wallet.core.primitives.Currency.toGem(): uniffi.gemstone.Currency = string

fun uniffi.gemstone.FeePriority.toPrimitives(): com.wallet.core.primitives.FeePriority = when (this) {
    uniffi.gemstone.FeePriority.NORMAL -> com.wallet.core.primitives.FeePriority.Normal
    uniffi.gemstone.FeePriority.FAST -> com.wallet.core.primitives.FeePriority.Fast
}

fun com.wallet.core.primitives.FeePriority.toGem(): uniffi.gemstone.FeePriority = when (this) {
    com.wallet.core.primitives.FeePriority.Normal -> uniffi.gemstone.FeePriority.NORMAL
    com.wallet.core.primitives.FeePriority.Fast -> uniffi.gemstone.FeePriority.FAST
}

fun uniffi.gemstone.PerpetualProvider.toPrimitives(): com.wallet.core.primitives.PerpetualProvider = when (this) {
    uniffi.gemstone.PerpetualProvider.HYPERCORE -> com.wallet.core.primitives.PerpetualProvider.Hypercore
}

fun com.wallet.core.primitives.PerpetualProvider.toGem(): uniffi.gemstone.PerpetualProvider = when (this) {
    com.wallet.core.primitives.PerpetualProvider.Hypercore -> uniffi.gemstone.PerpetualProvider.HYPERCORE
}

fun uniffi.gemstone.RecentActivityType.toPrimitives(): com.wallet.core.primitives.RecentActivityType = when (this) {
    uniffi.gemstone.RecentActivityType.SEARCH -> com.wallet.core.primitives.RecentActivityType.Search
    uniffi.gemstone.RecentActivityType.TRANSFER -> com.wallet.core.primitives.RecentActivityType.Transfer
    uniffi.gemstone.RecentActivityType.RECEIVE -> com.wallet.core.primitives.RecentActivityType.Receive
    uniffi.gemstone.RecentActivityType.FIAT_BUY -> com.wallet.core.primitives.RecentActivityType.FiatBuy
    uniffi.gemstone.RecentActivityType.FIAT_SELL -> com.wallet.core.primitives.RecentActivityType.FiatSell
    uniffi.gemstone.RecentActivityType.SWAP -> com.wallet.core.primitives.RecentActivityType.Swap
    uniffi.gemstone.RecentActivityType.SWAP_SELECT -> com.wallet.core.primitives.RecentActivityType.SwapSelect
    uniffi.gemstone.RecentActivityType.PERPETUAL -> com.wallet.core.primitives.RecentActivityType.Perpetual
}

fun com.wallet.core.primitives.RecentActivityType.toGem(): uniffi.gemstone.RecentActivityType = when (this) {
    com.wallet.core.primitives.RecentActivityType.Search -> uniffi.gemstone.RecentActivityType.SEARCH
    com.wallet.core.primitives.RecentActivityType.Transfer -> uniffi.gemstone.RecentActivityType.TRANSFER
    com.wallet.core.primitives.RecentActivityType.Receive -> uniffi.gemstone.RecentActivityType.RECEIVE
    com.wallet.core.primitives.RecentActivityType.FiatBuy -> uniffi.gemstone.RecentActivityType.FIAT_BUY
    com.wallet.core.primitives.RecentActivityType.FiatSell -> uniffi.gemstone.RecentActivityType.FIAT_SELL
    com.wallet.core.primitives.RecentActivityType.Swap -> uniffi.gemstone.RecentActivityType.SWAP
    com.wallet.core.primitives.RecentActivityType.SwapSelect -> uniffi.gemstone.RecentActivityType.SWAP_SELECT
    com.wallet.core.primitives.RecentActivityType.Perpetual -> uniffi.gemstone.RecentActivityType.PERPETUAL
}

fun uniffi.gemstone.SimulationPayloadFieldDisplay.toPrimitives(): com.wallet.core.primitives.SimulationPayloadFieldDisplay = when (this) {
    uniffi.gemstone.SimulationPayloadFieldDisplay.PRIMARY -> com.wallet.core.primitives.SimulationPayloadFieldDisplay.Primary
    uniffi.gemstone.SimulationPayloadFieldDisplay.SECONDARY -> com.wallet.core.primitives.SimulationPayloadFieldDisplay.Secondary
}

fun com.wallet.core.primitives.SimulationPayloadFieldDisplay.toGem(): uniffi.gemstone.SimulationPayloadFieldDisplay = when (this) {
    com.wallet.core.primitives.SimulationPayloadFieldDisplay.Primary -> uniffi.gemstone.SimulationPayloadFieldDisplay.PRIMARY
    com.wallet.core.primitives.SimulationPayloadFieldDisplay.Secondary -> uniffi.gemstone.SimulationPayloadFieldDisplay.SECONDARY
}

fun uniffi.gemstone.SimulationPayloadFieldKind.toPrimitives(): com.wallet.core.primitives.SimulationPayloadFieldKind = when (this) {
    uniffi.gemstone.SimulationPayloadFieldKind.CONTRACT -> com.wallet.core.primitives.SimulationPayloadFieldKind.Contract
    uniffi.gemstone.SimulationPayloadFieldKind.METHOD -> com.wallet.core.primitives.SimulationPayloadFieldKind.Method
    uniffi.gemstone.SimulationPayloadFieldKind.TOKEN -> com.wallet.core.primitives.SimulationPayloadFieldKind.Token
    uniffi.gemstone.SimulationPayloadFieldKind.SPENDER -> com.wallet.core.primitives.SimulationPayloadFieldKind.Spender
    uniffi.gemstone.SimulationPayloadFieldKind.VALUE -> com.wallet.core.primitives.SimulationPayloadFieldKind.Value
    uniffi.gemstone.SimulationPayloadFieldKind.CUSTOM -> com.wallet.core.primitives.SimulationPayloadFieldKind.Custom
}

fun com.wallet.core.primitives.SimulationPayloadFieldKind.toGem(): uniffi.gemstone.SimulationPayloadFieldKind = when (this) {
    com.wallet.core.primitives.SimulationPayloadFieldKind.Contract -> uniffi.gemstone.SimulationPayloadFieldKind.CONTRACT
    com.wallet.core.primitives.SimulationPayloadFieldKind.Method -> uniffi.gemstone.SimulationPayloadFieldKind.METHOD
    com.wallet.core.primitives.SimulationPayloadFieldKind.Token -> uniffi.gemstone.SimulationPayloadFieldKind.TOKEN
    com.wallet.core.primitives.SimulationPayloadFieldKind.Spender -> uniffi.gemstone.SimulationPayloadFieldKind.SPENDER
    com.wallet.core.primitives.SimulationPayloadFieldKind.Value -> uniffi.gemstone.SimulationPayloadFieldKind.VALUE
    com.wallet.core.primitives.SimulationPayloadFieldKind.Custom -> uniffi.gemstone.SimulationPayloadFieldKind.CUSTOM
}

fun uniffi.gemstone.SimulationPayloadFieldType.toPrimitives(): com.wallet.core.primitives.SimulationPayloadFieldType = when (this) {
    uniffi.gemstone.SimulationPayloadFieldType.TEXT -> com.wallet.core.primitives.SimulationPayloadFieldType.Text
    uniffi.gemstone.SimulationPayloadFieldType.ADDRESS -> com.wallet.core.primitives.SimulationPayloadFieldType.Address
    uniffi.gemstone.SimulationPayloadFieldType.TIMESTAMP -> com.wallet.core.primitives.SimulationPayloadFieldType.Timestamp
}

fun com.wallet.core.primitives.SimulationPayloadFieldType.toGem(): uniffi.gemstone.SimulationPayloadFieldType = when (this) {
    com.wallet.core.primitives.SimulationPayloadFieldType.Text -> uniffi.gemstone.SimulationPayloadFieldType.TEXT
    com.wallet.core.primitives.SimulationPayloadFieldType.Address -> uniffi.gemstone.SimulationPayloadFieldType.ADDRESS
    com.wallet.core.primitives.SimulationPayloadFieldType.Timestamp -> uniffi.gemstone.SimulationPayloadFieldType.TIMESTAMP
}

fun uniffi.gemstone.TpslType.toPrimitives(): com.wallet.core.primitives.TpslType = when (this) {
    uniffi.gemstone.TpslType.TAKE_PROFIT -> com.wallet.core.primitives.TpslType.TakeProfit
    uniffi.gemstone.TpslType.STOP_LOSS -> com.wallet.core.primitives.TpslType.StopLoss
}

fun com.wallet.core.primitives.TpslType.toGem(): uniffi.gemstone.TpslType = when (this) {
    com.wallet.core.primitives.TpslType.TakeProfit -> uniffi.gemstone.TpslType.TAKE_PROFIT
    com.wallet.core.primitives.TpslType.StopLoss -> uniffi.gemstone.TpslType.STOP_LOSS
}

fun uniffi.gemstone.WalletConnectionVerificationStatus.toPrimitives(): com.wallet.core.primitives.WalletConnectionVerificationStatus = when (this) {
    uniffi.gemstone.WalletConnectionVerificationStatus.VERIFIED -> com.wallet.core.primitives.WalletConnectionVerificationStatus.Verified
    uniffi.gemstone.WalletConnectionVerificationStatus.UNKNOWN -> com.wallet.core.primitives.WalletConnectionVerificationStatus.Unknown
    uniffi.gemstone.WalletConnectionVerificationStatus.INVALID -> com.wallet.core.primitives.WalletConnectionVerificationStatus.Invalid
    uniffi.gemstone.WalletConnectionVerificationStatus.MALICIOUS -> com.wallet.core.primitives.WalletConnectionVerificationStatus.Malicious
}

fun com.wallet.core.primitives.WalletConnectionVerificationStatus.toGem(): uniffi.gemstone.WalletConnectionVerificationStatus = when (this) {
    com.wallet.core.primitives.WalletConnectionVerificationStatus.Verified -> uniffi.gemstone.WalletConnectionVerificationStatus.VERIFIED
    com.wallet.core.primitives.WalletConnectionVerificationStatus.Unknown -> uniffi.gemstone.WalletConnectionVerificationStatus.UNKNOWN
    com.wallet.core.primitives.WalletConnectionVerificationStatus.Invalid -> uniffi.gemstone.WalletConnectionVerificationStatus.INVALID
    com.wallet.core.primitives.WalletConnectionVerificationStatus.Malicious -> uniffi.gemstone.WalletConnectionVerificationStatus.MALICIOUS
}

fun uniffi.gemstone.WalletSource.toPrimitives(): com.wallet.core.primitives.WalletSource = when (this) {
    uniffi.gemstone.WalletSource.CREATE -> com.wallet.core.primitives.WalletSource.Create
    uniffi.gemstone.WalletSource.IMPORT -> com.wallet.core.primitives.WalletSource.Import
}

fun com.wallet.core.primitives.WalletSource.toGem(): uniffi.gemstone.WalletSource = when (this) {
    com.wallet.core.primitives.WalletSource.Create -> uniffi.gemstone.WalletSource.CREATE
    com.wallet.core.primitives.WalletSource.Import -> uniffi.gemstone.WalletSource.IMPORT
}

fun uniffi.gemstone.WalletType.toPrimitives(): com.wallet.core.primitives.WalletType = when (this) {
    uniffi.gemstone.WalletType.MULTICOIN -> com.wallet.core.primitives.WalletType.Multicoin
    uniffi.gemstone.WalletType.SINGLE -> com.wallet.core.primitives.WalletType.Single
    uniffi.gemstone.WalletType.PRIVATE_KEY -> com.wallet.core.primitives.WalletType.PrivateKey
    uniffi.gemstone.WalletType.VIEW -> com.wallet.core.primitives.WalletType.View
}

fun com.wallet.core.primitives.WalletType.toGem(): uniffi.gemstone.WalletType = when (this) {
    com.wallet.core.primitives.WalletType.Multicoin -> uniffi.gemstone.WalletType.MULTICOIN
    com.wallet.core.primitives.WalletType.Single -> uniffi.gemstone.WalletType.SINGLE
    com.wallet.core.primitives.WalletType.PrivateKey -> uniffi.gemstone.WalletType.PRIVATE_KEY
    com.wallet.core.primitives.WalletType.View -> uniffi.gemstone.WalletType.VIEW
}

fun uniffi.gemstone.Asset.toPrimitives(): com.wallet.core.primitives.Asset = com.wallet.core.primitives.Asset(
    id = id.toAssetId()!!,
    name = name,
    symbol = symbol,
    decimals = decimals,
    type = assetType.toPrimitives(),
)

fun com.wallet.core.primitives.Asset.toGem(): uniffi.gemstone.Asset = uniffi.gemstone.Asset(
    id = id.toIdentifier(),
    name = name,
    symbol = symbol,
    decimals = decimals,
    assetType = type.toGem(),
)

fun uniffi.gemstone.SimulationPayloadField.toPrimitives(): com.wallet.core.primitives.SimulationPayloadField = com.wallet.core.primitives.SimulationPayloadField(
    kind = kind.toPrimitives(),
    label = label,
    value = value,
    fieldType = fieldType.toPrimitives(),
    display = display.toPrimitives(),
)

fun com.wallet.core.primitives.SimulationPayloadField.toGem(): uniffi.gemstone.SimulationPayloadField = uniffi.gemstone.SimulationPayloadField(
    kind = kind.toGem(),
    label = label,
    value = value,
    fieldType = fieldType.toGem(),
    display = display.toGem(),
)
