// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

package com.gemwallet.android.ext

fun uniffi.gemstone.AccountDataType.toPrimitives(): com.wallet.core.primitives.AccountDataType = when (this) {
    uniffi.gemstone.AccountDataType.ACTIVATE -> com.wallet.core.primitives.AccountDataType.Activate
}

fun com.wallet.core.primitives.AccountDataType.toGem(): uniffi.gemstone.AccountDataType = when (this) {
    com.wallet.core.primitives.AccountDataType.Activate -> uniffi.gemstone.AccountDataType.ACTIVATE
}

fun uniffi.gemstone.AddressType.toPrimitives(): com.wallet.core.primitives.AddressType = when (this) {
    uniffi.gemstone.AddressType.ADDRESS -> com.wallet.core.primitives.AddressType.Address
    uniffi.gemstone.AddressType.CONTRACT -> com.wallet.core.primitives.AddressType.Contract
    uniffi.gemstone.AddressType.VALIDATOR -> com.wallet.core.primitives.AddressType.Validator
    uniffi.gemstone.AddressType.CONTACT -> com.wallet.core.primitives.AddressType.Contact
    uniffi.gemstone.AddressType.INTERNAL_WALLET -> com.wallet.core.primitives.AddressType.InternalWallet
}

fun com.wallet.core.primitives.AddressType.toGem(): uniffi.gemstone.AddressType = when (this) {
    com.wallet.core.primitives.AddressType.Address -> uniffi.gemstone.AddressType.ADDRESS
    com.wallet.core.primitives.AddressType.Contract -> uniffi.gemstone.AddressType.CONTRACT
    com.wallet.core.primitives.AddressType.Validator -> uniffi.gemstone.AddressType.VALIDATOR
    com.wallet.core.primitives.AddressType.Contact -> uniffi.gemstone.AddressType.CONTACT
    com.wallet.core.primitives.AddressType.InternalWallet -> uniffi.gemstone.AddressType.INTERNAL_WALLET
}

fun uniffi.gemstone.Appearance.toPrimitives(): com.wallet.core.primitives.Appearance = when (this) {
    uniffi.gemstone.Appearance.SYSTEM -> com.wallet.core.primitives.Appearance.System
    uniffi.gemstone.Appearance.LIGHT -> com.wallet.core.primitives.Appearance.Light
    uniffi.gemstone.Appearance.DARK -> com.wallet.core.primitives.Appearance.Dark
}

fun com.wallet.core.primitives.Appearance.toGem(): uniffi.gemstone.Appearance = when (this) {
    com.wallet.core.primitives.Appearance.System -> uniffi.gemstone.Appearance.SYSTEM
    com.wallet.core.primitives.Appearance.Light -> uniffi.gemstone.Appearance.LIGHT
    com.wallet.core.primitives.Appearance.Dark -> uniffi.gemstone.Appearance.DARK
}

fun uniffi.gemstone.ApplicationMetadataSource.toPrimitives(): com.wallet.core.primitives.ApplicationMetadataSource = when (this) {
    uniffi.gemstone.ApplicationMetadataSource.WALLET_CONNECT -> com.wallet.core.primitives.ApplicationMetadataSource.WalletConnect
    uniffi.gemstone.ApplicationMetadataSource.PAYMENT -> com.wallet.core.primitives.ApplicationMetadataSource.Payment
}

fun com.wallet.core.primitives.ApplicationMetadataSource.toGem(): uniffi.gemstone.ApplicationMetadataSource = when (this) {
    com.wallet.core.primitives.ApplicationMetadataSource.WalletConnect -> uniffi.gemstone.ApplicationMetadataSource.WALLET_CONNECT
    com.wallet.core.primitives.ApplicationMetadataSource.Payment -> uniffi.gemstone.ApplicationMetadataSource.PAYMENT
}

fun uniffi.gemstone.AssetType.toPrimitives(): com.wallet.core.primitives.AssetType = when (this) {
    uniffi.gemstone.AssetType.NATIVE -> com.wallet.core.primitives.AssetType.NATIVE
    uniffi.gemstone.AssetType.ERC20 -> com.wallet.core.primitives.AssetType.ERC20
    uniffi.gemstone.AssetType.BEP20 -> com.wallet.core.primitives.AssetType.BEP20
    uniffi.gemstone.AssetType.SPL -> com.wallet.core.primitives.AssetType.SPL
    uniffi.gemstone.AssetType.SPL2022 -> com.wallet.core.primitives.AssetType.SPL2022
    uniffi.gemstone.AssetType.TRC20 -> com.wallet.core.primitives.AssetType.TRC20
    uniffi.gemstone.AssetType.TIP20 -> com.wallet.core.primitives.AssetType.TIP20
    uniffi.gemstone.AssetType.TOKEN -> com.wallet.core.primitives.AssetType.TOKEN
    uniffi.gemstone.AssetType.IBC -> com.wallet.core.primitives.AssetType.IBC
    uniffi.gemstone.AssetType.JETTON -> com.wallet.core.primitives.AssetType.JETTON
    uniffi.gemstone.AssetType.SYNTH -> com.wallet.core.primitives.AssetType.SYNTH
    uniffi.gemstone.AssetType.ASA -> com.wallet.core.primitives.AssetType.ASA
    uniffi.gemstone.AssetType.PERPETUAL -> com.wallet.core.primitives.AssetType.PERPETUAL
    uniffi.gemstone.AssetType.SPOT -> com.wallet.core.primitives.AssetType.SPOT
}

fun com.wallet.core.primitives.AssetType.toGem(): uniffi.gemstone.AssetType = when (this) {
    com.wallet.core.primitives.AssetType.NATIVE -> uniffi.gemstone.AssetType.NATIVE
    com.wallet.core.primitives.AssetType.ERC20 -> uniffi.gemstone.AssetType.ERC20
    com.wallet.core.primitives.AssetType.BEP20 -> uniffi.gemstone.AssetType.BEP20
    com.wallet.core.primitives.AssetType.SPL -> uniffi.gemstone.AssetType.SPL
    com.wallet.core.primitives.AssetType.SPL2022 -> uniffi.gemstone.AssetType.SPL2022
    com.wallet.core.primitives.AssetType.TRC20 -> uniffi.gemstone.AssetType.TRC20
    com.wallet.core.primitives.AssetType.TIP20 -> uniffi.gemstone.AssetType.TIP20
    com.wallet.core.primitives.AssetType.TOKEN -> uniffi.gemstone.AssetType.TOKEN
    com.wallet.core.primitives.AssetType.IBC -> uniffi.gemstone.AssetType.IBC
    com.wallet.core.primitives.AssetType.JETTON -> uniffi.gemstone.AssetType.JETTON
    com.wallet.core.primitives.AssetType.SYNTH -> uniffi.gemstone.AssetType.SYNTH
    com.wallet.core.primitives.AssetType.ASA -> uniffi.gemstone.AssetType.ASA
    com.wallet.core.primitives.AssetType.PERPETUAL -> uniffi.gemstone.AssetType.PERPETUAL
    com.wallet.core.primitives.AssetType.SPOT -> uniffi.gemstone.AssetType.SPOT
}

fun uniffi.gemstone.BannerEvent.toPrimitives(): com.wallet.core.primitives.BannerEvent = when (this) {
    uniffi.gemstone.BannerEvent.STAKE -> com.wallet.core.primitives.BannerEvent.Stake
    uniffi.gemstone.BannerEvent.ACCOUNT_ACTIVATION -> com.wallet.core.primitives.BannerEvent.AccountActivation
    uniffi.gemstone.BannerEvent.ACCOUNT_BLOCKED_MULTI_SIGNATURE -> com.wallet.core.primitives.BannerEvent.AccountBlockedMultiSignature
    uniffi.gemstone.BannerEvent.ACTIVATE_ASSET -> com.wallet.core.primitives.BannerEvent.ActivateAsset
    uniffi.gemstone.BannerEvent.SUSPICIOUS_ASSET -> com.wallet.core.primitives.BannerEvent.SuspiciousAsset
    uniffi.gemstone.BannerEvent.ONBOARDING -> com.wallet.core.primitives.BannerEvent.Onboarding
    uniffi.gemstone.BannerEvent.TRADE_PERPETUALS -> com.wallet.core.primitives.BannerEvent.TradePerpetuals
}

fun com.wallet.core.primitives.BannerEvent.toGem(): uniffi.gemstone.BannerEvent = when (this) {
    com.wallet.core.primitives.BannerEvent.Stake -> uniffi.gemstone.BannerEvent.STAKE
    com.wallet.core.primitives.BannerEvent.AccountActivation -> uniffi.gemstone.BannerEvent.ACCOUNT_ACTIVATION
    com.wallet.core.primitives.BannerEvent.AccountBlockedMultiSignature -> uniffi.gemstone.BannerEvent.ACCOUNT_BLOCKED_MULTI_SIGNATURE
    com.wallet.core.primitives.BannerEvent.ActivateAsset -> uniffi.gemstone.BannerEvent.ACTIVATE_ASSET
    com.wallet.core.primitives.BannerEvent.SuspiciousAsset -> uniffi.gemstone.BannerEvent.SUSPICIOUS_ASSET
    com.wallet.core.primitives.BannerEvent.Onboarding -> uniffi.gemstone.BannerEvent.ONBOARDING
    com.wallet.core.primitives.BannerEvent.TradePerpetuals -> uniffi.gemstone.BannerEvent.TRADE_PERPETUALS
}

fun uniffi.gemstone.BannerState.toPrimitives(): com.wallet.core.primitives.BannerState = when (this) {
    uniffi.gemstone.BannerState.ACTIVE -> com.wallet.core.primitives.BannerState.Active
    uniffi.gemstone.BannerState.CANCELLED -> com.wallet.core.primitives.BannerState.Cancelled
    uniffi.gemstone.BannerState.ALWAYS_ACTIVE -> com.wallet.core.primitives.BannerState.AlwaysActive
}

fun com.wallet.core.primitives.BannerState.toGem(): uniffi.gemstone.BannerState = when (this) {
    com.wallet.core.primitives.BannerState.Active -> uniffi.gemstone.BannerState.ACTIVE
    com.wallet.core.primitives.BannerState.Cancelled -> uniffi.gemstone.BannerState.CANCELLED
    com.wallet.core.primitives.BannerState.AlwaysActive -> uniffi.gemstone.BannerState.ALWAYS_ACTIVE
}

fun uniffi.gemstone.Chain.toChain(): com.wallet.core.primitives.Chain = com.wallet.core.primitives.Chain.entries.firstOrNull { it.string == this }
    ?: throw IllegalStateException("Core returned a Chain this build does not know: $this")

fun com.wallet.core.primitives.Chain.toGem(): uniffi.gemstone.Chain = string

fun uniffi.gemstone.ChainType.toPrimitives(): com.wallet.core.primitives.ChainType = when (this) {
    uniffi.gemstone.ChainType.ETHEREUM -> com.wallet.core.primitives.ChainType.Ethereum
    uniffi.gemstone.ChainType.BITCOIN -> com.wallet.core.primitives.ChainType.Bitcoin
    uniffi.gemstone.ChainType.SOLANA -> com.wallet.core.primitives.ChainType.Solana
    uniffi.gemstone.ChainType.COSMOS -> com.wallet.core.primitives.ChainType.Cosmos
    uniffi.gemstone.ChainType.TON -> com.wallet.core.primitives.ChainType.Ton
    uniffi.gemstone.ChainType.TRON -> com.wallet.core.primitives.ChainType.Tron
    uniffi.gemstone.ChainType.APTOS -> com.wallet.core.primitives.ChainType.Aptos
    uniffi.gemstone.ChainType.SUI -> com.wallet.core.primitives.ChainType.Sui
    uniffi.gemstone.ChainType.XRP -> com.wallet.core.primitives.ChainType.Xrp
    uniffi.gemstone.ChainType.NEAR -> com.wallet.core.primitives.ChainType.Near
    uniffi.gemstone.ChainType.STELLAR -> com.wallet.core.primitives.ChainType.Stellar
    uniffi.gemstone.ChainType.ALGORAND -> com.wallet.core.primitives.ChainType.Algorand
    uniffi.gemstone.ChainType.POLKADOT -> com.wallet.core.primitives.ChainType.Polkadot
    uniffi.gemstone.ChainType.CARDANO -> com.wallet.core.primitives.ChainType.Cardano
    uniffi.gemstone.ChainType.HYPER_CORE -> com.wallet.core.primitives.ChainType.HyperCore
}

fun com.wallet.core.primitives.ChainType.toGem(): uniffi.gemstone.ChainType = when (this) {
    com.wallet.core.primitives.ChainType.Ethereum -> uniffi.gemstone.ChainType.ETHEREUM
    com.wallet.core.primitives.ChainType.Bitcoin -> uniffi.gemstone.ChainType.BITCOIN
    com.wallet.core.primitives.ChainType.Solana -> uniffi.gemstone.ChainType.SOLANA
    com.wallet.core.primitives.ChainType.Cosmos -> uniffi.gemstone.ChainType.COSMOS
    com.wallet.core.primitives.ChainType.Ton -> uniffi.gemstone.ChainType.TON
    com.wallet.core.primitives.ChainType.Tron -> uniffi.gemstone.ChainType.TRON
    com.wallet.core.primitives.ChainType.Aptos -> uniffi.gemstone.ChainType.APTOS
    com.wallet.core.primitives.ChainType.Sui -> uniffi.gemstone.ChainType.SUI
    com.wallet.core.primitives.ChainType.Xrp -> uniffi.gemstone.ChainType.XRP
    com.wallet.core.primitives.ChainType.Near -> uniffi.gemstone.ChainType.NEAR
    com.wallet.core.primitives.ChainType.Stellar -> uniffi.gemstone.ChainType.STELLAR
    com.wallet.core.primitives.ChainType.Algorand -> uniffi.gemstone.ChainType.ALGORAND
    com.wallet.core.primitives.ChainType.Polkadot -> uniffi.gemstone.ChainType.POLKADOT
    com.wallet.core.primitives.ChainType.Cardano -> uniffi.gemstone.ChainType.CARDANO
    com.wallet.core.primitives.ChainType.HyperCore -> uniffi.gemstone.ChainType.HYPER_CORE
}

fun uniffi.gemstone.ChartPeriod.toPrimitives(): com.wallet.core.primitives.ChartPeriod = when (this) {
    uniffi.gemstone.ChartPeriod.HOUR -> com.wallet.core.primitives.ChartPeriod.Hour
    uniffi.gemstone.ChartPeriod.DAY -> com.wallet.core.primitives.ChartPeriod.Day
    uniffi.gemstone.ChartPeriod.WEEK -> com.wallet.core.primitives.ChartPeriod.Week
    uniffi.gemstone.ChartPeriod.MONTH -> com.wallet.core.primitives.ChartPeriod.Month
    uniffi.gemstone.ChartPeriod.YEAR -> com.wallet.core.primitives.ChartPeriod.Year
    uniffi.gemstone.ChartPeriod.ALL -> com.wallet.core.primitives.ChartPeriod.All
}

fun com.wallet.core.primitives.ChartPeriod.toGem(): uniffi.gemstone.ChartPeriod = when (this) {
    com.wallet.core.primitives.ChartPeriod.Hour -> uniffi.gemstone.ChartPeriod.HOUR
    com.wallet.core.primitives.ChartPeriod.Day -> uniffi.gemstone.ChartPeriod.DAY
    com.wallet.core.primitives.ChartPeriod.Week -> uniffi.gemstone.ChartPeriod.WEEK
    com.wallet.core.primitives.ChartPeriod.Month -> uniffi.gemstone.ChartPeriod.MONTH
    com.wallet.core.primitives.ChartPeriod.Year -> uniffi.gemstone.ChartPeriod.YEAR
    com.wallet.core.primitives.ChartPeriod.All -> uniffi.gemstone.ChartPeriod.ALL
}

fun uniffi.gemstone.ConnectionComponent.toPrimitives(): com.wallet.core.primitives.ConnectionComponent = when (this) {
    uniffi.gemstone.ConnectionComponent.INTERNET -> com.wallet.core.primitives.ConnectionComponent.Internet
    uniffi.gemstone.ConnectionComponent.API -> com.wallet.core.primitives.ConnectionComponent.Api
    uniffi.gemstone.ConnectionComponent.NODES -> com.wallet.core.primitives.ConnectionComponent.Nodes
    uniffi.gemstone.ConnectionComponent.STREAM -> com.wallet.core.primitives.ConnectionComponent.Stream
}

fun com.wallet.core.primitives.ConnectionComponent.toGem(): uniffi.gemstone.ConnectionComponent = when (this) {
    com.wallet.core.primitives.ConnectionComponent.Internet -> uniffi.gemstone.ConnectionComponent.INTERNET
    com.wallet.core.primitives.ConnectionComponent.Api -> uniffi.gemstone.ConnectionComponent.API
    com.wallet.core.primitives.ConnectionComponent.Nodes -> uniffi.gemstone.ConnectionComponent.NODES
    com.wallet.core.primitives.ConnectionComponent.Stream -> uniffi.gemstone.ConnectionComponent.STREAM
}

fun uniffi.gemstone.ConnectionStatus.toPrimitives(): com.wallet.core.primitives.ConnectionStatus = when (this) {
    uniffi.gemstone.ConnectionStatus.ONLINE -> com.wallet.core.primitives.ConnectionStatus.Online
    uniffi.gemstone.ConnectionStatus.NO_INTERNET -> com.wallet.core.primitives.ConnectionStatus.NoInternet
    uniffi.gemstone.ConnectionStatus.NO_SERVICE -> com.wallet.core.primitives.ConnectionStatus.NoService
}

fun com.wallet.core.primitives.ConnectionStatus.toGem(): uniffi.gemstone.ConnectionStatus = when (this) {
    com.wallet.core.primitives.ConnectionStatus.Online -> uniffi.gemstone.ConnectionStatus.ONLINE
    com.wallet.core.primitives.ConnectionStatus.NoInternet -> uniffi.gemstone.ConnectionStatus.NO_INTERNET
    com.wallet.core.primitives.ConnectionStatus.NoService -> uniffi.gemstone.ConnectionStatus.NO_SERVICE
}

fun uniffi.gemstone.Currency.toCurrency(): com.wallet.core.primitives.Currency = com.wallet.core.primitives.Currency.entries.firstOrNull { it.string == this }
    ?: throw IllegalStateException("Core returned a Currency this build does not know: $this")

fun com.wallet.core.primitives.Currency.toGem(): uniffi.gemstone.Currency = string

fun uniffi.gemstone.DelegationState.toPrimitives(): com.wallet.core.primitives.DelegationState = when (this) {
    uniffi.gemstone.DelegationState.ACTIVE -> com.wallet.core.primitives.DelegationState.Active
    uniffi.gemstone.DelegationState.PENDING -> com.wallet.core.primitives.DelegationState.Pending
    uniffi.gemstone.DelegationState.INACTIVE -> com.wallet.core.primitives.DelegationState.Inactive
    uniffi.gemstone.DelegationState.ACTIVATING -> com.wallet.core.primitives.DelegationState.Activating
    uniffi.gemstone.DelegationState.DEACTIVATING -> com.wallet.core.primitives.DelegationState.Deactivating
    uniffi.gemstone.DelegationState.AWAITING_WITHDRAWAL -> com.wallet.core.primitives.DelegationState.AwaitingWithdrawal
}

fun com.wallet.core.primitives.DelegationState.toGem(): uniffi.gemstone.DelegationState = when (this) {
    com.wallet.core.primitives.DelegationState.Active -> uniffi.gemstone.DelegationState.ACTIVE
    com.wallet.core.primitives.DelegationState.Pending -> uniffi.gemstone.DelegationState.PENDING
    com.wallet.core.primitives.DelegationState.Inactive -> uniffi.gemstone.DelegationState.INACTIVE
    com.wallet.core.primitives.DelegationState.Activating -> uniffi.gemstone.DelegationState.ACTIVATING
    com.wallet.core.primitives.DelegationState.Deactivating -> uniffi.gemstone.DelegationState.DEACTIVATING
    com.wallet.core.primitives.DelegationState.AwaitingWithdrawal -> uniffi.gemstone.DelegationState.AWAITING_WITHDRAWAL
}

fun uniffi.gemstone.FeePriority.toPrimitives(): com.wallet.core.primitives.FeePriority = when (this) {
    uniffi.gemstone.FeePriority.NORMAL -> com.wallet.core.primitives.FeePriority.Normal
    uniffi.gemstone.FeePriority.FAST -> com.wallet.core.primitives.FeePriority.Fast
}

fun com.wallet.core.primitives.FeePriority.toGem(): uniffi.gemstone.FeePriority = when (this) {
    com.wallet.core.primitives.FeePriority.Normal -> uniffi.gemstone.FeePriority.NORMAL
    com.wallet.core.primitives.FeePriority.Fast -> uniffi.gemstone.FeePriority.FAST
}

fun uniffi.gemstone.FeeUnitType.toPrimitives(): com.wallet.core.primitives.FeeUnitType = when (this) {
    uniffi.gemstone.FeeUnitType.SAT_VB -> com.wallet.core.primitives.FeeUnitType.SatVb
    uniffi.gemstone.FeeUnitType.GWEI -> com.wallet.core.primitives.FeeUnitType.Gwei
    uniffi.gemstone.FeeUnitType.NATIVE -> com.wallet.core.primitives.FeeUnitType.Native
}

fun com.wallet.core.primitives.FeeUnitType.toGem(): uniffi.gemstone.FeeUnitType = when (this) {
    com.wallet.core.primitives.FeeUnitType.SatVb -> uniffi.gemstone.FeeUnitType.SAT_VB
    com.wallet.core.primitives.FeeUnitType.Gwei -> uniffi.gemstone.FeeUnitType.GWEI
    com.wallet.core.primitives.FeeUnitType.Native -> uniffi.gemstone.FeeUnitType.NATIVE
}

fun uniffi.gemstone.FiatQuoteType.toPrimitives(): com.wallet.core.primitives.FiatQuoteType = when (this) {
    uniffi.gemstone.FiatQuoteType.BUY -> com.wallet.core.primitives.FiatQuoteType.Buy
    uniffi.gemstone.FiatQuoteType.SELL -> com.wallet.core.primitives.FiatQuoteType.Sell
}

fun com.wallet.core.primitives.FiatQuoteType.toGem(): uniffi.gemstone.FiatQuoteType = when (this) {
    com.wallet.core.primitives.FiatQuoteType.Buy -> uniffi.gemstone.FiatQuoteType.BUY
    com.wallet.core.primitives.FiatQuoteType.Sell -> uniffi.gemstone.FiatQuoteType.SELL
}

fun uniffi.gemstone.LatencyType.toPrimitives(): com.wallet.core.primitives.LatencyType = when (this) {
    uniffi.gemstone.LatencyType.FAST -> com.wallet.core.primitives.LatencyType.Fast
    uniffi.gemstone.LatencyType.NORMAL -> com.wallet.core.primitives.LatencyType.Normal
    uniffi.gemstone.LatencyType.SLOW -> com.wallet.core.primitives.LatencyType.Slow
}

fun com.wallet.core.primitives.LatencyType.toGem(): uniffi.gemstone.LatencyType = when (this) {
    com.wallet.core.primitives.LatencyType.Fast -> uniffi.gemstone.LatencyType.FAST
    com.wallet.core.primitives.LatencyType.Normal -> uniffi.gemstone.LatencyType.NORMAL
    com.wallet.core.primitives.LatencyType.Slow -> uniffi.gemstone.LatencyType.SLOW
}

fun uniffi.gemstone.LinkType.toPrimitives(): com.wallet.core.primitives.LinkType = when (this) {
    uniffi.gemstone.LinkType.X -> com.wallet.core.primitives.LinkType.X
    uniffi.gemstone.LinkType.DISCORD -> com.wallet.core.primitives.LinkType.Discord
    uniffi.gemstone.LinkType.REDDIT -> com.wallet.core.primitives.LinkType.Reddit
    uniffi.gemstone.LinkType.TELEGRAM -> com.wallet.core.primitives.LinkType.Telegram
    uniffi.gemstone.LinkType.GIT_HUB -> com.wallet.core.primitives.LinkType.GitHub
    uniffi.gemstone.LinkType.YOU_TUBE -> com.wallet.core.primitives.LinkType.YouTube
    uniffi.gemstone.LinkType.FACEBOOK -> com.wallet.core.primitives.LinkType.Facebook
    uniffi.gemstone.LinkType.WEBSITE -> com.wallet.core.primitives.LinkType.Website
    uniffi.gemstone.LinkType.COINGECKO -> com.wallet.core.primitives.LinkType.Coingecko
    uniffi.gemstone.LinkType.OPEN_SEA -> com.wallet.core.primitives.LinkType.OpenSea
    uniffi.gemstone.LinkType.INSTAGRAM -> com.wallet.core.primitives.LinkType.Instagram
    uniffi.gemstone.LinkType.MAGIC_EDEN -> com.wallet.core.primitives.LinkType.MagicEden
    uniffi.gemstone.LinkType.COIN_MARKET_CAP -> com.wallet.core.primitives.LinkType.CoinMarketCap
    uniffi.gemstone.LinkType.TIK_TOK -> com.wallet.core.primitives.LinkType.TikTok
}

fun com.wallet.core.primitives.LinkType.toGem(): uniffi.gemstone.LinkType = when (this) {
    com.wallet.core.primitives.LinkType.X -> uniffi.gemstone.LinkType.X
    com.wallet.core.primitives.LinkType.Discord -> uniffi.gemstone.LinkType.DISCORD
    com.wallet.core.primitives.LinkType.Reddit -> uniffi.gemstone.LinkType.REDDIT
    com.wallet.core.primitives.LinkType.Telegram -> uniffi.gemstone.LinkType.TELEGRAM
    com.wallet.core.primitives.LinkType.GitHub -> uniffi.gemstone.LinkType.GIT_HUB
    com.wallet.core.primitives.LinkType.YouTube -> uniffi.gemstone.LinkType.YOU_TUBE
    com.wallet.core.primitives.LinkType.Facebook -> uniffi.gemstone.LinkType.FACEBOOK
    com.wallet.core.primitives.LinkType.Website -> uniffi.gemstone.LinkType.WEBSITE
    com.wallet.core.primitives.LinkType.Coingecko -> uniffi.gemstone.LinkType.COINGECKO
    com.wallet.core.primitives.LinkType.OpenSea -> uniffi.gemstone.LinkType.OPEN_SEA
    com.wallet.core.primitives.LinkType.Instagram -> uniffi.gemstone.LinkType.INSTAGRAM
    com.wallet.core.primitives.LinkType.MagicEden -> uniffi.gemstone.LinkType.MAGIC_EDEN
    com.wallet.core.primitives.LinkType.CoinMarketCap -> uniffi.gemstone.LinkType.COIN_MARKET_CAP
    com.wallet.core.primitives.LinkType.TikTok -> uniffi.gemstone.LinkType.TIK_TOK
}

fun uniffi.gemstone.NameProvider.toPrimitives(): com.wallet.core.primitives.NameProvider = when (this) {
    uniffi.gemstone.NameProvider.UD -> com.wallet.core.primitives.NameProvider.Ud
    uniffi.gemstone.NameProvider.ENS -> com.wallet.core.primitives.NameProvider.Ens
    uniffi.gemstone.NameProvider.SNS -> com.wallet.core.primitives.NameProvider.Sns
    uniffi.gemstone.NameProvider.TON -> com.wallet.core.primitives.NameProvider.Ton
    uniffi.gemstone.NameProvider.SPACEID -> com.wallet.core.primitives.NameProvider.Spaceid
    uniffi.gemstone.NameProvider.DID -> com.wallet.core.primitives.NameProvider.Did
    uniffi.gemstone.NameProvider.SUINS -> com.wallet.core.primitives.NameProvider.Suins
    uniffi.gemstone.NameProvider.APTOS -> com.wallet.core.primitives.NameProvider.Aptos
    uniffi.gemstone.NameProvider.INJECTIVE -> com.wallet.core.primitives.NameProvider.Injective
    uniffi.gemstone.NameProvider.ICNS -> com.wallet.core.primitives.NameProvider.Icns
    uniffi.gemstone.NameProvider.LENS -> com.wallet.core.primitives.NameProvider.Lens
    uniffi.gemstone.NameProvider.BASENAMES -> com.wallet.core.primitives.NameProvider.Basenames
    uniffi.gemstone.NameProvider.HYPERLIQUID -> com.wallet.core.primitives.NameProvider.Hyperliquid
    uniffi.gemstone.NameProvider.ALL_DOMAINS -> com.wallet.core.primitives.NameProvider.AllDomains
    uniffi.gemstone.NameProvider.NEAR -> com.wallet.core.primitives.NameProvider.Near
}

fun com.wallet.core.primitives.NameProvider.toGem(): uniffi.gemstone.NameProvider = when (this) {
    com.wallet.core.primitives.NameProvider.Ud -> uniffi.gemstone.NameProvider.UD
    com.wallet.core.primitives.NameProvider.Ens -> uniffi.gemstone.NameProvider.ENS
    com.wallet.core.primitives.NameProvider.Sns -> uniffi.gemstone.NameProvider.SNS
    com.wallet.core.primitives.NameProvider.Ton -> uniffi.gemstone.NameProvider.TON
    com.wallet.core.primitives.NameProvider.Spaceid -> uniffi.gemstone.NameProvider.SPACEID
    com.wallet.core.primitives.NameProvider.Did -> uniffi.gemstone.NameProvider.DID
    com.wallet.core.primitives.NameProvider.Suins -> uniffi.gemstone.NameProvider.SUINS
    com.wallet.core.primitives.NameProvider.Aptos -> uniffi.gemstone.NameProvider.APTOS
    com.wallet.core.primitives.NameProvider.Injective -> uniffi.gemstone.NameProvider.INJECTIVE
    com.wallet.core.primitives.NameProvider.Icns -> uniffi.gemstone.NameProvider.ICNS
    com.wallet.core.primitives.NameProvider.Lens -> uniffi.gemstone.NameProvider.LENS
    com.wallet.core.primitives.NameProvider.Basenames -> uniffi.gemstone.NameProvider.BASENAMES
    com.wallet.core.primitives.NameProvider.Hyperliquid -> uniffi.gemstone.NameProvider.HYPERLIQUID
    com.wallet.core.primitives.NameProvider.AllDomains -> uniffi.gemstone.NameProvider.ALL_DOMAINS
    com.wallet.core.primitives.NameProvider.Near -> uniffi.gemstone.NameProvider.NEAR
}

fun uniffi.gemstone.NodeState.toPrimitives(): com.wallet.core.primitives.NodeState = when (this) {
    uniffi.gemstone.NodeState.ACTIVE -> com.wallet.core.primitives.NodeState.Active
    uniffi.gemstone.NodeState.INACTIVE -> com.wallet.core.primitives.NodeState.Inactive
}

fun com.wallet.core.primitives.NodeState.toGem(): uniffi.gemstone.NodeState = when (this) {
    com.wallet.core.primitives.NodeState.Active -> uniffi.gemstone.NodeState.ACTIVE
    com.wallet.core.primitives.NodeState.Inactive -> uniffi.gemstone.NodeState.INACTIVE
}

fun uniffi.gemstone.PerpetualAccountMode.toPrimitives(): com.wallet.core.primitives.PerpetualAccountMode = when (this) {
    uniffi.gemstone.PerpetualAccountMode.STANDARD -> com.wallet.core.primitives.PerpetualAccountMode.Standard
    uniffi.gemstone.PerpetualAccountMode.UNIFIED -> com.wallet.core.primitives.PerpetualAccountMode.Unified
}

fun com.wallet.core.primitives.PerpetualAccountMode.toGem(): uniffi.gemstone.PerpetualAccountMode = when (this) {
    com.wallet.core.primitives.PerpetualAccountMode.Standard -> uniffi.gemstone.PerpetualAccountMode.STANDARD
    com.wallet.core.primitives.PerpetualAccountMode.Unified -> uniffi.gemstone.PerpetualAccountMode.UNIFIED
}

fun uniffi.gemstone.PerpetualDirection.toPrimitives(): com.wallet.core.primitives.PerpetualDirection = when (this) {
    uniffi.gemstone.PerpetualDirection.SHORT -> com.wallet.core.primitives.PerpetualDirection.Short
    uniffi.gemstone.PerpetualDirection.LONG -> com.wallet.core.primitives.PerpetualDirection.Long
}

fun com.wallet.core.primitives.PerpetualDirection.toGem(): uniffi.gemstone.PerpetualDirection = when (this) {
    com.wallet.core.primitives.PerpetualDirection.Short -> uniffi.gemstone.PerpetualDirection.SHORT
    com.wallet.core.primitives.PerpetualDirection.Long -> uniffi.gemstone.PerpetualDirection.LONG
}

fun uniffi.gemstone.PerpetualMarginType.toPrimitives(): com.wallet.core.primitives.PerpetualMarginType = when (this) {
    uniffi.gemstone.PerpetualMarginType.CROSS -> com.wallet.core.primitives.PerpetualMarginType.Cross
    uniffi.gemstone.PerpetualMarginType.ISOLATED -> com.wallet.core.primitives.PerpetualMarginType.Isolated
}

fun com.wallet.core.primitives.PerpetualMarginType.toGem(): uniffi.gemstone.PerpetualMarginType = when (this) {
    com.wallet.core.primitives.PerpetualMarginType.Cross -> uniffi.gemstone.PerpetualMarginType.CROSS
    com.wallet.core.primitives.PerpetualMarginType.Isolated -> uniffi.gemstone.PerpetualMarginType.ISOLATED
}

fun uniffi.gemstone.PerpetualOrderType.toPrimitives(): com.wallet.core.primitives.PerpetualOrderType = when (this) {
    uniffi.gemstone.PerpetualOrderType.MARKET -> com.wallet.core.primitives.PerpetualOrderType.Market
    uniffi.gemstone.PerpetualOrderType.LIMIT -> com.wallet.core.primitives.PerpetualOrderType.Limit
}

fun com.wallet.core.primitives.PerpetualOrderType.toGem(): uniffi.gemstone.PerpetualOrderType = when (this) {
    com.wallet.core.primitives.PerpetualOrderType.Market -> uniffi.gemstone.PerpetualOrderType.MARKET
    com.wallet.core.primitives.PerpetualOrderType.Limit -> uniffi.gemstone.PerpetualOrderType.LIMIT
}

fun uniffi.gemstone.PerpetualProvider.toPrimitives(): com.wallet.core.primitives.PerpetualProvider = when (this) {
    uniffi.gemstone.PerpetualProvider.HYPERCORE -> com.wallet.core.primitives.PerpetualProvider.Hypercore
}

fun com.wallet.core.primitives.PerpetualProvider.toGem(): uniffi.gemstone.PerpetualProvider = when (this) {
    com.wallet.core.primitives.PerpetualProvider.Hypercore -> uniffi.gemstone.PerpetualProvider.HYPERCORE
}

fun uniffi.gemstone.Platform.toPrimitives(): com.wallet.core.primitives.Platform = when (this) {
    uniffi.gemstone.Platform.IOS -> com.wallet.core.primitives.Platform.IOS
    uniffi.gemstone.Platform.ANDROID -> com.wallet.core.primitives.Platform.Android
}

fun com.wallet.core.primitives.Platform.toGem(): uniffi.gemstone.Platform = when (this) {
    com.wallet.core.primitives.Platform.IOS -> uniffi.gemstone.Platform.IOS
    com.wallet.core.primitives.Platform.Android -> uniffi.gemstone.Platform.ANDROID
}

fun uniffi.gemstone.PlatformStore.toPrimitives(): com.wallet.core.primitives.PlatformStore = when (this) {
    uniffi.gemstone.PlatformStore.APP_STORE -> com.wallet.core.primitives.PlatformStore.AppStore
    uniffi.gemstone.PlatformStore.GOOGLE_PLAY -> com.wallet.core.primitives.PlatformStore.GooglePlay
    uniffi.gemstone.PlatformStore.FDROID -> com.wallet.core.primitives.PlatformStore.Fdroid
    uniffi.gemstone.PlatformStore.HUAWEI -> com.wallet.core.primitives.PlatformStore.Huawei
    uniffi.gemstone.PlatformStore.SOLANA_STORE -> com.wallet.core.primitives.PlatformStore.SolanaStore
    uniffi.gemstone.PlatformStore.SAMSUNG_STORE -> com.wallet.core.primitives.PlatformStore.SamsungStore
    uniffi.gemstone.PlatformStore.APK_UNIVERSAL -> com.wallet.core.primitives.PlatformStore.ApkUniversal
    uniffi.gemstone.PlatformStore.EMERALD -> com.wallet.core.primitives.PlatformStore.Emerald
    uniffi.gemstone.PlatformStore.LOCAL -> com.wallet.core.primitives.PlatformStore.Local
}

fun com.wallet.core.primitives.PlatformStore.toGem(): uniffi.gemstone.PlatformStore = when (this) {
    com.wallet.core.primitives.PlatformStore.AppStore -> uniffi.gemstone.PlatformStore.APP_STORE
    com.wallet.core.primitives.PlatformStore.GooglePlay -> uniffi.gemstone.PlatformStore.GOOGLE_PLAY
    com.wallet.core.primitives.PlatformStore.Fdroid -> uniffi.gemstone.PlatformStore.FDROID
    com.wallet.core.primitives.PlatformStore.Huawei -> uniffi.gemstone.PlatformStore.HUAWEI
    com.wallet.core.primitives.PlatformStore.SolanaStore -> uniffi.gemstone.PlatformStore.SOLANA_STORE
    com.wallet.core.primitives.PlatformStore.SamsungStore -> uniffi.gemstone.PlatformStore.SAMSUNG_STORE
    com.wallet.core.primitives.PlatformStore.ApkUniversal -> uniffi.gemstone.PlatformStore.APK_UNIVERSAL
    com.wallet.core.primitives.PlatformStore.Emerald -> uniffi.gemstone.PlatformStore.EMERALD
    com.wallet.core.primitives.PlatformStore.Local -> uniffi.gemstone.PlatformStore.LOCAL
}

fun uniffi.gemstone.PortfolioType.toPrimitives(): com.wallet.core.primitives.PortfolioType = when (this) {
    uniffi.gemstone.PortfolioType.WALLET -> com.wallet.core.primitives.PortfolioType.Wallet
    uniffi.gemstone.PortfolioType.PERPETUALS -> com.wallet.core.primitives.PortfolioType.Perpetuals
}

fun com.wallet.core.primitives.PortfolioType.toGem(): uniffi.gemstone.PortfolioType = when (this) {
    com.wallet.core.primitives.PortfolioType.Wallet -> uniffi.gemstone.PortfolioType.WALLET
    com.wallet.core.primitives.PortfolioType.Perpetuals -> uniffi.gemstone.PortfolioType.PERPETUALS
}

fun uniffi.gemstone.PriceAlertDirection.toPrimitives(): com.wallet.core.primitives.PriceAlertDirection = when (this) {
    uniffi.gemstone.PriceAlertDirection.UP -> com.wallet.core.primitives.PriceAlertDirection.Up
    uniffi.gemstone.PriceAlertDirection.DOWN -> com.wallet.core.primitives.PriceAlertDirection.Down
}

fun com.wallet.core.primitives.PriceAlertDirection.toGem(): uniffi.gemstone.PriceAlertDirection = when (this) {
    com.wallet.core.primitives.PriceAlertDirection.Up -> uniffi.gemstone.PriceAlertDirection.UP
    com.wallet.core.primitives.PriceAlertDirection.Down -> uniffi.gemstone.PriceAlertDirection.DOWN
}

fun uniffi.gemstone.PriceAlertNotificationType.toPrimitives(): com.wallet.core.primitives.PriceAlertNotificationType = when (this) {
    uniffi.gemstone.PriceAlertNotificationType.AUTO -> com.wallet.core.primitives.PriceAlertNotificationType.Auto
    uniffi.gemstone.PriceAlertNotificationType.PRICE -> com.wallet.core.primitives.PriceAlertNotificationType.Price
    uniffi.gemstone.PriceAlertNotificationType.PRICE_PERCENT_CHANGE -> com.wallet.core.primitives.PriceAlertNotificationType.PricePercentChange
}

fun com.wallet.core.primitives.PriceAlertNotificationType.toGem(): uniffi.gemstone.PriceAlertNotificationType = when (this) {
    com.wallet.core.primitives.PriceAlertNotificationType.Auto -> uniffi.gemstone.PriceAlertNotificationType.AUTO
    com.wallet.core.primitives.PriceAlertNotificationType.Price -> uniffi.gemstone.PriceAlertNotificationType.PRICE
    com.wallet.core.primitives.PriceAlertNotificationType.PricePercentChange -> uniffi.gemstone.PriceAlertNotificationType.PRICE_PERCENT_CHANGE
}

fun uniffi.gemstone.RecentActivityType.toPrimitives(): com.wallet.core.primitives.RecentActivityType = when (this) {
    uniffi.gemstone.RecentActivityType.SEARCH -> com.wallet.core.primitives.RecentActivityType.Search
    uniffi.gemstone.RecentActivityType.TRANSFER -> com.wallet.core.primitives.RecentActivityType.Transfer
    uniffi.gemstone.RecentActivityType.RECEIVE -> com.wallet.core.primitives.RecentActivityType.Receive
    uniffi.gemstone.RecentActivityType.FIAT_BUY -> com.wallet.core.primitives.RecentActivityType.FiatBuy
    uniffi.gemstone.RecentActivityType.FIAT_SELL -> com.wallet.core.primitives.RecentActivityType.FiatSell
    uniffi.gemstone.RecentActivityType.SWAP -> com.wallet.core.primitives.RecentActivityType.Swap
    uniffi.gemstone.RecentActivityType.SWAP_SELECT -> com.wallet.core.primitives.RecentActivityType.SwapSelect
    uniffi.gemstone.RecentActivityType.PERPETUAL -> com.wallet.core.primitives.RecentActivityType.Perpetual
}

fun com.wallet.core.primitives.RecentActivityType.toGem(): uniffi.gemstone.RecentActivityType = when (this) {
    com.wallet.core.primitives.RecentActivityType.Search -> uniffi.gemstone.RecentActivityType.SEARCH
    com.wallet.core.primitives.RecentActivityType.Transfer -> uniffi.gemstone.RecentActivityType.TRANSFER
    com.wallet.core.primitives.RecentActivityType.Receive -> uniffi.gemstone.RecentActivityType.RECEIVE
    com.wallet.core.primitives.RecentActivityType.FiatBuy -> uniffi.gemstone.RecentActivityType.FIAT_BUY
    com.wallet.core.primitives.RecentActivityType.FiatSell -> uniffi.gemstone.RecentActivityType.FIAT_SELL
    com.wallet.core.primitives.RecentActivityType.Swap -> uniffi.gemstone.RecentActivityType.SWAP
    com.wallet.core.primitives.RecentActivityType.SwapSelect -> uniffi.gemstone.RecentActivityType.SWAP_SELECT
    com.wallet.core.primitives.RecentActivityType.Perpetual -> uniffi.gemstone.RecentActivityType.PERPETUAL
}

fun uniffi.gemstone.Resource.toPrimitives(): com.wallet.core.primitives.Resource = when (this) {
    uniffi.gemstone.Resource.BANDWIDTH -> com.wallet.core.primitives.Resource.Bandwidth
    uniffi.gemstone.Resource.ENERGY -> com.wallet.core.primitives.Resource.Energy
}

fun com.wallet.core.primitives.Resource.toGem(): uniffi.gemstone.Resource = when (this) {
    com.wallet.core.primitives.Resource.Bandwidth -> uniffi.gemstone.Resource.BANDWIDTH
    com.wallet.core.primitives.Resource.Energy -> uniffi.gemstone.Resource.ENERGY
}

fun uniffi.gemstone.SimulationPayloadFieldDisplay.toPrimitives(): com.wallet.core.primitives.SimulationPayloadFieldDisplay = when (this) {
    uniffi.gemstone.SimulationPayloadFieldDisplay.PRIMARY -> com.wallet.core.primitives.SimulationPayloadFieldDisplay.Primary
    uniffi.gemstone.SimulationPayloadFieldDisplay.SECONDARY -> com.wallet.core.primitives.SimulationPayloadFieldDisplay.Secondary
}

fun com.wallet.core.primitives.SimulationPayloadFieldDisplay.toGem(): uniffi.gemstone.SimulationPayloadFieldDisplay = when (this) {
    com.wallet.core.primitives.SimulationPayloadFieldDisplay.Primary -> uniffi.gemstone.SimulationPayloadFieldDisplay.PRIMARY
    com.wallet.core.primitives.SimulationPayloadFieldDisplay.Secondary -> uniffi.gemstone.SimulationPayloadFieldDisplay.SECONDARY
}

fun uniffi.gemstone.SimulationPayloadFieldKind.toPrimitives(): com.wallet.core.primitives.SimulationPayloadFieldKind = when (this) {
    uniffi.gemstone.SimulationPayloadFieldKind.CONTRACT -> com.wallet.core.primitives.SimulationPayloadFieldKind.Contract
    uniffi.gemstone.SimulationPayloadFieldKind.METHOD -> com.wallet.core.primitives.SimulationPayloadFieldKind.Method
    uniffi.gemstone.SimulationPayloadFieldKind.TOKEN -> com.wallet.core.primitives.SimulationPayloadFieldKind.Token
    uniffi.gemstone.SimulationPayloadFieldKind.SPENDER -> com.wallet.core.primitives.SimulationPayloadFieldKind.Spender
    uniffi.gemstone.SimulationPayloadFieldKind.VALUE -> com.wallet.core.primitives.SimulationPayloadFieldKind.Value
    uniffi.gemstone.SimulationPayloadFieldKind.CUSTOM -> com.wallet.core.primitives.SimulationPayloadFieldKind.Custom
}

fun com.wallet.core.primitives.SimulationPayloadFieldKind.toGem(): uniffi.gemstone.SimulationPayloadFieldKind = when (this) {
    com.wallet.core.primitives.SimulationPayloadFieldKind.Contract -> uniffi.gemstone.SimulationPayloadFieldKind.CONTRACT
    com.wallet.core.primitives.SimulationPayloadFieldKind.Method -> uniffi.gemstone.SimulationPayloadFieldKind.METHOD
    com.wallet.core.primitives.SimulationPayloadFieldKind.Token -> uniffi.gemstone.SimulationPayloadFieldKind.TOKEN
    com.wallet.core.primitives.SimulationPayloadFieldKind.Spender -> uniffi.gemstone.SimulationPayloadFieldKind.SPENDER
    com.wallet.core.primitives.SimulationPayloadFieldKind.Value -> uniffi.gemstone.SimulationPayloadFieldKind.VALUE
    com.wallet.core.primitives.SimulationPayloadFieldKind.Custom -> uniffi.gemstone.SimulationPayloadFieldKind.CUSTOM
}

fun uniffi.gemstone.SimulationPayloadFieldType.toPrimitives(): com.wallet.core.primitives.SimulationPayloadFieldType = when (this) {
    uniffi.gemstone.SimulationPayloadFieldType.TEXT -> com.wallet.core.primitives.SimulationPayloadFieldType.Text
    uniffi.gemstone.SimulationPayloadFieldType.ADDRESS -> com.wallet.core.primitives.SimulationPayloadFieldType.Address
    uniffi.gemstone.SimulationPayloadFieldType.TIMESTAMP -> com.wallet.core.primitives.SimulationPayloadFieldType.Timestamp
}

fun com.wallet.core.primitives.SimulationPayloadFieldType.toGem(): uniffi.gemstone.SimulationPayloadFieldType = when (this) {
    com.wallet.core.primitives.SimulationPayloadFieldType.Text -> uniffi.gemstone.SimulationPayloadFieldType.TEXT
    com.wallet.core.primitives.SimulationPayloadFieldType.Address -> uniffi.gemstone.SimulationPayloadFieldType.ADDRESS
    com.wallet.core.primitives.SimulationPayloadFieldType.Timestamp -> uniffi.gemstone.SimulationPayloadFieldType.TIMESTAMP
}

fun uniffi.gemstone.SolanaTokenProgramId.toPrimitives(): com.wallet.core.primitives.SolanaTokenProgramId = when (this) {
    uniffi.gemstone.SolanaTokenProgramId.TOKEN -> com.wallet.core.primitives.SolanaTokenProgramId.Token
    uniffi.gemstone.SolanaTokenProgramId.TOKEN2022 -> com.wallet.core.primitives.SolanaTokenProgramId.Token2022
}

fun com.wallet.core.primitives.SolanaTokenProgramId.toGem(): uniffi.gemstone.SolanaTokenProgramId = when (this) {
    com.wallet.core.primitives.SolanaTokenProgramId.Token -> uniffi.gemstone.SolanaTokenProgramId.TOKEN
    com.wallet.core.primitives.SolanaTokenProgramId.Token2022 -> uniffi.gemstone.SolanaTokenProgramId.TOKEN2022
}

fun uniffi.gemstone.StakeProviderType.toPrimitives(): com.wallet.core.primitives.StakeProviderType = when (this) {
    uniffi.gemstone.StakeProviderType.STAKE -> com.wallet.core.primitives.StakeProviderType.Stake
    uniffi.gemstone.StakeProviderType.EARN -> com.wallet.core.primitives.StakeProviderType.Earn
}

fun com.wallet.core.primitives.StakeProviderType.toGem(): uniffi.gemstone.StakeProviderType = when (this) {
    com.wallet.core.primitives.StakeProviderType.Stake -> uniffi.gemstone.StakeProviderType.STAKE
    com.wallet.core.primitives.StakeProviderType.Earn -> uniffi.gemstone.StakeProviderType.EARN
}

fun uniffi.gemstone.SwapPriceImpactType.toPrimitives(): com.wallet.core.primitives.swap.SwapPriceImpactType = when (this) {
    uniffi.gemstone.SwapPriceImpactType.POSITIVE -> com.wallet.core.primitives.swap.SwapPriceImpactType.Positive
    uniffi.gemstone.SwapPriceImpactType.LOW -> com.wallet.core.primitives.swap.SwapPriceImpactType.Low
    uniffi.gemstone.SwapPriceImpactType.MEDIUM -> com.wallet.core.primitives.swap.SwapPriceImpactType.Medium
    uniffi.gemstone.SwapPriceImpactType.HIGH -> com.wallet.core.primitives.swap.SwapPriceImpactType.High
}

fun com.wallet.core.primitives.swap.SwapPriceImpactType.toGem(): uniffi.gemstone.SwapPriceImpactType = when (this) {
    com.wallet.core.primitives.swap.SwapPriceImpactType.Positive -> uniffi.gemstone.SwapPriceImpactType.POSITIVE
    com.wallet.core.primitives.swap.SwapPriceImpactType.Low -> uniffi.gemstone.SwapPriceImpactType.LOW
    com.wallet.core.primitives.swap.SwapPriceImpactType.Medium -> uniffi.gemstone.SwapPriceImpactType.MEDIUM
    com.wallet.core.primitives.swap.SwapPriceImpactType.High -> uniffi.gemstone.SwapPriceImpactType.HIGH
}

fun uniffi.gemstone.SwapProvider.toPrimitives(): com.wallet.core.primitives.SwapProvider = when (this) {
    uniffi.gemstone.SwapProvider.UNISWAP_V3 -> com.wallet.core.primitives.SwapProvider.UniswapV3
    uniffi.gemstone.SwapProvider.UNISWAP_V4 -> com.wallet.core.primitives.SwapProvider.UniswapV4
    uniffi.gemstone.SwapProvider.PANCAKESWAP_V3 -> com.wallet.core.primitives.SwapProvider.PancakeswapV3
    uniffi.gemstone.SwapProvider.AERODROME -> com.wallet.core.primitives.SwapProvider.Aerodrome
    uniffi.gemstone.SwapProvider.PANORA -> com.wallet.core.primitives.SwapProvider.Panora
    uniffi.gemstone.SwapProvider.THORCHAIN -> com.wallet.core.primitives.SwapProvider.Thorchain
    uniffi.gemstone.SwapProvider.JUPITER -> com.wallet.core.primitives.SwapProvider.Jupiter
    uniffi.gemstone.SwapProvider.OKX -> com.wallet.core.primitives.SwapProvider.Okx
    uniffi.gemstone.SwapProvider.ACROSS -> com.wallet.core.primitives.SwapProvider.Across
    uniffi.gemstone.SwapProvider.OKU -> com.wallet.core.primitives.SwapProvider.Oku
    uniffi.gemstone.SwapProvider.WAGMI -> com.wallet.core.primitives.SwapProvider.Wagmi
    uniffi.gemstone.SwapProvider.STONFI_V2 -> com.wallet.core.primitives.SwapProvider.StonfiV2
    uniffi.gemstone.SwapProvider.MAYAN -> com.wallet.core.primitives.SwapProvider.Mayan
    uniffi.gemstone.SwapProvider.CHAINFLIP -> com.wallet.core.primitives.SwapProvider.Chainflip
    uniffi.gemstone.SwapProvider.NEAR_INTENTS -> com.wallet.core.primitives.SwapProvider.NearIntents
    uniffi.gemstone.SwapProvider.CETUS_AGGREGATOR -> com.wallet.core.primitives.SwapProvider.CetusAggregator
    uniffi.gemstone.SwapProvider.CETUS_CLMM -> com.wallet.core.primitives.SwapProvider.CetusClmm
    uniffi.gemstone.SwapProvider.RELAY -> com.wallet.core.primitives.SwapProvider.Relay
    uniffi.gemstone.SwapProvider.HYPERLIQUID -> com.wallet.core.primitives.SwapProvider.Hyperliquid
    uniffi.gemstone.SwapProvider.ORCA -> com.wallet.core.primitives.SwapProvider.Orca
    uniffi.gemstone.SwapProvider.SQUID -> com.wallet.core.primitives.SwapProvider.Squid
    uniffi.gemstone.SwapProvider.MAYACHAIN -> com.wallet.core.primitives.SwapProvider.Mayachain
    uniffi.gemstone.SwapProvider.SWAPS_XYZ -> com.wallet.core.primitives.SwapProvider.SwapsXyz
}

fun com.wallet.core.primitives.SwapProvider.toGem(): uniffi.gemstone.SwapProvider = when (this) {
    com.wallet.core.primitives.SwapProvider.UniswapV3 -> uniffi.gemstone.SwapProvider.UNISWAP_V3
    com.wallet.core.primitives.SwapProvider.UniswapV4 -> uniffi.gemstone.SwapProvider.UNISWAP_V4
    com.wallet.core.primitives.SwapProvider.PancakeswapV3 -> uniffi.gemstone.SwapProvider.PANCAKESWAP_V3
    com.wallet.core.primitives.SwapProvider.Aerodrome -> uniffi.gemstone.SwapProvider.AERODROME
    com.wallet.core.primitives.SwapProvider.Panora -> uniffi.gemstone.SwapProvider.PANORA
    com.wallet.core.primitives.SwapProvider.Thorchain -> uniffi.gemstone.SwapProvider.THORCHAIN
    com.wallet.core.primitives.SwapProvider.Jupiter -> uniffi.gemstone.SwapProvider.JUPITER
    com.wallet.core.primitives.SwapProvider.Okx -> uniffi.gemstone.SwapProvider.OKX
    com.wallet.core.primitives.SwapProvider.Across -> uniffi.gemstone.SwapProvider.ACROSS
    com.wallet.core.primitives.SwapProvider.Oku -> uniffi.gemstone.SwapProvider.OKU
    com.wallet.core.primitives.SwapProvider.Wagmi -> uniffi.gemstone.SwapProvider.WAGMI
    com.wallet.core.primitives.SwapProvider.StonfiV2 -> uniffi.gemstone.SwapProvider.STONFI_V2
    com.wallet.core.primitives.SwapProvider.Mayan -> uniffi.gemstone.SwapProvider.MAYAN
    com.wallet.core.primitives.SwapProvider.Chainflip -> uniffi.gemstone.SwapProvider.CHAINFLIP
    com.wallet.core.primitives.SwapProvider.NearIntents -> uniffi.gemstone.SwapProvider.NEAR_INTENTS
    com.wallet.core.primitives.SwapProvider.CetusAggregator -> uniffi.gemstone.SwapProvider.CETUS_AGGREGATOR
    com.wallet.core.primitives.SwapProvider.CetusClmm -> uniffi.gemstone.SwapProvider.CETUS_CLMM
    com.wallet.core.primitives.SwapProvider.Relay -> uniffi.gemstone.SwapProvider.RELAY
    com.wallet.core.primitives.SwapProvider.Hyperliquid -> uniffi.gemstone.SwapProvider.HYPERLIQUID
    com.wallet.core.primitives.SwapProvider.Orca -> uniffi.gemstone.SwapProvider.ORCA
    com.wallet.core.primitives.SwapProvider.Squid -> uniffi.gemstone.SwapProvider.SQUID
    com.wallet.core.primitives.SwapProvider.Mayachain -> uniffi.gemstone.SwapProvider.MAYACHAIN
    com.wallet.core.primitives.SwapProvider.SwapsXyz -> uniffi.gemstone.SwapProvider.SWAPS_XYZ
}

fun uniffi.gemstone.TpslType.toPrimitives(): com.wallet.core.primitives.TpslType = when (this) {
    uniffi.gemstone.TpslType.TAKE_PROFIT -> com.wallet.core.primitives.TpslType.TakeProfit
    uniffi.gemstone.TpslType.STOP_LOSS -> com.wallet.core.primitives.TpslType.StopLoss
}

fun com.wallet.core.primitives.TpslType.toGem(): uniffi.gemstone.TpslType = when (this) {
    com.wallet.core.primitives.TpslType.TakeProfit -> uniffi.gemstone.TpslType.TAKE_PROFIT
    com.wallet.core.primitives.TpslType.StopLoss -> uniffi.gemstone.TpslType.STOP_LOSS
}

fun uniffi.gemstone.TransactionState.toPrimitives(): com.wallet.core.primitives.TransactionState = when (this) {
    uniffi.gemstone.TransactionState.PENDING -> com.wallet.core.primitives.TransactionState.Pending
    uniffi.gemstone.TransactionState.CONFIRMED -> com.wallet.core.primitives.TransactionState.Confirmed
    uniffi.gemstone.TransactionState.IN_TRANSIT -> com.wallet.core.primitives.TransactionState.InTransit
    uniffi.gemstone.TransactionState.FAILED -> com.wallet.core.primitives.TransactionState.Failed
    uniffi.gemstone.TransactionState.REVERTED -> com.wallet.core.primitives.TransactionState.Reverted
    uniffi.gemstone.TransactionState.REFUNDED -> com.wallet.core.primitives.TransactionState.Refunded
}

fun com.wallet.core.primitives.TransactionState.toGem(): uniffi.gemstone.TransactionState = when (this) {
    com.wallet.core.primitives.TransactionState.Pending -> uniffi.gemstone.TransactionState.PENDING
    com.wallet.core.primitives.TransactionState.Confirmed -> uniffi.gemstone.TransactionState.CONFIRMED
    com.wallet.core.primitives.TransactionState.InTransit -> uniffi.gemstone.TransactionState.IN_TRANSIT
    com.wallet.core.primitives.TransactionState.Failed -> uniffi.gemstone.TransactionState.FAILED
    com.wallet.core.primitives.TransactionState.Reverted -> uniffi.gemstone.TransactionState.REVERTED
    com.wallet.core.primitives.TransactionState.Refunded -> uniffi.gemstone.TransactionState.REFUNDED
}

fun uniffi.gemstone.TransactionType.toPrimitives(): com.wallet.core.primitives.TransactionType = when (this) {
    uniffi.gemstone.TransactionType.TRANSFER -> com.wallet.core.primitives.TransactionType.Transfer
    uniffi.gemstone.TransactionType.TRANSFER_NFT -> com.wallet.core.primitives.TransactionType.TransferNFT
    uniffi.gemstone.TransactionType.SWAP -> com.wallet.core.primitives.TransactionType.Swap
    uniffi.gemstone.TransactionType.TOKEN_APPROVAL -> com.wallet.core.primitives.TransactionType.TokenApproval
    uniffi.gemstone.TransactionType.STAKE_DELEGATE -> com.wallet.core.primitives.TransactionType.StakeDelegate
    uniffi.gemstone.TransactionType.STAKE_UNDELEGATE -> com.wallet.core.primitives.TransactionType.StakeUndelegate
    uniffi.gemstone.TransactionType.STAKE_REWARDS -> com.wallet.core.primitives.TransactionType.StakeRewards
    uniffi.gemstone.TransactionType.STAKE_REDELEGATE -> com.wallet.core.primitives.TransactionType.StakeRedelegate
    uniffi.gemstone.TransactionType.STAKE_WITHDRAW -> com.wallet.core.primitives.TransactionType.StakeWithdraw
    uniffi.gemstone.TransactionType.STAKE_FREEZE -> com.wallet.core.primitives.TransactionType.StakeFreeze
    uniffi.gemstone.TransactionType.STAKE_UNFREEZE -> com.wallet.core.primitives.TransactionType.StakeUnfreeze
    uniffi.gemstone.TransactionType.ASSET_ACTIVATION -> com.wallet.core.primitives.TransactionType.AssetActivation
    uniffi.gemstone.TransactionType.SMART_CONTRACT_CALL -> com.wallet.core.primitives.TransactionType.SmartContractCall
    uniffi.gemstone.TransactionType.PERPETUAL_OPEN_POSITION -> com.wallet.core.primitives.TransactionType.PerpetualOpenPosition
    uniffi.gemstone.TransactionType.PERPETUAL_CLOSE_POSITION -> com.wallet.core.primitives.TransactionType.PerpetualClosePosition
    uniffi.gemstone.TransactionType.PERPETUAL_MODIFY_POSITION -> com.wallet.core.primitives.TransactionType.PerpetualModifyPosition
    uniffi.gemstone.TransactionType.EARN_DEPOSIT -> com.wallet.core.primitives.TransactionType.EarnDeposit
    uniffi.gemstone.TransactionType.EARN_WITHDRAW -> com.wallet.core.primitives.TransactionType.EarnWithdraw
}

fun com.wallet.core.primitives.TransactionType.toGem(): uniffi.gemstone.TransactionType = when (this) {
    com.wallet.core.primitives.TransactionType.Transfer -> uniffi.gemstone.TransactionType.TRANSFER
    com.wallet.core.primitives.TransactionType.TransferNFT -> uniffi.gemstone.TransactionType.TRANSFER_NFT
    com.wallet.core.primitives.TransactionType.Swap -> uniffi.gemstone.TransactionType.SWAP
    com.wallet.core.primitives.TransactionType.TokenApproval -> uniffi.gemstone.TransactionType.TOKEN_APPROVAL
    com.wallet.core.primitives.TransactionType.StakeDelegate -> uniffi.gemstone.TransactionType.STAKE_DELEGATE
    com.wallet.core.primitives.TransactionType.StakeUndelegate -> uniffi.gemstone.TransactionType.STAKE_UNDELEGATE
    com.wallet.core.primitives.TransactionType.StakeRewards -> uniffi.gemstone.TransactionType.STAKE_REWARDS
    com.wallet.core.primitives.TransactionType.StakeRedelegate -> uniffi.gemstone.TransactionType.STAKE_REDELEGATE
    com.wallet.core.primitives.TransactionType.StakeWithdraw -> uniffi.gemstone.TransactionType.STAKE_WITHDRAW
    com.wallet.core.primitives.TransactionType.StakeFreeze -> uniffi.gemstone.TransactionType.STAKE_FREEZE
    com.wallet.core.primitives.TransactionType.StakeUnfreeze -> uniffi.gemstone.TransactionType.STAKE_UNFREEZE
    com.wallet.core.primitives.TransactionType.AssetActivation -> uniffi.gemstone.TransactionType.ASSET_ACTIVATION
    com.wallet.core.primitives.TransactionType.SmartContractCall -> uniffi.gemstone.TransactionType.SMART_CONTRACT_CALL
    com.wallet.core.primitives.TransactionType.PerpetualOpenPosition -> uniffi.gemstone.TransactionType.PERPETUAL_OPEN_POSITION
    com.wallet.core.primitives.TransactionType.PerpetualClosePosition -> uniffi.gemstone.TransactionType.PERPETUAL_CLOSE_POSITION
    com.wallet.core.primitives.TransactionType.PerpetualModifyPosition -> uniffi.gemstone.TransactionType.PERPETUAL_MODIFY_POSITION
    com.wallet.core.primitives.TransactionType.EarnDeposit -> uniffi.gemstone.TransactionType.EARN_DEPOSIT
    com.wallet.core.primitives.TransactionType.EarnWithdraw -> uniffi.gemstone.TransactionType.EARN_WITHDRAW
}

fun uniffi.gemstone.TransferDataOutputAction.toPrimitives(): com.wallet.core.primitives.TransferDataOutputAction = when (this) {
    uniffi.gemstone.TransferDataOutputAction.SIGN -> com.wallet.core.primitives.TransferDataOutputAction.Sign
    uniffi.gemstone.TransferDataOutputAction.SEND -> com.wallet.core.primitives.TransferDataOutputAction.Send
}

fun com.wallet.core.primitives.TransferDataOutputAction.toGem(): uniffi.gemstone.TransferDataOutputAction = when (this) {
    com.wallet.core.primitives.TransferDataOutputAction.Sign -> uniffi.gemstone.TransferDataOutputAction.SIGN
    com.wallet.core.primitives.TransferDataOutputAction.Send -> uniffi.gemstone.TransferDataOutputAction.SEND
}

fun uniffi.gemstone.TransferDataOutputType.toPrimitives(): com.wallet.core.primitives.TransferDataOutputType = when (this) {
    uniffi.gemstone.TransferDataOutputType.ENCODED_TRANSACTION -> com.wallet.core.primitives.TransferDataOutputType.EncodedTransaction
    uniffi.gemstone.TransferDataOutputType.SIGNATURE -> com.wallet.core.primitives.TransferDataOutputType.Signature
}

fun com.wallet.core.primitives.TransferDataOutputType.toGem(): uniffi.gemstone.TransferDataOutputType = when (this) {
    com.wallet.core.primitives.TransferDataOutputType.EncodedTransaction -> uniffi.gemstone.TransferDataOutputType.ENCODED_TRANSACTION
    com.wallet.core.primitives.TransferDataOutputType.Signature -> uniffi.gemstone.TransferDataOutputType.SIGNATURE
}

fun uniffi.gemstone.VerificationStatus.toPrimitives(): com.wallet.core.primitives.VerificationStatus = when (this) {
    uniffi.gemstone.VerificationStatus.VERIFIED -> com.wallet.core.primitives.VerificationStatus.Verified
    uniffi.gemstone.VerificationStatus.UNVERIFIED -> com.wallet.core.primitives.VerificationStatus.Unverified
    uniffi.gemstone.VerificationStatus.SUSPICIOUS -> com.wallet.core.primitives.VerificationStatus.Suspicious
}

fun com.wallet.core.primitives.VerificationStatus.toGem(): uniffi.gemstone.VerificationStatus = when (this) {
    com.wallet.core.primitives.VerificationStatus.Verified -> uniffi.gemstone.VerificationStatus.VERIFIED
    com.wallet.core.primitives.VerificationStatus.Unverified -> uniffi.gemstone.VerificationStatus.UNVERIFIED
    com.wallet.core.primitives.VerificationStatus.Suspicious -> uniffi.gemstone.VerificationStatus.SUSPICIOUS
}

fun uniffi.gemstone.WalletConnectionState.toPrimitives(): com.wallet.core.primitives.WalletConnectionState = when (this) {
    uniffi.gemstone.WalletConnectionState.STARTED -> com.wallet.core.primitives.WalletConnectionState.Started
    uniffi.gemstone.WalletConnectionState.ACTIVE -> com.wallet.core.primitives.WalletConnectionState.Active
    uniffi.gemstone.WalletConnectionState.EXPIRED -> com.wallet.core.primitives.WalletConnectionState.Expired
}

fun com.wallet.core.primitives.WalletConnectionState.toGem(): uniffi.gemstone.WalletConnectionState = when (this) {
    com.wallet.core.primitives.WalletConnectionState.Started -> uniffi.gemstone.WalletConnectionState.STARTED
    com.wallet.core.primitives.WalletConnectionState.Active -> uniffi.gemstone.WalletConnectionState.ACTIVE
    com.wallet.core.primitives.WalletConnectionState.Expired -> uniffi.gemstone.WalletConnectionState.EXPIRED
}

fun uniffi.gemstone.WalletConnectionVerificationStatus.toPrimitives(): com.wallet.core.primitives.WalletConnectionVerificationStatus = when (this) {
    uniffi.gemstone.WalletConnectionVerificationStatus.VERIFIED -> com.wallet.core.primitives.WalletConnectionVerificationStatus.Verified
    uniffi.gemstone.WalletConnectionVerificationStatus.UNKNOWN -> com.wallet.core.primitives.WalletConnectionVerificationStatus.Unknown
    uniffi.gemstone.WalletConnectionVerificationStatus.INVALID -> com.wallet.core.primitives.WalletConnectionVerificationStatus.Invalid
    uniffi.gemstone.WalletConnectionVerificationStatus.MALICIOUS -> com.wallet.core.primitives.WalletConnectionVerificationStatus.Malicious
}

fun com.wallet.core.primitives.WalletConnectionVerificationStatus.toGem(): uniffi.gemstone.WalletConnectionVerificationStatus = when (this) {
    com.wallet.core.primitives.WalletConnectionVerificationStatus.Verified -> uniffi.gemstone.WalletConnectionVerificationStatus.VERIFIED
    com.wallet.core.primitives.WalletConnectionVerificationStatus.Unknown -> uniffi.gemstone.WalletConnectionVerificationStatus.UNKNOWN
    com.wallet.core.primitives.WalletConnectionVerificationStatus.Invalid -> uniffi.gemstone.WalletConnectionVerificationStatus.INVALID
    com.wallet.core.primitives.WalletConnectionVerificationStatus.Malicious -> uniffi.gemstone.WalletConnectionVerificationStatus.MALICIOUS
}

fun uniffi.gemstone.WalletSource.toPrimitives(): com.wallet.core.primitives.WalletSource = when (this) {
    uniffi.gemstone.WalletSource.CREATE -> com.wallet.core.primitives.WalletSource.Create
    uniffi.gemstone.WalletSource.IMPORT -> com.wallet.core.primitives.WalletSource.Import
}

fun com.wallet.core.primitives.WalletSource.toGem(): uniffi.gemstone.WalletSource = when (this) {
    com.wallet.core.primitives.WalletSource.Create -> uniffi.gemstone.WalletSource.CREATE
    com.wallet.core.primitives.WalletSource.Import -> uniffi.gemstone.WalletSource.IMPORT
}

fun uniffi.gemstone.WalletType.toPrimitives(): com.wallet.core.primitives.WalletType = when (this) {
    uniffi.gemstone.WalletType.MULTICOIN -> com.wallet.core.primitives.WalletType.Multicoin
    uniffi.gemstone.WalletType.SINGLE -> com.wallet.core.primitives.WalletType.Single
    uniffi.gemstone.WalletType.PRIVATE_KEY -> com.wallet.core.primitives.WalletType.PrivateKey
    uniffi.gemstone.WalletType.VIEW -> com.wallet.core.primitives.WalletType.View
}

fun com.wallet.core.primitives.WalletType.toGem(): uniffi.gemstone.WalletType = when (this) {
    com.wallet.core.primitives.WalletType.Multicoin -> uniffi.gemstone.WalletType.MULTICOIN
    com.wallet.core.primitives.WalletType.Single -> uniffi.gemstone.WalletType.SINGLE
    com.wallet.core.primitives.WalletType.PrivateKey -> uniffi.gemstone.WalletType.PRIVATE_KEY
    com.wallet.core.primitives.WalletType.View -> uniffi.gemstone.WalletType.VIEW
}

fun uniffi.gemstone.Account.toPrimitives(): com.wallet.core.primitives.Account = com.wallet.core.primitives.Account(
    chain = chain.toChain(),
    address = address,
    derivationPath = derivationPath,
    extendedPublicKey = extendedPublicKey,
)

fun com.wallet.core.primitives.Account.toGem(): uniffi.gemstone.Account = uniffi.gemstone.Account(
    chain = chain.toGem(),
    address = address,
    derivationPath = derivationPath,
    extendedPublicKey = extendedPublicKey,
)

fun uniffi.gemstone.AddressName.toPrimitives(): com.wallet.core.primitives.AddressName = com.wallet.core.primitives.AddressName(
    chain = chain.toChain(),
    address = address,
    name = name,
    type = addressType.toPrimitives(),
    status = status.toPrimitives(),
    imageUrl = imageUrl,
)

fun com.wallet.core.primitives.AddressName.toGem(): uniffi.gemstone.AddressName = uniffi.gemstone.AddressName(
    chain = chain.toGem(),
    address = address,
    name = name,
    addressType = type.toGem(),
    status = status.toGem(),
    imageUrl = imageUrl,
)

fun uniffi.gemstone.ApplicationMetadata.toPrimitives(): com.wallet.core.primitives.ApplicationMetadata = com.wallet.core.primitives.ApplicationMetadata(
    name = name,
    description = description,
    url = url,
    icon = icon,
    source = source.toPrimitives(),
)

fun com.wallet.core.primitives.ApplicationMetadata.toGem(): uniffi.gemstone.ApplicationMetadata = uniffi.gemstone.ApplicationMetadata(
    name = name,
    description = description,
    url = url,
    icon = icon,
    source = source.toGem(),
)

fun uniffi.gemstone.Asset.toPrimitives(): com.wallet.core.primitives.Asset = com.wallet.core.primitives.Asset(
    id = com.wallet.core.primitives.AssetId(id),
    name = name,
    symbol = symbol,
    decimals = decimals,
    type = assetType.toPrimitives(),
)

fun com.wallet.core.primitives.Asset.toGem(): uniffi.gemstone.Asset = uniffi.gemstone.Asset(
    id = id.toIdentifier(),
    name = name,
    symbol = symbol,
    decimals = decimals,
    assetType = type.toGem(),
)

fun uniffi.gemstone.AssetFiatValue.toPrimitives(): com.wallet.core.primitives.AssetFiatValue = com.wallet.core.primitives.AssetFiatValue(
    amount = amount,
    price = price,
    priceChangePercentage24h = priceChangePercentage24h,
)

fun com.wallet.core.primitives.AssetFiatValue.toGem(): uniffi.gemstone.AssetFiatValue = uniffi.gemstone.AssetFiatValue(
    amount = amount,
    price = price,
    priceChangePercentage24h = priceChangePercentage24h,
)

fun uniffi.gemstone.AssetLink.toPrimitives(): com.wallet.core.primitives.AssetLink = com.wallet.core.primitives.AssetLink(
    name = name,
    url = url,
)

fun com.wallet.core.primitives.AssetLink.toGem(): uniffi.gemstone.AssetLink = uniffi.gemstone.AssetLink(
    name = name,
    url = url,
)

fun uniffi.gemstone.AssetPrice.toPrimitives(): com.wallet.core.primitives.AssetPrice = com.wallet.core.primitives.AssetPrice(
    assetId = com.wallet.core.primitives.AssetId(assetId),
    price = price,
    priceChangePercentage24h = priceChangePercentage24h,
    updatedAt = updatedAt,
)

fun com.wallet.core.primitives.AssetPrice.toGem(): uniffi.gemstone.AssetPrice = uniffi.gemstone.AssetPrice(
    assetId = assetId.toIdentifier(),
    price = price,
    priceChangePercentage24h = priceChangePercentage24h,
    updatedAt = updatedAt,
)

fun uniffi.gemstone.BalanceMetadata.toPrimitives(): com.wallet.core.primitives.BalanceMetadata = com.wallet.core.primitives.BalanceMetadata(
    votes = votes,
    energyAvailable = energyAvailable,
    energyTotal = energyTotal,
    bandwidthAvailable = bandwidthAvailable,
    bandwidthTotal = bandwidthTotal,
)

fun com.wallet.core.primitives.BalanceMetadata.toGem(): uniffi.gemstone.BalanceMetadata = uniffi.gemstone.BalanceMetadata(
    votes = votes,
    energyAvailable = energyAvailable,
    energyTotal = energyTotal,
    bandwidthAvailable = bandwidthAvailable,
    bandwidthTotal = bandwidthTotal,
)

fun uniffi.gemstone.BlockExplorerLink.toPrimitives(): com.wallet.core.primitives.BlockExplorerLink = com.wallet.core.primitives.BlockExplorerLink(
    name = name,
    link = link,
)

fun com.wallet.core.primitives.BlockExplorerLink.toGem(): uniffi.gemstone.BlockExplorerLink = uniffi.gemstone.BlockExplorerLink(
    name = name,
    link = link,
)

fun uniffi.gemstone.ChainAddress.toPrimitives(): com.wallet.core.primitives.ChainAddress = com.wallet.core.primitives.ChainAddress(
    chain = chain.toChain(),
    address = address,
)

fun com.wallet.core.primitives.ChainAddress.toGem(): uniffi.gemstone.ChainAddress = uniffi.gemstone.ChainAddress(
    chain = chain.toGem(),
    address = address,
)

fun uniffi.gemstone.ChartCandleStick.toPrimitives(): com.wallet.core.primitives.ChartCandleStick = com.wallet.core.primitives.ChartCandleStick(
    date = date,
    open = open,
    high = high,
    low = low,
    close = close,
    volume = volume,
)

fun com.wallet.core.primitives.ChartCandleStick.toGem(): uniffi.gemstone.ChartCandleStick = uniffi.gemstone.ChartCandleStick(
    date = date,
    open = open,
    high = high,
    low = low,
    close = close,
    volume = volume,
)

fun uniffi.gemstone.ChartCandleUpdate.toPrimitives(): com.wallet.core.primitives.ChartCandleUpdate = com.wallet.core.primitives.ChartCandleUpdate(
    coin = coin,
    interval = interval,
    candle = candle.toPrimitives(),
)

fun com.wallet.core.primitives.ChartCandleUpdate.toGem(): uniffi.gemstone.ChartCandleUpdate = uniffi.gemstone.ChartCandleUpdate(
    coin = coin,
    interval = interval,
    candle = candle.toGem(),
)

fun uniffi.gemstone.ChartDateValue.toPrimitives(): com.wallet.core.primitives.ChartDateValue = com.wallet.core.primitives.ChartDateValue(
    date = date,
    value = value,
)

fun com.wallet.core.primitives.ChartDateValue.toGem(): uniffi.gemstone.ChartDateValue = uniffi.gemstone.ChartDateValue(
    date = date,
    value = value,
)

fun uniffi.gemstone.Contact.toPrimitives(): com.wallet.core.primitives.Contact = com.wallet.core.primitives.Contact(
    id = id,
    name = name,
    description = description,
    imageUrl = imageUrl,
    createdAt = createdAt,
    updatedAt = updatedAt,
)

fun com.wallet.core.primitives.Contact.toGem(): uniffi.gemstone.Contact = uniffi.gemstone.Contact(
    id = id,
    name = name,
    description = description,
    imageUrl = imageUrl,
    createdAt = createdAt,
    updatedAt = updatedAt,
)

fun uniffi.gemstone.ContactAddress.toPrimitives(): com.wallet.core.primitives.ContactAddress = com.wallet.core.primitives.ContactAddress(
    id = id,
    contactId = contactId,
    address = address,
    chain = chain.toChain(),
    memo = memo,
)

fun com.wallet.core.primitives.ContactAddress.toGem(): uniffi.gemstone.ContactAddress = uniffi.gemstone.ContactAddress(
    id = id,
    contactId = contactId,
    address = address,
    chain = chain.toGem(),
    memo = memo,
)

fun uniffi.gemstone.DelegationValidator.toPrimitives(): com.wallet.core.primitives.DelegationValidator = com.wallet.core.primitives.DelegationValidator(
    chain = chain.toChain(),
    id = id,
    name = name,
    isActive = isActive,
    commission = commission,
    apr = apr,
    providerType = providerType.toPrimitives(),
)

fun com.wallet.core.primitives.DelegationValidator.toGem(): uniffi.gemstone.DelegationValidator = uniffi.gemstone.DelegationValidator(
    chain = chain.toGem(),
    id = id,
    name = name,
    isActive = isActive,
    commission = commission,
    apr = apr,
    providerType = providerType.toGem(),
)

fun uniffi.gemstone.FiatRate.toPrimitives(): com.wallet.core.primitives.FiatRate = com.wallet.core.primitives.FiatRate(
    symbol = symbol.toCurrency(),
    rate = rate,
)

fun com.wallet.core.primitives.FiatRate.toGem(): uniffi.gemstone.FiatRate = uniffi.gemstone.FiatRate(
    symbol = symbol.toGem(),
    rate = rate,
)

fun uniffi.gemstone.Latency.toPrimitives(): com.wallet.core.primitives.Latency = com.wallet.core.primitives.Latency(
    latencyType = latencyType.toPrimitives(),
    value = value,
)

fun com.wallet.core.primitives.Latency.toGem(): uniffi.gemstone.Latency = uniffi.gemstone.Latency(
    latencyType = latencyType.toGem(),
    value = value,
)

fun uniffi.gemstone.NameRecord.toPrimitives(): com.wallet.core.primitives.NameRecord = com.wallet.core.primitives.NameRecord(
    name = name,
    chain = chain.toChain(),
    address = address,
    provider = provider.toPrimitives(),
)

fun com.wallet.core.primitives.NameRecord.toGem(): uniffi.gemstone.NameRecord = uniffi.gemstone.NameRecord(
    name = name,
    chain = chain.toGem(),
    address = address,
    provider = provider.toGem(),
)

fun uniffi.gemstone.Node.toPrimitives(): com.wallet.core.primitives.Node = com.wallet.core.primitives.Node(
    url = url,
    status = status.toPrimitives(),
    priority = priority,
)

fun com.wallet.core.primitives.Node.toGem(): uniffi.gemstone.Node = uniffi.gemstone.Node(
    url = url,
    status = status.toGem(),
    priority = priority,
)

fun uniffi.gemstone.Perpetual.toPrimitives(): com.wallet.core.primitives.Perpetual = com.wallet.core.primitives.Perpetual(
    id = com.wallet.core.primitives.PerpetualId(id),
    name = name,
    provider = provider.toPrimitives(),
    assetId = com.wallet.core.primitives.AssetId(assetId),
    identifier = identifier,
    price = price,
    pricePercentChange24h = pricePercentChange24h,
    openInterest = openInterest,
    volume24h = volume24h,
    funding = funding,
    maxLeverage = maxLeverage,
    isIsolatedOnly = isIsolatedOnly,
)

fun com.wallet.core.primitives.Perpetual.toGem(): uniffi.gemstone.Perpetual = uniffi.gemstone.Perpetual(
    id = id.toIdentifier(),
    name = name,
    provider = provider.toGem(),
    assetId = assetId.toIdentifier(),
    identifier = identifier,
    price = price,
    pricePercentChange24h = pricePercentChange24h,
    openInterest = openInterest,
    volume24h = volume24h,
    funding = funding,
    maxLeverage = maxLeverage,
    isIsolatedOnly = isIsolatedOnly,
)

fun uniffi.gemstone.PerpetualBalance.toPrimitives(): com.wallet.core.primitives.PerpetualBalance = com.wallet.core.primitives.PerpetualBalance(
    available = available,
    reserved = reserved,
    withdrawable = withdrawable,
)

fun com.wallet.core.primitives.PerpetualBalance.toGem(): uniffi.gemstone.PerpetualBalance = uniffi.gemstone.PerpetualBalance(
    available = available,
    reserved = reserved,
    withdrawable = withdrawable,
)

fun uniffi.gemstone.PerpetualData.toPrimitives(): com.wallet.core.primitives.PerpetualData = com.wallet.core.primitives.PerpetualData(
    perpetual = perpetual.toPrimitives(),
    asset = asset.toPrimitives(),
    metadata = metadata.toPrimitives(),
)

fun com.wallet.core.primitives.PerpetualData.toGem(): uniffi.gemstone.PerpetualData = uniffi.gemstone.PerpetualData(
    perpetual = perpetual.toGem(),
    asset = asset.toGem(),
    metadata = metadata.toGem(),
)

fun uniffi.gemstone.PerpetualMarketData.toPrimitives(): com.wallet.core.primitives.PerpetualMarketData = com.wallet.core.primitives.PerpetualMarketData(
    coin = coin,
    price = price,
    pricePercentChange24h = pricePercentChange24h,
    openInterest = openInterest,
    volume24h = volume24h,
    funding = funding,
)

fun com.wallet.core.primitives.PerpetualMarketData.toGem(): uniffi.gemstone.PerpetualMarketData = uniffi.gemstone.PerpetualMarketData(
    coin = coin,
    price = price,
    pricePercentChange24h = pricePercentChange24h,
    openInterest = openInterest,
    volume24h = volume24h,
    funding = funding,
)

fun uniffi.gemstone.PerpetualMetadata.toPrimitives(): com.wallet.core.primitives.PerpetualMetadata = com.wallet.core.primitives.PerpetualMetadata(
    isPinned = isPinned,
)

fun com.wallet.core.primitives.PerpetualMetadata.toGem(): uniffi.gemstone.PerpetualMetadata = uniffi.gemstone.PerpetualMetadata(
    isPinned = isPinned,
)

fun uniffi.gemstone.PerpetualPosition.toPrimitives(): com.wallet.core.primitives.PerpetualPosition = com.wallet.core.primitives.PerpetualPosition(
    id = id,
    perpetualId = com.wallet.core.primitives.PerpetualId(perpetualId),
    assetId = com.wallet.core.primitives.AssetId(assetId),
    size = size,
    sizeValue = sizeValue,
    leverage = leverage,
    entryPrice = entryPrice,
    liquidationPrice = liquidationPrice,
    marginType = marginType.toPrimitives(),
    direction = direction.toPrimitives(),
    marginAmount = marginAmount,
    takeProfit = takeProfit?.let { it.toPrimitives() },
    stopLoss = stopLoss?.let { it.toPrimitives() },
    pnl = pnl,
    funding = funding,
)

fun com.wallet.core.primitives.PerpetualPosition.toGem(): uniffi.gemstone.PerpetualPosition = uniffi.gemstone.PerpetualPosition(
    id = id,
    perpetualId = perpetualId.toIdentifier(),
    assetId = assetId.toIdentifier(),
    size = size,
    sizeValue = sizeValue,
    leverage = leverage,
    entryPrice = entryPrice,
    liquidationPrice = liquidationPrice,
    marginType = marginType.toGem(),
    direction = direction.toGem(),
    marginAmount = marginAmount,
    takeProfit = takeProfit?.let { it.toGem() },
    stopLoss = stopLoss?.let { it.toGem() },
    pnl = pnl,
    funding = funding,
)

fun uniffi.gemstone.PerpetualPositionsSummary.toPrimitives(): com.wallet.core.primitives.PerpetualPositionsSummary = com.wallet.core.primitives.PerpetualPositionsSummary(
    positions = positions.map { it.toPrimitives() },
    balance = balance.toPrimitives(),
)

fun com.wallet.core.primitives.PerpetualPositionsSummary.toGem(): uniffi.gemstone.PerpetualPositionsSummary = uniffi.gemstone.PerpetualPositionsSummary(
    positions = positions.map { it.toGem() },
    balance = balance.toGem(),
)

fun uniffi.gemstone.PerpetualTriggerOrder.toPrimitives(): com.wallet.core.primitives.PerpetualTriggerOrder = com.wallet.core.primitives.PerpetualTriggerOrder(
    price = price,
    order_type = orderType.toPrimitives(),
    order_id = orderId,
)

fun com.wallet.core.primitives.PerpetualTriggerOrder.toGem(): uniffi.gemstone.PerpetualTriggerOrder = uniffi.gemstone.PerpetualTriggerOrder(
    price = price,
    orderType = order_type.toGem(),
    orderId = order_id,
)

fun uniffi.gemstone.PriceAlert.toPrimitives(): com.wallet.core.primitives.PriceAlert = com.wallet.core.primitives.PriceAlert(
    assetId = com.wallet.core.primitives.AssetId(assetId),
    currency = currency.toCurrency(),
    price = price,
    pricePercentChange = pricePercentChange,
    priceDirection = priceDirection?.let { it.toPrimitives() },
    lastNotifiedAt = lastNotifiedAt,
)

fun com.wallet.core.primitives.PriceAlert.toGem(): uniffi.gemstone.PriceAlert = uniffi.gemstone.PriceAlert(
    assetId = assetId.toIdentifier(),
    currency = currency.toGem(),
    price = price,
    pricePercentChange = pricePercentChange,
    priceDirection = priceDirection?.let { it.toGem() },
    lastNotifiedAt = lastNotifiedAt,
    identifier = "",
)

fun uniffi.gemstone.Release.toPrimitives(): com.wallet.core.primitives.Release = com.wallet.core.primitives.Release(
    version = version,
    store = store.toPrimitives(),
    upgradeRequired = upgradeRequired,
)

fun com.wallet.core.primitives.Release.toGem(): uniffi.gemstone.Release = uniffi.gemstone.Release(
    version = version,
    store = store.toGem(),
    upgradeRequired = upgradeRequired,
)

fun uniffi.gemstone.ReportNft.toPrimitives(): com.wallet.core.primitives.ReportNft = com.wallet.core.primitives.ReportNft(
    collectionId = collectionId,
    assetId = assetId,
    reason = reason,
)

fun com.wallet.core.primitives.ReportNft.toGem(): uniffi.gemstone.ReportNft = uniffi.gemstone.ReportNft(
    collectionId = collectionId,
    assetId = assetId,
    reason = reason,
)

fun uniffi.gemstone.SimulationPayloadField.toPrimitives(): com.wallet.core.primitives.SimulationPayloadField = com.wallet.core.primitives.SimulationPayloadField(
    kind = kind.toPrimitives(),
    label = label,
    value = value,
    fieldType = fieldType.toPrimitives(),
    display = display.toPrimitives(),
)

fun com.wallet.core.primitives.SimulationPayloadField.toGem(): uniffi.gemstone.SimulationPayloadField = uniffi.gemstone.SimulationPayloadField(
    kind = kind.toGem(),
    label = label,
    value = value,
    fieldType = fieldType.toGem(),
    display = display.toGem(),
)

fun uniffi.gemstone.SwapPriceImpact.toPrimitives(): com.wallet.core.primitives.swap.SwapPriceImpact = com.wallet.core.primitives.swap.SwapPriceImpact(
    percentage = percentage,
    impactType = impactType.toPrimitives(),
    isHigh = isHigh,
)

fun com.wallet.core.primitives.swap.SwapPriceImpact.toGem(): uniffi.gemstone.SwapPriceImpact = uniffi.gemstone.SwapPriceImpact(
    percentage = percentage,
    impactType = impactType.toGem(),
    isHigh = isHigh,
)

fun uniffi.gemstone.TotalFiatValue.toPrimitives(): com.wallet.core.primitives.TotalFiatValue = com.wallet.core.primitives.TotalFiatValue(
    value = value,
    pnlAmount = pnlAmount,
    pnlPercentage = pnlPercentage,
)

fun com.wallet.core.primitives.TotalFiatValue.toGem(): uniffi.gemstone.TotalFiatValue = uniffi.gemstone.TotalFiatValue(
    value = value,
    pnlAmount = pnlAmount,
    pnlPercentage = pnlPercentage,
)

fun uniffi.gemstone.Wallet.toPrimitives(): com.wallet.core.primitives.Wallet = com.wallet.core.primitives.Wallet(
    id = com.wallet.core.primitives.WalletId(id),
    externalId = externalId,
    name = name,
    index = index,
    type = walletType.toPrimitives(),
    accounts = accounts.map { it.toPrimitives() },
    isPinned = isPinned,
    imageUrl = imageUrl,
    source = source.toPrimitives(),
)

fun com.wallet.core.primitives.Wallet.toGem(): uniffi.gemstone.Wallet = uniffi.gemstone.Wallet(
    id = id.toIdentifier(),
    externalId = externalId,
    name = name,
    index = index,
    walletType = type.toGem(),
    accounts = accounts.map { it.toGem() },
    isPinned = isPinned,
    imageUrl = imageUrl,
    source = source.toGem(),
)

fun uniffi.gemstone.WalletConnection.toPrimitives(): com.wallet.core.primitives.WalletConnection = com.wallet.core.primitives.WalletConnection(
    session = session.toPrimitives(),
    wallet = wallet.toPrimitives(),
)

fun com.wallet.core.primitives.WalletConnection.toGem(): uniffi.gemstone.WalletConnection = uniffi.gemstone.WalletConnection(
    session = session.toGem(),
    wallet = wallet.toGem(),
)

fun uniffi.gemstone.WalletConnectionSession.toPrimitives(): com.wallet.core.primitives.WalletConnectionSession = com.wallet.core.primitives.WalletConnectionSession(
    id = id,
    sessionId = sessionId,
    state = state.toPrimitives(),
    chains = chains.map { it.toChain() },
    createdAt = createdAt,
    expireAt = expireAt,
    metadata = metadata.toPrimitives(),
)

fun com.wallet.core.primitives.WalletConnectionSession.toGem(): uniffi.gemstone.WalletConnectionSession = uniffi.gemstone.WalletConnectionSession(
    id = id,
    sessionId = sessionId,
    state = state.toGem(),
    chains = chains.map { it.toGem() },
    createdAt = createdAt,
    expireAt = expireAt,
    metadata = metadata.toGem(),
)

fun uniffi.gemstone.WalletConnectionSessionProposal.toPrimitives(): com.wallet.core.primitives.WalletConnectionSessionProposal = com.wallet.core.primitives.WalletConnectionSessionProposal(
    defaultWallet = defaultWallet.toPrimitives(),
    wallets = wallets.map { it.toPrimitives() },
    metadata = metadata.toPrimitives(),
)

fun com.wallet.core.primitives.WalletConnectionSessionProposal.toGem(): uniffi.gemstone.WalletConnectionSessionProposal = uniffi.gemstone.WalletConnectionSessionProposal(
    defaultWallet = defaultWallet.toGem(),
    wallets = wallets.map { it.toGem() },
    metadata = metadata.toGem(),
)
