[package]
name = "yielder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
num-bigint = { workspace = true }
gem_evm = { path = "../gem_evm", features = ["rpc"] }
gem_jsonrpc = { path = "../gem_jsonrpc" }
primitives = { path = "../primitives" }
async-trait = { workspace = true }
futures = { workspace = true }
