// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "FeatureServices",
    platforms: [
        .iOS(.v17),
        .macOS(.v15),
    ],
    products: [
        .library(name: "StreamService", targets: ["StreamService"]),
        .library(name: "StreamServiceTestKit", targets: ["StreamServiceTestKit"]),
        .library(name: "AppService", targets: ["AppService"]),
        .library(name: "AppServiceTestKit", targets: ["AppServiceTestKit"]),
        .library(name: "ConnectionStatusService", targets: ["ConnectionStatusService"]),
        .library(name: "ConnectionsService", targets: ["ConnectionsService"]),
        .library(name: "ConnectionsServiceTestKit", targets: ["ConnectionsServiceTestKit"]),
    ],
    dependencies: [
        .package(name: "Primitives", path: "../Primitives"),
        .package(name: "GemstoneServices", path: "../GemstoneServices"),
        .package(name: "Store", path: "../Store"),
        .package(name: "ChainServices", path: "../ChainServices"),
        .package(name: "GemAPI", path: "../GemAPI"),
        .package(name: "Preferences", path: "../Preferences"),
        .package(name: "GemstonePrimitives", path: "../GemstonePrimitives"),
        .package(name: "Gemstone", path: "../Gemstone"),
        .package(name: "Keystore", path: "../Keystore"),
        .package(name: "SwiftHTTPClient", path: "../SwiftHTTPClient"),
        .package(name: "NativeProviderService", path: "../NativeProviderService"),
        .package(name: "SystemServices", path: "../SystemServices"),
    ],
    targets: [
        .target(
            name: "StreamService",
            dependencies: [
                "Primitives",
                "Store",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                "Preferences",
                .product(name: "WebSocketClient", package: "SwiftHTTPClient"),
            ],
            path: "StreamService",
            exclude: ["TestKit", "Tests"],
        ),
        .target(
            name: "StreamServiceTestKit",
            dependencies: [
                "StreamService",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "WebSocketClientTestKit", package: "SwiftHTTPClient"),
                .product(name: "GemstonePrimitivesTestKit", package: "GemstonePrimitives"),
            ],
            path: "StreamService/TestKit",
        ),
        .target(
            name: "AppService",
            dependencies: [
                "Primitives",
                "Store",
                "GemAPI",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                "GemstonePrimitives",
                "Preferences",
                "StreamService",
                "ConnectionsService",
                "ConnectionStatusService",
                "Gemstone",
            ],
            path: "AppService",
            exclude: ["Tests", "TestKit"],
        ),
        .target(
            name: "AppServiceTestKit",
            dependencies: [
                .product(name: "GemstonePrimitivesTestKit", package: "GemstonePrimitives"),
                "AppService",
                "Primitives",
                .product(name: "GemAPITestKit", package: "GemAPI"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                "StreamServiceTestKit",
                "ConnectionsServiceTestKit",
                "ConnectionStatusService",
                .product(name: "ConnectivityService", package: "SystemServices"),
                .product(name: "ConnectivityServiceTestKit", package: "SystemServices"),
            ],
            path: "AppService/TestKit",
        ),
        .target(
            name: "ConnectionStatusService",
            dependencies: [
                "Primitives",
                "GemstonePrimitives",
                .product(name: "ConnectivityService", package: "SystemServices"),
            ],
            path: "ConnectionStatusService",
            exclude: ["Tests"],
        ),
        .testTarget(
            name: "ConnectionStatusServiceTests",
            dependencies: [
                "ConnectionStatusService",
                .product(name: "ConnectivityService", package: "SystemServices"),
            ],
            path: "ConnectionStatusService/Tests",
        ),
        .target(
            name: "ConnectionsService",
            dependencies: [
                "Primitives",
                "Store",
                "Preferences",
                .product(name: "WalletConnectorService", package: "ChainServices"),
            ],
            path: "ConnectionsService",
            exclude: ["TestKit"],
        ),
        .target(
            name: "ConnectionsServiceTestKit",
            dependencies: [
                "ConnectionsService",
                "Primitives",
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "WalletConnectorServiceTestKit", package: "ChainServices"),
            ],
            path: "ConnectionsService/TestKit",
        ),
        .testTarget(
            name: "StreamServiceTests",
            dependencies: [
                "StreamService",
                "StreamServiceTestKit",
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                "Gemstone",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                .product(name: "PrimitivesTestKit", package: "Primitives"),
                .product(name: "WebSocketClientTestKit", package: "SwiftHTTPClient"),
            ],
            path: "StreamService/Tests",
        ),
        .testTarget(
            name: "AppServiceTests",
            dependencies: [
                "AppService",
                "AppServiceTestKit",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                .product(name: "GemAPITestKit", package: "GemAPI"),
                .product(name: "PrimitivesTestKit", package: "Primitives"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                "Store",
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "GemstonePrimitivesTestKit", package: "GemstonePrimitives"),
            ],
            path: "AppService/Tests",
        ),
    ],
)
