// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "FeatureServices",
    platforms: [
        .iOS(.v17),
        .macOS(.v15),
    ],
    products: [
        .library(name: "PerpetualService", targets: ["PerpetualService"]),
        .library(name: "PerpetualServiceTestKit", targets: ["PerpetualServiceTestKit"]),
        .library(name: "BalanceService", targets: ["BalanceService"]),
        .library(name: "BalanceServiceTestKit", targets: ["BalanceServiceTestKit"]),
        .library(name: "AvatarService", targets: ["AvatarService"]),
        .library(name: "StreamService", targets: ["StreamService"]),
        .library(name: "StreamServiceTestKit", targets: ["StreamServiceTestKit"]),
        .library(name: "TransactionStateService", targets: ["TransactionStateService"]),
        .library(name: "TransactionStateServiceTestKit", targets: ["TransactionStateServiceTestKit"]),
        .library(name: "SwapService", targets: ["SwapService"]),
        .library(name: "SwapServiceTestKit", targets: ["SwapServiceTestKit"]),
        .library(name: "WalletSessionService", targets: ["WalletSessionService"]),
        .library(name: "WalletSessionServiceTestKit", targets: ["WalletSessionServiceTestKit"]),
        .library(name: "WalletService", targets: ["WalletService"]),
        .library(name: "WalletServiceTestKit", targets: ["WalletServiceTestKit"]),
        .library(name: "AppService", targets: ["AppService"]),
        .library(name: "AppServiceTestKit", targets: ["AppServiceTestKit"]),
        .library(name: "ConnectionStatusService", targets: ["ConnectionStatusService"]),
        .library(name: "ServiceStatusService", targets: ["ServiceStatusService"]),
        .library(name: "ActivityService", targets: ["ActivityService"]),
        .library(name: "ActivityServiceTestKit", targets: ["ActivityServiceTestKit"]),
        .library(name: "ConnectionsService", targets: ["ConnectionsService"]),
        .library(name: "ConnectionsServiceTestKit", targets: ["ConnectionsServiceTestKit"]),
        .library(name: "EarnService", targets: ["EarnService"]),
        .library(name: "EarnServiceTestKit", targets: ["EarnServiceTestKit"]),
    ],
    dependencies: [
        .package(name: "Primitives", path: "../Primitives"),
        .package(name: "GemstoneStore", path: "../GemstoneStore"),
        .package(name: "GemstoneServices", path: "../GemstoneServices"),
        .package(name: "Store", path: "../Store"),
        .package(name: "Blockchain", path: "../Blockchain"),
        .package(name: "ChainServices", path: "../ChainServices"),
        .package(name: "GemAPI", path: "../GemAPI"),
        .package(name: "Preferences", path: "../Preferences"),
        .package(name: "GemstonePrimitives", path: "../GemstonePrimitives"),
        .package(name: "Gemstone", path: "../Gemstone"),
        .package(name: "Signer", path: "../Signer"),
        .package(name: "Keystore", path: "../Keystore"),
        .package(name: "Formatters", path: "../Formatters"),
        .package(name: "SwiftHTTPClient", path: "../SwiftHTTPClient"),
        .package(name: "NativeProviderService", path: "../NativeProviderService"),
        .package(name: "SystemServices", path: "../SystemServices"),
    ],
    targets: [
        .target(
            name: "PerpetualService",
            dependencies: [
                "GemstoneStore",
                "Gemstone",
                "Primitives",
                "GemstonePrimitives",
                "Store",
                "Blockchain",
                "Formatters",
                "Preferences",
                .product(name: "ChainService", package: "ChainServices"),
                .product(name: "WebSocketClient", package: "SwiftHTTPClient"),
            ],
            path: "PerpetualService",
            exclude: ["Tests", "TestKit"],
        ),
        .target(
            name: "PerpetualServiceTestKit",
            dependencies: [
                "GemstoneStore",
                .product(name: "GemstonePrimitivesTestKit", package: "GemstonePrimitives"),
                .product(name: "BlockchainTestKit", package: "Blockchain"),
                "Blockchain",
                "Gemstone",
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                "PerpetualService",
                "Primitives",
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
            ],
            path: "PerpetualService/TestKit",
        ),
        .testTarget(
            name: "PerpetualServiceTests",
            dependencies: [
                "PerpetualService",
                "Primitives",
                .product(name: "WebSocketClientTestKit", package: "SwiftHTTPClient"),
            ],
            path: "PerpetualService/Tests",
        ),
        .target(
            name: "BalanceService",
            dependencies: [
                "Gemstone",
                .product(name: "GemstonePrimitivesTestKit", package: "GemstonePrimitives"),
                "Primitives",
                "Store",
                .product(name: "ChainService", package: "ChainServices"),
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                "Formatters",
            ],
            path: "BalanceService",
            exclude: ["TestKit", "Tests"],
        ),
        .target(
            name: "BalanceServiceTestKit",
            dependencies: [
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "ChainServiceTestKit", package: "ChainServices"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                "BalanceService",
                "Primitives",
            ],
            path: "BalanceService/TestKit",
        ),
        .target(
            name: "AvatarService",
            dependencies: [
                "Primitives",
                "Store",
                .product(name: "LocalStore", package: "SystemServices"),
            ],
            path: "AvatarService",
            exclude: ["TestKit"],
        ),
        .target(
            name: "StreamService",
            dependencies: [
                "Primitives",
                "Store",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                "GemAPI",
                .product(name: "GemAPIDevice", package: "GemAPI"),
                "Preferences",
                "WalletSessionService",
                .product(name: "WebSocketClient", package: "SwiftHTTPClient"),
            ],
            path: "StreamService",
            exclude: ["TestKit", "Tests"],
        ),
        .target(
            name: "StreamServiceTestKit",
            dependencies: [
                "StreamService",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                .product(name: "StoreTestKit", package: "Store"),
                "WalletSessionServiceTestKit",
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "WebSocketClientTestKit", package: "SwiftHTTPClient"),
                .product(name: "GemstonePrimitivesTestKit", package: "GemstonePrimitives"),
            ],
            path: "StreamService/TestKit",
        ),
        .target(
            name: "TransactionStateService",
            dependencies: [
                "Primitives",
                "Store",
                "Blockchain",
                "Gemstone",
                .product(name: "StakeService", package: "ChainServices"),
                "BalanceService",
                "EarnService",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                "GemstonePrimitives",
            ],
            path: "TransactionStateService",
            exclude: ["Tests", "TestKit"],
        ),
        .target(
            name: "TransactionStateServiceTestKit",
            dependencies: [
                "GemstoneStore",
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "StakeServiceTestKit", package: "ChainServices"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "BlockchainTestKit", package: "Blockchain"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                "BalanceServiceTestKit",
                "EarnService",
                "EarnServiceTestKit",
                "Blockchain",
                "TransactionStateService",
            ],
            path: "TransactionStateService/TestKit",
        ),
        .target(
            name: "SwapService",
            dependencies: [
                "Gemstone",
                "GemstonePrimitives",
                "Primitives",
                .product(name: "ChainService", package: "ChainServices"),
                "Signer",
                "Keystore",
                "NativeProviderService",
            ],
            path: "SwapService",
            exclude: ["TestKit"],
        ),
        .target(
            name: "SwapServiceTestKit",
            dependencies: [
                .product(name: "ChainServiceTestKit", package: "ChainServices"),
                "SwapService",
                "Gemstone",
            ],
            path: "SwapService/TestKit",
        ),
        .target(
            name: "WalletSessionService",
            dependencies: [
                "Primitives",
                "Store",
                "Preferences",
            ],
            path: "WalletSessionService",
            exclude: ["TestKit", "Tests"],
        ),
        .target(
            name: "WalletSessionServiceTestKit",
            dependencies: [
                "WalletSessionService",
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "StoreTestKit", package: "Store"),
            ],
            path: "WalletSessionService/TestKit",
        ),
        .target(
            name: "WalletService",
            dependencies: [
                "Primitives",
                "Keystore",
                "Store",
                "Preferences",
                "GemstonePrimitives",
                "AvatarService",
                "WalletSessionService",
                "BalanceService",
            ],
            path: "WalletService",
            exclude: ["TestKit", "Tests"],
        ),
        .target(
            name: "WalletServiceTestKit",
            dependencies: [
                .product(name: "KeystoreTestKit", package: "Keystore"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "StoreTestKit", package: "Store"),
                "BalanceServiceTestKit",
                "WalletService",
                "WalletSessionService",
                "WalletSessionServiceTestKit",
            ],
            path: "WalletService/TestKit",
        ),
        .target(
            name: "AppService",
            dependencies: [
                "Primitives",
                "Store",
                "GemAPI",
                .product(name: "NodeService", package: "ChainServices"),
                "GemstonePrimitives",
                "Preferences",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                "WalletService",
                "StreamService",
                "PerpetualService",
                "ConnectionsService",
                "ConnectionStatusService",
                "WalletSessionService",
                "Gemstone",
            ],
            path: "AppService",
            exclude: ["Tests", "TestKit"],
        ),
        .target(
            name: "AppServiceTestKit",
            dependencies: [
                "AppService",
                "Primitives",
                .product(name: "GemAPITestKit", package: "GemAPI"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                .product(name: "NodeServiceTestKit", package: "ChainServices"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                "StreamServiceTestKit",
                "PerpetualServiceTestKit",
                "ConnectionsServiceTestKit",
                "ConnectionStatusService",
                "WalletSessionServiceTestKit",
                .product(name: "ConnectivityService", package: "SystemServices"),
                .product(name: "ConnectivityServiceTestKit", package: "SystemServices"),
            ],
            path: "AppService/TestKit",
        ),
        .target(
            name: "ServiceStatusService",
            dependencies: [
                "Primitives",
                "Gemstone",
                "GemstonePrimitives",
                "NativeProviderService",
            ],
            path: "ServiceStatusService",
        ),
        .target(
            name: "ConnectionStatusService",
            dependencies: [
                "Primitives",
                "GemstonePrimitives",
                .product(name: "ConnectivityService", package: "SystemServices"),
            ],
            path: "ConnectionStatusService",
            exclude: ["Tests"],
        ),
        .testTarget(
            name: "ConnectionStatusServiceTests",
            dependencies: [
                "ConnectionStatusService",
                .product(name: "ConnectivityService", package: "SystemServices"),
            ],
            path: "ConnectionStatusService/Tests",
        ),
        .target(
            name: "ActivityService",
            dependencies: [
                "Primitives",
                "Store",
            ],
            path: "ActivityService",
            exclude: ["TestKit"],
        ),
        .target(
            name: "ActivityServiceTestKit",
            dependencies: [
                "ActivityService",
                .product(name: "StoreTestKit", package: "Store"),
            ],
            path: "ActivityService/TestKit",
        ),
        .target(
            name: "ConnectionsService",
            dependencies: [
                "Primitives",
                "Store",
                "Preferences",
                .product(name: "WalletConnectorService", package: "ChainServices"),
            ],
            path: "ConnectionsService",
            exclude: ["TestKit"],
        ),
        .target(
            name: "ConnectionsServiceTestKit",
            dependencies: [
                "ConnectionsService",
                "Primitives",
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "WalletConnectorServiceTestKit", package: "ChainServices"),
            ],
            path: "ConnectionsService/TestKit",
        ),
        .target(
            name: "EarnService",
            dependencies: [
                "Primitives",
                "Store",
                "Blockchain",
                "BalanceService",
            ],
            path: "EarnService",
            exclude: ["TestKit"],
        ),
        .target(
            name: "EarnServiceTestKit",
            dependencies: [
                "EarnService",
                "Primitives",
                .product(name: "PrimitivesTestKit", package: "Primitives"),
            ],
            path: "EarnService/TestKit",
        ),
        .testTarget(
            name: "TransactionStateServiceTests",
            dependencies: [
                "GemstoneStore",
                "Gemstone",
                .product(name: "GemstonePrimitivesTestKit", package: "GemstonePrimitives"),
                "TransactionStateService",
                "TransactionStateServiceTestKit",
                "BalanceServiceTestKit",
                "EarnService",
                "EarnServiceTestKit",
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                .product(name: "GemAPITestKit", package: "GemAPI"),
                .product(name: "PrimitivesTestKit", package: "Primitives"),
                .product(name: "StakeServiceTestKit", package: "ChainServices"),
                .product(name: "StoreTestKit", package: "Store"),
            ],
            path: "TransactionStateService/Tests",
        ),
        .testTarget(
            name: "BalanceServiceTests",
            dependencies: [
                "BalanceService",
                "BalanceServiceTestKit",
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                "Gemstone",
                .product(name: "BlockchainTestKit", package: "Blockchain"),
                .product(name: "GemAPI", package: "GemAPI"),
                .product(name: "GemAPITestKit", package: "GemAPI"),
                .product(name: "ChainServiceTestKit", package: "ChainServices"),
                .product(name: "PrimitivesTestKit", package: "Primitives"),
                .product(name: "StoreTestKit", package: "Store"),
            ],
            path: "BalanceService/Tests",
        ),
        .testTarget(
            name: "StreamServiceTests",
            dependencies: [
                "StreamService",
                "StreamServiceTestKit",
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                "Gemstone",
                "WalletSessionService",
                "WalletSessionServiceTestKit",
                .product(name: "PrimitivesTestKit", package: "Primitives"),
                .product(name: "WebSocketClientTestKit", package: "SwiftHTTPClient"),
            ],
            path: "StreamService/Tests",
        ),
        .testTarget(
            name: "WalletSessionServiceTests",
            dependencies: [
                "WalletSessionService",
                "WalletSessionServiceTestKit",
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "PrimitivesTestKit", package: "Primitives"),
            ],
            path: "WalletSessionService/Tests",
        ),
        .testTarget(
            name: "WalletServiceTests",
            dependencies: [
                "WalletService",
                "WalletServiceTestKit",
                "GemstonePrimitives",
                "WalletSessionService",
                "WalletSessionServiceTestKit",
                "BalanceServiceTestKit",
                .product(name: "KeystoreTestKit", package: "Keystore"),
                .product(name: "StoreTestKit", package: "Store"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                .product(name: "PrimitivesTestKit", package: "Primitives"),
            ],
            path: "WalletService/Tests",
        ),
        .testTarget(
            name: "AppServiceTests",
            dependencies: [
                "AppService",
                "AppServiceTestKit",
                .product(name: "GemstoneServices", package: "GemstoneServices"),
                .product(name: "GemstoneServicesTestKit", package: "GemstoneServices"),
                .product(name: "GemAPITestKit", package: "GemAPI"),
                .product(name: "PrimitivesTestKit", package: "Primitives"),
                .product(name: "PreferencesTestKit", package: "Preferences"),
                "PerpetualServiceTestKit",
                "Store",
                .product(name: "StoreTestKit", package: "Store"),
                "WalletSessionService",
                "WalletSessionServiceTestKit",
                .product(name: "GemstonePrimitivesTestKit", package: "GemstonePrimitives"),
            ],
            path: "AppService/Tests",
        ),
    ],
)
