[package]
name = "api_connector"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
reqwest = { workspace = true }
primitives = { path = "../primitives" }
gem_client = { path = "../gem_client", features = ["reqwest"] }

[dev-dependencies]
primitives = { path = "../primitives", features = ["testkit"] }
