pub const ASSETS_INITIAL_LIMIT: u32 = 12;
pub const ASSETS_SEARCH_LIMIT: u32 = 25;
pub const PERPETUALS_PREVIEW_LIMIT: u32 = 3;
pub const NFTS_PREVIEW_LIMIT: u32 = 3;
pub const RESULTS_LIMIT: u32 = 100;
