package com.gemwallet.android.ui.models.navigation

enum class RouteArgument(val key: String) {
    AssetId("assetId"),
    AssetIds("assetIds"),
    Chain("chain"),
    Code("code"),
    ConnectionId("connectionId"),
    ContactId("contactId"),
    DelegationId("delegationId"),
    FiatAmount("fiatAmount"),
    FromAssetId("fromAssetId"),
    NftAssetId("nftAssetId"),
    NftCollectionId("nftCollectionId"),
    Params("params"),
    Payment("payment"),
    PaymentLink("paymentLink"),
    Query("query"),
    Scope("scope"),
    SwapItemType("swapItemType"),
    Title("title"),
    ToAssetId("toAssetId"),
    TransactionId("transactionId"),
    Type("type"),
    Unverified("unverified"),
    Url("url"),
    ValidatorId("validatorId"),
    WalletId("walletId"),
}
