// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

import BigInt
import Foundation
import Gemstone
import GemstonePrimitives
import Primitives
import PrimitivesTestKit

public extension Gemstone.ApprovalData {
    static func mock(
        token: String = "",
        spender: String = "",
        value: BigUInt = 0,
        isUnlimited: Bool = false,
    ) -> Gemstone.ApprovalData {
        Gemstone.ApprovalData(
            token: token,
            spender: spender,
            value: value,
            isUnlimited: isUnlimited,
        )
    }
}

public extension Gemstone.ContractCallData {
    static func mock(
        contractAddress: String = "",
        callData: String = "",
        approval: Gemstone.ApprovalData? = nil,
        gasLimit: String? = nil,
    ) -> Gemstone.ContractCallData {
        Gemstone.ContractCallData(
            contractAddress: contractAddress,
            callData: callData,
            approval: approval,
            gasLimit: gasLimit,
        )
    }
}

public extension Gemstone.FiatProvider {
    static func mock(
        id: Gemstone.FiatProviderName = .mercuryo,
        name: String = "",
        imageUrl: String? = nil,
        priority: Int32? = nil,
        thresholdBps: Int32? = nil,
        enabled: Bool = false,
        buyEnabled: Bool = false,
        sellEnabled: Bool = false,
        paymentMethods: [Gemstone.PaymentType] = [],
    ) -> Gemstone.FiatProvider {
        Gemstone.FiatProvider(
            id: id,
            name: name,
            imageUrl: imageUrl,
            priority: priority,
            thresholdBps: thresholdBps,
            enabled: enabled,
            buyEnabled: buyEnabled,
            sellEnabled: sellEnabled,
            paymentMethods: paymentMethods,
        )
    }
}

public extension Gemstone.FiatQuote {
    static func mock(
        id: String = "",
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        provider: Gemstone.FiatProvider = .mock(),
        quoteType: Gemstone.FiatQuoteType = .buy,
        fiatAmount: Double = 0,
        fiatCurrency: String = "",
        cryptoAmount: Double = 0,
        value: BigUInt = 0,
        latency: UInt64 = 0,
        paymentMethods: [Gemstone.PaymentType] = [],
    ) -> Gemstone.FiatQuote {
        Gemstone.FiatQuote(
            id: id,
            asset: asset,
            provider: provider,
            quoteType: quoteType,
            fiatAmount: fiatAmount,
            fiatCurrency: fiatCurrency,
            cryptoAmount: cryptoAmount,
            value: value,
            latency: latency,
            paymentMethods: paymentMethods,
        )
    }
}

public extension Gemstone.GemAssetBalance {
    static func mock(
        assetId: String = Primitives.AssetId.mock().identifier,
        available: BigUInt = 0,
        frozen: BigUInt = 0,
        locked: BigUInt = 0,
        staked: BigUInt = 0,
        pending: BigUInt = 0,
        pendingUnconfirmed: BigUInt = 0,
        rewards: BigUInt = 0,
        reserved: BigUInt = 0,
        withdrawable: BigUInt = 0,
        earn: BigUInt = 0,
        metadata: Gemstone.BalanceMetadata? = nil,
        isActive: Bool = false,
    ) -> Gemstone.GemAssetBalance {
        Gemstone.GemAssetBalance(
            assetId: assetId,
            available: available,
            frozen: frozen,
            locked: locked,
            staked: staked,
            pending: pending,
            pendingUnconfirmed: pendingUnconfirmed,
            rewards: rewards,
            reserved: reserved,
            withdrawable: withdrawable,
            earn: earn,
            metadata: metadata,
            isActive: isActive,
        )
    }
}

public extension Gemstone.GemAssetIcon {
    static func mock(
        image: Gemstone.GemAssetIconImage = .mock(),
        badge: String? = nil,
        placeholder: String? = nil,
    ) -> Gemstone.GemAssetIcon {
        Gemstone.GemAssetIcon(
            image: image,
            badge: badge,
            placeholder: placeholder,
        )
    }
}

public extension Gemstone.GemAssetIconImage {
    static func mock() -> Gemstone.GemAssetIconImage {
        .local(chain: Primitives.Chain.bitcoin.rawValue)
    }
}

public extension Gemstone.GemAssetItemRow {
    static func mock(
        icon: Gemstone.GemAssetIcon = .mock(),
        title: String = "",
        titleExtra: String? = nil,
        subtitle: Gemstone.GemRowText? = nil,
        subtitleExtra: Gemstone.GemRowText? = nil,
        trailing: Gemstone.GemAssetItemTrailing = .mock(),
        masksBalance: Bool = false,
    ) -> Gemstone.GemAssetItemRow {
        Gemstone.GemAssetItemRow(
            icon: icon,
            title: title,
            titleExtra: titleExtra,
            subtitle: subtitle,
            subtitleExtra: subtitleExtra,
            trailing: trailing,
            masksBalance: masksBalance,
        )
    }
}

public extension Gemstone.GemAssetItemTrailing {
    static func mock() -> Gemstone.GemAssetItemTrailing {
        .value(value: .mock(), extra: nil)
    }
}

public extension Gemstone.GemConfirmFee {
    static func mock(
        value: BigInt = 0,
        formatted: Gemstone.GemFeeAmount = .mock(),
        additionalFees: [Gemstone.GemFeeOptionItem] = [],
        selectedPriority: Gemstone.FeePriority = .normal,
        amount: Gemstone.GemTransferAmountResult = .mock(),
    ) -> Gemstone.GemConfirmFee {
        Gemstone.GemConfirmFee(
            value: value,
            formatted: formatted,
            additionalFees: additionalFees,
            selectedPriority: selectedPriority,
            amount: amount,
        )
    }
}

public extension Gemstone.GemConfirmLoad {
    static func mock(
        transfer: Gemstone.GemTransferData = .mock(),
        sender: Gemstone.Account = Primitives.Account.mock().toGem(),
        feeAsset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        metadata: Gemstone.GemConfirmMetadata = .mock(),
        feeAssets: [Gemstone.GemFeeAsset] = [],
        simulation: Gemstone.GemConfirmSimulationState = .mock(),
        addressName: Gemstone.AddressName? = nil,
        fee: Gemstone.GemConfirmFee? = nil,
    ) -> Gemstone.GemConfirmLoad {
        Gemstone.GemConfirmLoad(
            transfer: transfer,
            sender: sender,
            feeAsset: feeAsset,
            metadata: metadata,
            feeAssets: feeAssets,
            simulation: simulation,
            addressName: addressName,
            fee: fee,
        )
    }
}

public extension Gemstone.GemConfirmMetadata {
    static func mock(
        assetBalance: Gemstone.GemAssetBalance = .mock(),
        feeAssetBalance: Gemstone.GemAssetBalance = .mock(),
        prices: [Gemstone.AssetPrice] = [],
    ) -> Gemstone.GemConfirmMetadata {
        Gemstone.GemConfirmMetadata(
            assetBalance: assetBalance,
            feeAssetBalance: feeAssetBalance,
            prices: prices,
        )
    }
}

public extension Gemstone.GemConfirmScreen {
    static func mock(
        phase: Gemstone.GemConfirmPhase = .loading,
        hasCriticalWarning: Bool = false,
        failure: Gemstone.GemConfirmFailure? = nil,
        hasFee: Bool = false,
        shownSheet: Gemstone.GemConfirmErrorSheet? = nil,
    ) -> Gemstone.GemConfirmScreen {
        Gemstone.GemConfirmScreen(
            phase: phase,
            hasCriticalWarning: hasCriticalWarning,
            failure: failure,
            hasFee: hasFee,
            shownSheet: shownSheet,
        )
    }
}

public extension Gemstone.GemConfirmSimulation {
    static func mock(
        primaryFields: [Gemstone.GemSimulationPayloadRow] = [],
        secondaryFields: [Gemstone.GemSimulationPayloadRow] = [],
        header: Gemstone.GemSimulationValue? = nil,
        balanceChanges: [Gemstone.GemSimulationBalanceChange] = [],
        hasCriticalWarning: Bool = false,
    ) -> Gemstone.GemConfirmSimulation {
        Gemstone.GemConfirmSimulation(
            primaryFields: primaryFields,
            secondaryFields: secondaryFields,
            header: header,
            balanceChanges: balanceChanges,
            hasCriticalWarning: hasCriticalWarning,
        )
    }
}

public extension Gemstone.GemConfirmSimulationState {
    static func mock(
        chain: String = Primitives.Chain.bitcoin.rawValue,
        warnings: [Gemstone.GemListRow] = [],
        simulation: Gemstone.GemConfirmSimulation? = nil,
    ) -> Gemstone.GemConfirmSimulationState {
        Gemstone.GemConfirmSimulationState(
            chain: chain,
            warnings: warnings,
            simulation: simulation,
        )
    }
}

public extension Gemstone.GemFeeAmount {
    static func mock(
        amount: Gemstone.GemFormattedNumber = .mock(),
        fiat: Gemstone.GemFormattedNumber? = nil,
    ) -> Gemstone.GemFeeAmount {
        Gemstone.GemFeeAmount(
            amount: amount,
            fiat: fiat,
        )
    }
}

public extension Gemstone.GemFeeAsset {
    static func mock(
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        balance: Gemstone.GemAssetBalance = .mock(),
        price: Gemstone.AssetPrice? = nil,
        row: Gemstone.GemAssetItemRow = .mock(),
    ) -> Gemstone.GemFeeAsset {
        Gemstone.GemFeeAsset(
            asset: asset,
            balance: balance,
            price: price,
            row: row,
        )
    }
}

public extension Gemstone.GemFeeRateRows {
    static func mock(
        rows: [Gemstone.GemFeeRateRow] = [],
        showsOptions: Bool = false,
        unitType: Gemstone.FeeUnitType = .satVb,
        unitDecimals: UInt32 = 0,
        supportsCustomFee: Bool = false,
        selectedTotal: BigInt? = nil,
        normalTotal: BigInt? = nil,
        customRate: Gemstone.GemLocalizedText? = nil,
    ) -> Gemstone.GemFeeRateRows {
        Gemstone.GemFeeRateRows(
            rows: rows,
            showsOptions: showsOptions,
            unitType: unitType,
            unitDecimals: unitDecimals,
            supportsCustomFee: supportsCustomFee,
            selectedTotal: selectedTotal,
            normalTotal: normalTotal,
            customRate: customRate,
        )
    }
}

public extension Gemstone.GemFiatQuoteRequest {
    static func mock(
        quoteType: Gemstone.FiatQuoteType = .buy,
        amount: Double = 0,
    ) -> Gemstone.GemFiatQuoteRequest {
        Gemstone.GemFiatQuoteRequest(
            quoteType: quoteType,
            amount: amount,
        )
    }
}

public extension Gemstone.GemFiatQuoteRow {
    static func mock(
        quoteId: String = "",
        provider: Gemstone.FiatProviderName = .mercuryo,
        providerName: String = "",
        cryptoAmount: Gemstone.GemFormattedNumber = .mock(),
        fiatAmount: Gemstone.GemFormattedNumber = .mock(),
        rate: Gemstone.GemAssetRate? = nil,
    ) -> Gemstone.GemFiatQuoteRow {
        Gemstone.GemFiatQuoteRow(
            quoteId: quoteId,
            provider: provider,
            providerName: providerName,
            cryptoAmount: cryptoAmount,
            fiatAmount: fiatAmount,
            rate: rate,
        )
    }
}

public extension Gemstone.GemFiatQuotesResult {
    static func mock(
        request: Gemstone.GemFiatQuoteRequest = .mock(),
        quotes: [Gemstone.FiatQuote] = [],
        error: Gemstone.GemServiceError? = nil,
    ) -> Gemstone.GemFiatQuotesResult {
        Gemstone.GemFiatQuotesResult(
            request: request,
            quotes: quotes,
            error: error,
        )
    }
}

public extension Gemstone.GemFormattedNumber {
    static func mock(
        value: Double = 0,
        unit: Gemstone.GemNumberUnit = .mock(),
        display: Gemstone.GemNumberDisplay = .mock(),
        notation: Gemstone.GemNumberNotation = .plain,
        tone: Gemstone.GemValueTone = .plain,
        rounding: Gemstone.GemNumberRounding = .toNearest,
        exact: String? = nil,
    ) -> Gemstone.GemFormattedNumber {
        Gemstone.GemFormattedNumber(
            value: value,
            unit: unit,
            display: display,
            notation: notation,
            tone: tone,
            rounding: rounding,
            exact: exact,
        )
    }
}

public extension Gemstone.GemLocalizedText {
    static func mock() -> Gemstone.GemLocalizedText {
        .walletDefaultName(index: 0)
    }
}

public extension Gemstone.GemNumberDisplay {
    static func mock() -> Gemstone.GemNumberDisplay {
        .number(precision: .mock())
    }
}

public extension Gemstone.GemNumberUnit {
    static func mock() -> Gemstone.GemNumberUnit {
        .currency(code: "")
    }
}

public extension Gemstone.GemPaymentRecipient {
    static func mock(
        recipient: Gemstone.GemRecipient = .mock(),
        amount: String? = nil,
    ) -> Gemstone.GemPaymentRecipient {
        Gemstone.GemPaymentRecipient(
            recipient: recipient,
            amount: amount,
        )
    }
}

public extension Gemstone.GemPrecision {
    static func mock() -> Gemstone.GemPrecision {
        .fraction(min: 0, max: 0)
    }
}

public extension Gemstone.GemRecipient {
    static func mock(
        address: String = "",
        name: String? = nil,
        memo: String? = nil,
        references: [String] = [],
    ) -> Gemstone.GemRecipient {
        Gemstone.GemRecipient(
            address: address,
            name: name,
            memo: memo,
            references: references,
        )
    }
}

public extension Gemstone.GemRowText {
    static func mock(
        text: Gemstone.GemLocalizedText = .mock(),
        tone: Gemstone.GemValueTone = .plain,
    ) -> Gemstone.GemRowText {
        Gemstone.GemRowText(
            text: text,
            tone: tone,
        )
    }
}

public extension Gemstone.GemTransferAmount {
    static func mock(
        value: BigInt = 0,
        networkFee: BigInt = 0,
        isMaxAmount: Bool = false,
    ) -> Gemstone.GemTransferAmount {
        Gemstone.GemTransferAmount(
            value: value,
            networkFee: networkFee,
            isMaxAmount: isMaxAmount,
        )
    }
}

public extension Gemstone.GemTransferAmountResult {
    static func mock() -> Gemstone.GemTransferAmountResult {
        .amount(amount: .mock())
    }
}

public extension Gemstone.GemTransferData {
    static func mock(
        inputType: Gemstone.TransactionInputType = .mock(),
        recipient: Gemstone.GemRecipient = .mock(),
        value: BigInt = 0,
        useMaxAmount: Bool = false,
    ) -> Gemstone.GemTransferData {
        Gemstone.GemTransferData(
            inputType: inputType,
            recipient: recipient,
            value: value,
            useMaxAmount: useMaxAmount,
        )
    }
}

public extension Gemstone.PaymentInvoice {
    static func mock(
        link: Gemstone.PaymentLink = .mock(),
        merchant: Gemstone.PaymentMerchant = .mock(),
        price: Gemstone.PaymentPrice? = nil,
        quotes: [Gemstone.PaymentQuote] = [],
        verification: Gemstone.PaymentVerification? = nil,
    ) -> Gemstone.PaymentInvoice {
        Gemstone.PaymentInvoice(
            link: link,
            merchant: merchant,
            price: price,
            quotes: quotes,
            verification: verification,
        )
    }
}

public extension Gemstone.PaymentLink {
    static func mock() -> Gemstone.PaymentLink {
        .solanaPay(url: "")
    }
}

public extension Gemstone.PaymentMerchant {
    static func mock(
        name: String = "",
        icon: String = "",
    ) -> Gemstone.PaymentMerchant {
        Gemstone.PaymentMerchant(
            name: name,
            icon: icon,
        )
    }
}

public extension Gemstone.PaymentPrice {
    static func mock(
        currency: String = "",
        amount: Double = 0,
    ) -> Gemstone.PaymentPrice {
        Gemstone.PaymentPrice(
            currency: currency,
            amount: amount,
        )
    }
}

public extension Gemstone.PaymentQuote {
    static func mock(
        id: String = "",
        assetId: String = Primitives.AssetId.mock().identifier,
        value: BigUInt = 0,
    ) -> Gemstone.PaymentQuote {
        Gemstone.PaymentQuote(
            id: id,
            assetId: assetId,
            value: value,
        )
    }
}

public extension Gemstone.PaymentRequest {
    static func mock(
        address: String = "",
        amount: Gemstone.PaymentAmount? = nil,
        memo: String? = nil,
        label: String? = nil,
        references: [String]? = nil,
        assetId: String? = nil,
    ) -> Gemstone.PaymentRequest {
        Gemstone.PaymentRequest(
            address: address,
            amount: amount,
            memo: memo,
            label: label,
            references: references,
            assetId: assetId,
        )
    }
}

public extension Gemstone.SignMessage {
    static func mock(
        chain: String = Primitives.Chain.bitcoin.rawValue,
        signType: Gemstone.SignDigestType = .eip191,
        data: Data = Data(),
    ) -> Gemstone.SignMessage {
        Gemstone.SignMessage(
            chain: chain,
            signType: signType,
            data: data,
        )
    }
}

public extension Gemstone.SimulationPayloadField {
    static func mock(
        kind: Gemstone.SimulationPayloadFieldKind = .contract,
        label: String? = nil,
        value: String = "",
        fieldType: Gemstone.SimulationPayloadFieldType = .text,
        display: Gemstone.SimulationPayloadFieldDisplay = .primary,
    ) -> Gemstone.SimulationPayloadField {
        Gemstone.SimulationPayloadField(
            kind: kind,
            label: label,
            value: value,
            fieldType: fieldType,
            display: display,
        )
    }
}

public extension Gemstone.SimulationResult {
    static func mock(
        warnings: [Gemstone.SimulationWarning] = [],
        balanceChanges: [Gemstone.SimulationBalanceChange] = [],
        payload: [Gemstone.SimulationPayloadField] = [],
        header: Gemstone.SimulationHeader? = nil,
    ) -> Gemstone.SimulationResult {
        Gemstone.SimulationResult(
            warnings: warnings,
            balanceChanges: balanceChanges,
            payload: payload,
            header: header,
        )
    }
}

public extension Gemstone.SimulationWarning {
    static func mock(
        severity: Gemstone.SimulationSeverity = .low,
        warning: Gemstone.SimulationWarningType = .mock(),
        message: String? = nil,
    ) -> Gemstone.SimulationWarning {
        Gemstone.SimulationWarning(
            severity: severity,
            warning: warning,
            message: message,
        )
    }
}

public extension Gemstone.SimulationWarningApproval {
    static func mock(
        assetId: String = Primitives.AssetId.mock().identifier,
        value: BigInt? = nil,
    ) -> Gemstone.SimulationWarningApproval {
        Gemstone.SimulationWarningApproval(
            assetId: assetId,
            value: value,
        )
    }
}

public extension Gemstone.SimulationWarningType {
    static func mock() -> Gemstone.SimulationWarningType {
        .tokenApproval(.mock())
    }
}

public extension Gemstone.SwapData {
    static func mock(
        quote: Gemstone.SwapQuote = .mock(),
        data: Gemstone.SwapQuoteData = .mock(),
    ) -> Gemstone.SwapData {
        Gemstone.SwapData(
            quote: quote,
            data: data,
        )
    }
}

public extension Gemstone.SwapProviderData {
    static func mock(
        provider: Gemstone.SwapProvider = .uniswapV3,
        name: String = "",
        protocolName: String = "",
    ) -> Gemstone.SwapProviderData {
        Gemstone.SwapProviderData(
            provider: provider,
            name: name,
            protocolName: protocolName,
        )
    }
}

public extension Gemstone.SwapQuote {
    static func mock(
        fromAddress: String = "",
        fromValue: BigUInt = 0,
        minFromValue: BigUInt? = nil,
        toAddress: String = "",
        toValue: BigUInt = 0,
        providerData: Gemstone.SwapProviderData = .mock(),
        slippageBps: UInt32 = 0,
        etaInSeconds: UInt32? = nil,
        useMaxAmount: Bool? = nil,
    ) -> Gemstone.SwapQuote {
        Gemstone.SwapQuote(
            fromAddress: fromAddress,
            fromValue: fromValue,
            minFromValue: minFromValue,
            toAddress: toAddress,
            toValue: toValue,
            providerData: providerData,
            slippageBps: slippageBps,
            etaInSeconds: etaInSeconds,
            useMaxAmount: useMaxAmount,
        )
    }
}

public extension Gemstone.SwapQuoteData {
    static func mock(
        to: String = "",
        dataType: Gemstone.SwapQuoteDataType = .contract,
        value: BigUInt = 0,
        data: String = "",
        memo: String? = nil,
        approval: Gemstone.ApprovalData? = nil,
        gasLimit: String? = nil,
    ) -> Gemstone.SwapQuoteData {
        Gemstone.SwapQuoteData(
            to: to,
            dataType: dataType,
            value: value,
            data: data,
            memo: memo,
            approval: approval,
            gasLimit: gasLimit,
        )
    }
}

public extension Gemstone.TransactionInputType {
    static func mock() -> Gemstone.TransactionInputType {
        .transfer(asset: Primitives.Asset.mock().toGem())
    }
}

public extension Gemstone.TransferDataExtra {
    static func mock(
        to: String = "",
        gasLimit: BigInt? = nil,
        gasPrice: Gemstone.GasPriceType? = nil,
        data: Data? = nil,
        outputType: Gemstone.TransferDataOutputType = .encodedTransaction,
        outputAction: Gemstone.TransferDataOutputAction = .sign,
        transactionType: Gemstone.TransactionType = .transfer,
        approval: Gemstone.ApprovalData? = nil,
    ) -> Gemstone.TransferDataExtra {
        Gemstone.TransferDataExtra(
            to: to,
            gasLimit: gasLimit,
            gasPrice: gasPrice,
            data: data,
            outputType: outputType,
            outputAction: outputAction,
            transactionType: transactionType,
            approval: approval,
        )
    }
}
