// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

import BigInt
import Foundation
import Gemstone
import GemstonePrimitives
import Primitives
import PrimitivesTestKit

public extension Gemstone.GemAssetBalance {
    static func mock(
        assetId: String = Primitives.AssetId.mock().identifier,
        available: BigUInt = 0,
        frozen: BigUInt = 0,
        locked: BigUInt = 0,
        staked: BigUInt = 0,
        pending: BigUInt = 0,
        pendingUnconfirmed: BigUInt = 0,
        rewards: BigUInt = 0,
        reserved: BigUInt = 0,
        withdrawable: BigUInt = 0,
        earn: BigUInt = 0,
        metadata: Gemstone.BalanceMetadata? = nil,
        isActive: Bool = false,
    ) -> Gemstone.GemAssetBalance {
        Gemstone.GemAssetBalance(
            assetId: assetId,
            available: available,
            frozen: frozen,
            locked: locked,
            staked: staked,
            pending: pending,
            pendingUnconfirmed: pendingUnconfirmed,
            rewards: rewards,
            reserved: reserved,
            withdrawable: withdrawable,
            earn: earn,
            metadata: metadata,
            isActive: isActive,
        )
    }
}

public extension Gemstone.GemAssetIcon {
    static func mock(
        image: Gemstone.GemAssetIconImage = .mock(),
        badge: String? = nil,
        placeholder: String? = nil,
    ) -> Gemstone.GemAssetIcon {
        Gemstone.GemAssetIcon(
            image: image,
            badge: badge,
            placeholder: placeholder,
        )
    }
}

public extension Gemstone.GemAssetIconImage {
    static func mock() -> Gemstone.GemAssetIconImage {
        .local(chain: Primitives.Chain.bitcoin.rawValue)
    }
}

public extension Gemstone.GemAssetItemRow {
    static func mock(
        icon: Gemstone.GemAssetIcon = .mock(),
        title: String = "",
        titleExtra: String? = nil,
        subtitle: Gemstone.GemRowText? = nil,
        subtitleExtra: Gemstone.GemRowText? = nil,
        trailing: Gemstone.GemAssetItemTrailing = .mock(),
        masksBalance: Bool = false,
    ) -> Gemstone.GemAssetItemRow {
        Gemstone.GemAssetItemRow(
            icon: icon,
            title: title,
            titleExtra: titleExtra,
            subtitle: subtitle,
            subtitleExtra: subtitleExtra,
            trailing: trailing,
            masksBalance: masksBalance,
        )
    }
}

public extension Gemstone.GemAssetItemTrailing {
    static func mock() -> Gemstone.GemAssetItemTrailing {
        .value(value: .mock(), extra: nil)
    }
}

public extension Gemstone.GemConfirmFee {
    static func mock(
        value: BigInt = 0,
        formatted: Gemstone.GemFeeAmount = .mock(),
        additionalFees: [Gemstone.GemFeeOptionItem] = [],
        selectedPriority: Gemstone.FeePriority = .normal,
        amount: Gemstone.GemTransferAmountResult = .mock(),
    ) -> Gemstone.GemConfirmFee {
        Gemstone.GemConfirmFee(
            value: value,
            formatted: formatted,
            additionalFees: additionalFees,
            selectedPriority: selectedPriority,
            amount: amount,
        )
    }
}

public extension Gemstone.GemConfirmLoad {
    static func mock(
        transfer: Gemstone.GemTransferData = .mock(),
        sender: Gemstone.Account = Primitives.Account.mock().toGem(),
        feeAsset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        metadata: Gemstone.GemConfirmMetadata = .mock(),
        feeAssets: [Gemstone.GemFeeAsset] = [],
        simulation: Gemstone.GemConfirmSimulationState = .mock(),
        addressName: Gemstone.AddressName? = nil,
        fee: Gemstone.GemConfirmFee? = nil,
    ) -> Gemstone.GemConfirmLoad {
        Gemstone.GemConfirmLoad(
            transfer: transfer,
            sender: sender,
            feeAsset: feeAsset,
            metadata: metadata,
            feeAssets: feeAssets,
            simulation: simulation,
            addressName: addressName,
            fee: fee,
        )
    }
}

public extension Gemstone.GemConfirmMetadata {
    static func mock(
        assetBalance: Gemstone.GemAssetBalance = .mock(),
        feeAssetBalance: Gemstone.GemAssetBalance = .mock(),
        prices: [Gemstone.AssetPrice] = [],
    ) -> Gemstone.GemConfirmMetadata {
        Gemstone.GemConfirmMetadata(
            assetBalance: assetBalance,
            feeAssetBalance: feeAssetBalance,
            prices: prices,
        )
    }
}

public extension Gemstone.GemConfirmScreen {
    static func mock(
        phase: Gemstone.GemConfirmPhase = .loading,
        hasCriticalWarning: Bool = false,
        failure: Gemstone.GemConfirmFailure? = nil,
        hasFee: Bool = false,
        shownSheet: Gemstone.GemConfirmErrorSheet? = nil,
    ) -> Gemstone.GemConfirmScreen {
        Gemstone.GemConfirmScreen(
            phase: phase,
            hasCriticalWarning: hasCriticalWarning,
            failure: failure,
            hasFee: hasFee,
            shownSheet: shownSheet,
        )
    }
}

public extension Gemstone.GemConfirmSimulation {
    static func mock(
        primaryFields: [Gemstone.GemSimulationPayloadRow] = [],
        secondaryFields: [Gemstone.GemSimulationPayloadRow] = [],
        header: Gemstone.GemSimulationValue? = nil,
        balanceChanges: [Gemstone.GemSimulationBalanceChange] = [],
        hasCriticalWarning: Bool = false,
    ) -> Gemstone.GemConfirmSimulation {
        Gemstone.GemConfirmSimulation(
            primaryFields: primaryFields,
            secondaryFields: secondaryFields,
            header: header,
            balanceChanges: balanceChanges,
            hasCriticalWarning: hasCriticalWarning,
        )
    }
}

public extension Gemstone.GemConfirmSimulationState {
    static func mock(
        chain: String = Primitives.Chain.bitcoin.rawValue,
        warnings: [Gemstone.GemListRow] = [],
        simulation: Gemstone.GemConfirmSimulation? = nil,
    ) -> Gemstone.GemConfirmSimulationState {
        Gemstone.GemConfirmSimulationState(
            chain: chain,
            warnings: warnings,
            simulation: simulation,
        )
    }
}

public extension Gemstone.GemFeeAmount {
    static func mock(
        amount: Gemstone.GemFormattedNumber = .mock(),
        fiat: Gemstone.GemFormattedNumber? = nil,
    ) -> Gemstone.GemFeeAmount {
        Gemstone.GemFeeAmount(
            amount: amount,
            fiat: fiat,
        )
    }
}

public extension Gemstone.GemFeeAsset {
    static func mock(
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        balance: Gemstone.GemAssetBalance = .mock(),
        price: Gemstone.AssetPrice? = nil,
        row: Gemstone.GemAssetItemRow = .mock(),
    ) -> Gemstone.GemFeeAsset {
        Gemstone.GemFeeAsset(
            asset: asset,
            balance: balance,
            price: price,
            row: row,
        )
    }
}

public extension Gemstone.GemFeeRateRows {
    static func mock(
        rows: [Gemstone.GemFeeRateRow] = [],
        showsOptions: Bool = false,
        unitType: Gemstone.FeeUnitType = .satVb,
        unitDecimals: UInt32 = 0,
        supportsCustomFee: Bool = false,
        selectedTotal: BigInt? = nil,
        normalTotal: BigInt? = nil,
        customRate: Gemstone.GemLocalizedText? = nil,
    ) -> Gemstone.GemFeeRateRows {
        Gemstone.GemFeeRateRows(
            rows: rows,
            showsOptions: showsOptions,
            unitType: unitType,
            unitDecimals: unitDecimals,
            supportsCustomFee: supportsCustomFee,
            selectedTotal: selectedTotal,
            normalTotal: normalTotal,
            customRate: customRate,
        )
    }
}

public extension Gemstone.GemFormattedNumber {
    static func mock(
        value: Double = 0,
        unit: Gemstone.GemNumberUnit = .mock(),
        display: Gemstone.GemNumberDisplay = .mock(),
        notation: Gemstone.GemNumberNotation = .plain,
        tone: Gemstone.GemValueTone = .plain,
        rounding: Gemstone.GemNumberRounding = .toNearest,
        exact: String? = nil,
    ) -> Gemstone.GemFormattedNumber {
        Gemstone.GemFormattedNumber(
            value: value,
            unit: unit,
            display: display,
            notation: notation,
            tone: tone,
            rounding: rounding,
            exact: exact,
        )
    }
}

public extension Gemstone.GemLocalizedText {
    static func mock() -> Gemstone.GemLocalizedText {
        .walletDefaultName(index: 0)
    }
}

public extension Gemstone.GemNumberDisplay {
    static func mock() -> Gemstone.GemNumberDisplay {
        .number(precision: .mock())
    }
}

public extension Gemstone.GemNumberUnit {
    static func mock() -> Gemstone.GemNumberUnit {
        .currency(code: "")
    }
}

public extension Gemstone.GemPrecision {
    static func mock() -> Gemstone.GemPrecision {
        .fraction(min: 0, max: 0)
    }
}

public extension Gemstone.GemRecipient {
    static func mock(
        address: String = "",
        name: String? = nil,
        memo: String? = nil,
        references: [String] = [],
    ) -> Gemstone.GemRecipient {
        Gemstone.GemRecipient(
            address: address,
            name: name,
            memo: memo,
            references: references,
        )
    }
}

public extension Gemstone.GemRowText {
    static func mock(
        text: Gemstone.GemLocalizedText = .mock(),
        tone: Gemstone.GemValueTone = .plain,
    ) -> Gemstone.GemRowText {
        Gemstone.GemRowText(
            text: text,
            tone: tone,
        )
    }
}

public extension Gemstone.GemTransferAmount {
    static func mock(
        value: BigInt = 0,
        networkFee: BigInt = 0,
        isMaxAmount: Bool = false,
    ) -> Gemstone.GemTransferAmount {
        Gemstone.GemTransferAmount(
            value: value,
            networkFee: networkFee,
            isMaxAmount: isMaxAmount,
        )
    }
}

public extension Gemstone.GemTransferAmountResult {
    static func mock() -> Gemstone.GemTransferAmountResult {
        .amount(amount: .mock())
    }
}

public extension Gemstone.GemTransferData {
    static func mock(
        inputType: Gemstone.TransactionInputType = .mock(),
        recipient: Gemstone.GemRecipient = .mock(),
        value: BigInt = 0,
        useMaxAmount: Bool = false,
    ) -> Gemstone.GemTransferData {
        Gemstone.GemTransferData(
            inputType: inputType,
            recipient: recipient,
            value: value,
            useMaxAmount: useMaxAmount,
        )
    }
}

public extension Gemstone.SimulationPayloadField {
    static func mock(
        kind: Gemstone.SimulationPayloadFieldKind = .contract,
        label: String? = nil,
        value: String = "",
        fieldType: Gemstone.SimulationPayloadFieldType = .text,
        display: Gemstone.SimulationPayloadFieldDisplay = .primary,
    ) -> Gemstone.SimulationPayloadField {
        Gemstone.SimulationPayloadField(
            kind: kind,
            label: label,
            value: value,
            fieldType: fieldType,
            display: display,
        )
    }
}

public extension Gemstone.SimulationResult {
    static func mock(
        warnings: [Gemstone.SimulationWarning] = [],
        balanceChanges: [Gemstone.SimulationBalanceChange] = [],
        payload: [Gemstone.SimulationPayloadField] = [],
        header: Gemstone.SimulationHeader? = nil,
    ) -> Gemstone.SimulationResult {
        Gemstone.SimulationResult(
            warnings: warnings,
            balanceChanges: balanceChanges,
            payload: payload,
            header: header,
        )
    }
}

public extension Gemstone.SimulationWarning {
    static func mock(
        severity: Gemstone.SimulationSeverity = .low,
        warning: Gemstone.SimulationWarningType = .mock(),
        message: String? = nil,
    ) -> Gemstone.SimulationWarning {
        Gemstone.SimulationWarning(
            severity: severity,
            warning: warning,
            message: message,
        )
    }
}

public extension Gemstone.SimulationWarningApproval {
    static func mock(
        assetId: String = Primitives.AssetId.mock().identifier,
        value: BigInt? = nil,
    ) -> Gemstone.SimulationWarningApproval {
        Gemstone.SimulationWarningApproval(
            assetId: assetId,
            value: value,
        )
    }
}

public extension Gemstone.SimulationWarningType {
    static func mock() -> Gemstone.SimulationWarningType {
        .tokenApproval(.mock())
    }
}

public extension Gemstone.TransactionInputType {
    static func mock() -> Gemstone.TransactionInputType {
        .transfer(asset: Primitives.Asset.mock().toGem())
    }
}
