// Generated by `just generate-models`. Do not edit.
// Declared in core/bin/generate/remote_types.yml.

import BigInt
import Foundation
import Gemstone
import GemstonePrimitives
import Primitives
import PrimitivesTestKit

public extension Gemstone.ApprovalData {
    static func mock(
        token: String = "",
        spender: String = "",
        value: BigUInt = 0,
        isUnlimited: Bool = false,
    ) -> Gemstone.ApprovalData {
        Gemstone.ApprovalData(
            token: token,
            spender: spender,
            value: value,
            isUnlimited: isUnlimited,
        )
    }
}

public extension Gemstone.ContractCallData {
    static func mock(
        contractAddress: String = "",
        callData: String = "",
        approval: Gemstone.ApprovalData? = nil,
        gasLimit: String? = nil,
    ) -> Gemstone.ContractCallData {
        Gemstone.ContractCallData(
            contractAddress: contractAddress,
            callData: callData,
            approval: approval,
            gasLimit: gasLimit,
        )
    }
}

public extension Gemstone.FiatProvider {
    static func mock(
        id: Gemstone.FiatProviderName = .mercuryo,
        name: String = "",
        imageUrl: String? = nil,
        priority: Int32? = nil,
        thresholdBps: Int32? = nil,
        enabled: Bool = false,
        buyEnabled: Bool = false,
        sellEnabled: Bool = false,
        paymentMethods: [Gemstone.PaymentType] = [],
    ) -> Gemstone.FiatProvider {
        Gemstone.FiatProvider(
            id: id,
            name: name,
            imageUrl: imageUrl,
            priority: priority,
            thresholdBps: thresholdBps,
            enabled: enabled,
            buyEnabled: buyEnabled,
            sellEnabled: sellEnabled,
            paymentMethods: paymentMethods,
        )
    }
}

public extension Gemstone.FiatQuote {
    static func mock(
        id: String = "",
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        provider: Gemstone.FiatProvider = .mock(),
        quoteType: Gemstone.FiatQuoteType = .buy,
        fiatAmount: Double = 0,
        fiatCurrency: String = "",
        cryptoAmount: Double = 0,
        value: BigUInt = 0,
        latency: UInt64 = 0,
        paymentMethods: [Gemstone.PaymentType] = [],
    ) -> Gemstone.FiatQuote {
        Gemstone.FiatQuote(
            id: id,
            asset: asset,
            provider: provider,
            quoteType: quoteType,
            fiatAmount: fiatAmount,
            fiatCurrency: fiatCurrency,
            cryptoAmount: cryptoAmount,
            value: value,
            latency: latency,
            paymentMethods: paymentMethods,
        )
    }
}

public extension Gemstone.GemAddressRow {
    static func mock(
        title: Gemstone.GemLocalizedText = .mock(),
        text: Gemstone.GemLocalizedText = .mock(),
        shortAddress: String? = nil,
        chain: String = Primitives.Chain.bitcoin.rawValue,
        address: String = "",
        avatar: Gemstone.GemAvatar? = nil,
        menu: [Gemstone.GemRowMenuItem] = [],
        contact: Gemstone.GemRecipient? = nil,
        isSelectable: Bool = false,
    ) -> Gemstone.GemAddressRow {
        Gemstone.GemAddressRow(
            title: title,
            text: text,
            shortAddress: shortAddress,
            chain: chain,
            address: address,
            avatar: avatar,
            menu: menu,
            contact: contact,
            isSelectable: isSelectable,
        )
    }
}

public extension Gemstone.GemAppUpdateOffer {
    static func mock(
        version: String = "",
        title: Gemstone.GemLocalizedText = .mock(),
        description: Gemstone.GemLocalizedText = .mock(),
        actions: [Gemstone.GemAppUpdateAction] = [],
        apkUrl: String? = nil,
    ) -> Gemstone.GemAppUpdateOffer {
        Gemstone.GemAppUpdateOffer(
            version: version,
            title: title,
            description: description,
            actions: actions,
            apkUrl: apkUrl,
        )
    }
}

public extension Gemstone.GemAssetBalance {
    static func mock(
        assetId: String = Primitives.AssetId.mock().identifier,
        available: BigUInt = 0,
        frozen: BigUInt = 0,
        locked: BigUInt = 0,
        staked: BigUInt = 0,
        pending: BigUInt = 0,
        pendingUnconfirmed: BigUInt = 0,
        rewards: BigUInt = 0,
        reserved: BigUInt = 0,
        withdrawable: BigUInt = 0,
        earn: BigUInt = 0,
        metadata: Gemstone.BalanceMetadata? = nil,
        isActive: Bool = false,
    ) -> Gemstone.GemAssetBalance {
        Gemstone.GemAssetBalance(
            assetId: assetId,
            available: available,
            frozen: frozen,
            locked: locked,
            staked: staked,
            pending: pending,
            pendingUnconfirmed: pendingUnconfirmed,
            rewards: rewards,
            reserved: reserved,
            withdrawable: withdrawable,
            earn: earn,
            metadata: metadata,
            isActive: isActive,
        )
    }
}

public extension Gemstone.GemAssetDetails {
    static func mock(
        state: Gemstone.GemAssetDetailsState = .mock(),
        header: Gemstone.GemValueHeader = .mock(),
        banner: Gemstone.GemBannerRow? = nil,
        sections: [Gemstone.GemAssetDetailSection] = [],
        title: String = "",
        options: [Gemstone.GemAssetOption] = [],
        verificationStatus: Gemstone.VerificationStatus? = nil,
        networkDestination: Gemstone.GemAssetNetworkDestination? = nil,
        shareUrl: String = "",
        swapPair: Gemstone.GemSwapPairSuggestion = .mock(),
    ) -> Gemstone.GemAssetDetails {
        Gemstone.GemAssetDetails(
            state: state,
            header: header,
            banner: banner,
            sections: sections,
            title: title,
            options: options,
            verificationStatus: verificationStatus,
            networkDestination: networkDestination,
            shareUrl: shareUrl,
            swapPair: swapPair,
        )
    }
}

public extension Gemstone.GemAssetDetailsState {
    static func mock(
        isViewOnly: Bool = false,
        showsBanners: Bool = false,
        priceAlert: Gemstone.GemPriceAlertToggle = .enabled,
        emptyState: Gemstone.GemEmptyState = .mock(),
    ) -> Gemstone.GemAssetDetailsState {
        Gemstone.GemAssetDetailsState(
            isViewOnly: isViewOnly,
            showsBanners: showsBanners,
            priceAlert: priceAlert,
            emptyState: emptyState,
        )
    }
}

public extension Gemstone.GemAssetIcon {
    static func mock(
        image: Gemstone.GemAssetIconImage = .mock(),
        badge: String? = nil,
        placeholder: String? = nil,
    ) -> Gemstone.GemAssetIcon {
        Gemstone.GemAssetIcon(
            image: image,
            badge: badge,
            placeholder: placeholder,
        )
    }
}

public extension Gemstone.GemAssetIconImage {
    static func mock() -> Gemstone.GemAssetIconImage {
        .local(chain: Primitives.Chain.bitcoin.rawValue)
    }
}

public extension Gemstone.GemAssetItemRow {
    static func mock(
        icon: Gemstone.GemAssetIcon = .mock(),
        title: String = "",
        titleExtra: String? = nil,
        subtitle: Gemstone.GemRowText? = nil,
        subtitleExtra: Gemstone.GemRowText? = nil,
        trailing: Gemstone.GemAssetItemTrailing = .mock(),
        masksBalance: Bool = false,
    ) -> Gemstone.GemAssetItemRow {
        Gemstone.GemAssetItemRow(
            icon: icon,
            title: title,
            titleExtra: titleExtra,
            subtitle: subtitle,
            subtitleExtra: subtitleExtra,
            trailing: trailing,
            masksBalance: masksBalance,
        )
    }
}

public extension Gemstone.GemAssetItemTrailing {
    static func mock() -> Gemstone.GemAssetItemTrailing {
        .value(value: .mock(), extra: nil)
    }
}

public extension Gemstone.GemAssetRowStyle {
    static func mock(
        title: Gemstone.GemAssetTitleStyle = .asset,
        showsSymbol: Bool = false,
        subtitle: Gemstone.GemAssetSubtitleStyle = .network,
        trailing: Gemstone.GemAssetTrailingStyle = .balance,
    ) -> Gemstone.GemAssetRowStyle {
        Gemstone.GemAssetRowStyle(
            title: title,
            showsSymbol: showsSymbol,
            subtitle: subtitle,
            trailing: trailing,
        )
    }
}

public extension Gemstone.GemChainRow {
    static func mock(
        chain: String = Primitives.Chain.bitcoin.rawValue,
        title: String = "",
        standard: Gemstone.GemLocalizedText? = nil,
        icon: Gemstone.GemAssetIcon = .mock(),
    ) -> Gemstone.GemChainRow {
        Gemstone.GemChainRow(
            chain: chain,
            title: title,
            standard: standard,
            icon: icon,
        )
    }
}

public extension Gemstone.GemChart {
    static func mock(
        values: [Gemstone.ChartDateValue] = [],
        baseValue: Double = 0,
        current: Gemstone.GemChartCurrent? = nil,
    ) -> Gemstone.GemChart {
        Gemstone.GemChart(
            values: values,
            baseValue: baseValue,
            current: current,
        )
    }
}

public extension Gemstone.GemChartBounds {
    static func mock(
        lowerIndex: UInt32 = 0,
        upperIndex: UInt32 = 0,
        yMin: Double = 0,
        yMax: Double = 0,
        low: Gemstone.GemFormattedNumber = .mock(),
        high: Gemstone.GemFormattedNumber = .mock(),
    ) -> Gemstone.GemChartBounds {
        Gemstone.GemChartBounds(
            lowerIndex: lowerIndex,
            upperIndex: upperIndex,
            yMin: yMin,
            yMax: yMax,
            low: low,
            high: high,
        )
    }
}

public extension Gemstone.GemChartData {
    static func mock(
        valueType: Gemstone.GemChartValueType = .price,
        base: Double = 0,
        showsSecondaryValue: Bool = false,
        currency: Gemstone.Currency = .mxn,
        values: [Gemstone.ChartDateValue] = [],
        header: Gemstone.GemChartHeader? = nil,
        bounds: Gemstone.GemChartBounds = .mock(),
        dateStyle: Gemstone.GemChartDateStyle = .relative,
    ) -> Gemstone.GemChartData {
        Gemstone.GemChartData(
            valueType: valueType,
            base: base,
            showsSecondaryValue: showsSecondaryValue,
            currency: currency,
            values: values,
            header: header,
            bounds: bounds,
            dateStyle: dateStyle,
        )
    }
}

public extension Gemstone.GemChartHeader {
    static func mock(
        value: Gemstone.GemFormattedNumber = .mock(),
        secondaryValue: Gemstone.GemFormattedNumber? = nil,
        change: Gemstone.GemFormattedNumber? = nil,
    ) -> Gemstone.GemChartHeader {
        Gemstone.GemChartHeader(
            value: value,
            secondaryValue: secondaryValue,
            change: change,
        )
    }
}

public extension Gemstone.GemConfirmFee {
    static func mock(
        value: BigInt = 0,
        formatted: Gemstone.GemFeeAmount = .mock(),
        additionalFees: [Gemstone.GemFeeOptionItem] = [],
        selectedPriority: Gemstone.FeePriority = .normal,
        amount: Gemstone.GemTransferAmountResult = .mock(),
    ) -> Gemstone.GemConfirmFee {
        Gemstone.GemConfirmFee(
            value: value,
            formatted: formatted,
            additionalFees: additionalFees,
            selectedPriority: selectedPriority,
            amount: amount,
        )
    }
}

public extension Gemstone.GemConfirmFeeRow {
    static func mock(
        title: Gemstone.GemListRowTitle = .api,
        value: Gemstone.GemConfirmFeeValue = .loading,
        info: Gemstone.GemInfoTopic = .mock(),
        opensDetails: Bool = false,
    ) -> Gemstone.GemConfirmFeeRow {
        Gemstone.GemConfirmFeeRow(
            title: title,
            value: value,
            info: info,
            opensDetails: opensDetails,
        )
    }
}

public extension Gemstone.GemConfirmFeeSelection {
    static func mock() -> Gemstone.GemConfirmFeeSelection {
        .priority(priority: .normal)
    }
}

public extension Gemstone.GemConfirmHeader {
    static func mock(
        header: Gemstone.GemTransactionHeader = .mock(),
        isReserved: Bool = false,
    ) -> Gemstone.GemConfirmHeader {
        Gemstone.GemConfirmHeader(
            header: header,
            isReserved: isReserved,
        )
    }
}

public extension Gemstone.GemConfirmLoad {
    static func mock(
        transfer: Gemstone.GemTransferData = .mock(),
        sender: Gemstone.Account = Primitives.Account.mock().toGem(),
        feeAsset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        metadata: Gemstone.GemConfirmMetadata = .mock(),
        feeAssets: [Gemstone.GemFeeAsset] = [],
        simulation: Gemstone.GemConfirmSimulationState = .mock(),
        addressName: Gemstone.AddressName? = nil,
        fee: Gemstone.GemConfirmFee? = nil,
    ) -> Gemstone.GemConfirmLoad {
        Gemstone.GemConfirmLoad(
            transfer: transfer,
            sender: sender,
            feeAsset: feeAsset,
            metadata: metadata,
            feeAssets: feeAssets,
            simulation: simulation,
            addressName: addressName,
            fee: fee,
        )
    }
}

public extension Gemstone.GemConfirmLoadOptions {
    static func mock(
        feeSelection: Gemstone.GemConfirmFeeSelection = .mock(),
        feeAssetId: String? = nil,
        assetId: String? = nil,
    ) -> Gemstone.GemConfirmLoadOptions {
        Gemstone.GemConfirmLoadOptions(
            feeSelection: feeSelection,
            feeAssetId: feeAssetId,
            assetId: assetId,
        )
    }
}

public extension Gemstone.GemConfirmMetadata {
    static func mock(
        assetBalance: Gemstone.GemAssetBalance = .mock(),
        feeAssetBalance: Gemstone.GemAssetBalance = .mock(),
        prices: [Gemstone.AssetPrice] = [],
    ) -> Gemstone.GemConfirmMetadata {
        Gemstone.GemConfirmMetadata(
            assetBalance: assetBalance,
            feeAssetBalance: feeAssetBalance,
            prices: prices,
        )
    }
}

public extension Gemstone.GemConfirmScreen {
    static func mock(
        phase: Gemstone.GemConfirmPhase = .loading,
        hasCriticalWarning: Bool = false,
        failure: Gemstone.GemConfirmFailure? = nil,
        hasFee: Bool = false,
        shownSheet: Gemstone.GemConfirmErrorSheet? = nil,
    ) -> Gemstone.GemConfirmScreen {
        Gemstone.GemConfirmScreen(
            phase: phase,
            hasCriticalWarning: hasCriticalWarning,
            failure: failure,
            hasFee: hasFee,
            shownSheet: shownSheet,
        )
    }
}

public extension Gemstone.GemConfirmSimulation {
    static func mock(
        primaryFields: [Gemstone.GemSimulationPayloadRow] = [],
        secondaryFields: [Gemstone.GemSimulationPayloadRow] = [],
        header: Gemstone.GemSimulationValue? = nil,
        balanceChanges: [Gemstone.GemListRow] = [],
        hasCriticalWarning: Bool = false,
    ) -> Gemstone.GemConfirmSimulation {
        Gemstone.GemConfirmSimulation(
            primaryFields: primaryFields,
            secondaryFields: secondaryFields,
            header: header,
            balanceChanges: balanceChanges,
            hasCriticalWarning: hasCriticalWarning,
        )
    }
}

public extension Gemstone.GemConfirmSimulationState {
    static func mock(
        chain: String = Primitives.Chain.bitcoin.rawValue,
        warnings: [Gemstone.GemListRow] = [],
        simulation: Gemstone.GemConfirmSimulation? = nil,
    ) -> Gemstone.GemConfirmSimulationState {
        Gemstone.GemConfirmSimulationState(
            chain: chain,
            warnings: warnings,
            simulation: simulation,
        )
    }
}

public extension Gemstone.GemConnectionRow {
    static func mock(
        title: String = "",
        host: String? = nil,
        initial: String = "",
        iconUrl: String? = nil,
    ) -> Gemstone.GemConnectionRow {
        Gemstone.GemConnectionRow(
            title: title,
            host: host,
            initial: initial,
            iconUrl: iconUrl,
        )
    }
}

public extension Gemstone.GemCustomFeeSession {
    static func mock(
        feeAsset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        input: String = "",
        format: Gemstone.GemNumberFormat = .mock(),
        rows: Gemstone.GemFeeRateRows = .mock(),
        loadedFee: BigInt? = nil,
        price: Double? = nil,
        currency: Gemstone.Currency = .mxn,
    ) -> Gemstone.GemCustomFeeSession {
        Gemstone.GemCustomFeeSession(
            feeAsset: feeAsset,
            input: input,
            format: format,
            rows: rows,
            loadedFee: loadedFee,
            price: price,
            currency: currency,
        )
    }
}

public extension Gemstone.GemEmptyState {
    static func mock(
        title: Gemstone.GemEmptyStateText = .nftsTitle,
        description: Gemstone.GemEmptyStateText? = nil,
        image: Gemstone.GemEmptyStateImage = .nfts,
        actions: [Gemstone.GemEmptyStateAction] = [],
    ) -> Gemstone.GemEmptyState {
        Gemstone.GemEmptyState(
            title: title,
            description: description,
            image: image,
            actions: actions,
        )
    }
}

public extension Gemstone.GemFeeAmount {
    static func mock(
        amount: Gemstone.GemFormattedNumber = .mock(),
        fiat: Gemstone.GemFormattedNumber? = nil,
    ) -> Gemstone.GemFeeAmount {
        Gemstone.GemFeeAmount(
            amount: amount,
            fiat: fiat,
        )
    }
}

public extension Gemstone.GemFeeAsset {
    static func mock(
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        balance: Gemstone.GemAssetBalance = .mock(),
        price: Gemstone.AssetPrice? = nil,
        row: Gemstone.GemAssetItemRow = .mock(),
    ) -> Gemstone.GemFeeAsset {
        Gemstone.GemFeeAsset(
            asset: asset,
            balance: balance,
            price: price,
            row: row,
        )
    }
}

public extension Gemstone.GemFeeRateKind {
    static func mock() -> Gemstone.GemFeeRateKind {
        .priority(priority: .normal)
    }
}

public extension Gemstone.GemFeeRateRow {
    static func mock(
        kind: Gemstone.GemFeeRateKind = .mock(),
        title: Gemstone.GemListRowTitle = .api,
        emoji: String = "",
        fee: BigInt? = nil,
        amount: Gemstone.GemFeeAmount? = nil,
        value: Gemstone.GemLocalizedText? = nil,
        isSelected: Bool = false,
    ) -> Gemstone.GemFeeRateRow {
        Gemstone.GemFeeRateRow(
            kind: kind,
            title: title,
            emoji: emoji,
            fee: fee,
            amount: amount,
            value: value,
            isSelected: isSelected,
        )
    }
}

public extension Gemstone.GemFeeRateRows {
    static func mock(
        rows: [Gemstone.GemFeeRateRow] = [],
        showsOptions: Bool = false,
        unitType: Gemstone.FeeUnitType = .satVb,
        unitDecimals: UInt32 = 0,
        selectedTotal: BigInt? = nil,
        normalTotal: BigInt? = nil,
    ) -> Gemstone.GemFeeRateRows {
        Gemstone.GemFeeRateRows(
            rows: rows,
            showsOptions: showsOptions,
            unitType: unitType,
            unitDecimals: unitDecimals,
            selectedTotal: selectedTotal,
            normalTotal: normalTotal,
        )
    }
}

public extension Gemstone.GemFeeText {
    static func mock(
        value: Gemstone.GemFormattedNumber = .mock(),
        extra: Gemstone.GemLocalizedText? = nil,
    ) -> Gemstone.GemFeeText {
        Gemstone.GemFeeText(
            value: value,
            extra: extra,
        )
    }
}

public extension Gemstone.GemFiatOperation {
    static func mock(
        quoteType: Gemstone.FiatQuoteType = .buy,
        amount: String = "",
        quotes: [Gemstone.FiatQuote] = [],
        selectedProvider: Gemstone.FiatProviderName? = nil,
        phase: Gemstone.GemFiatQuotePhase = .noInput,
    ) -> Gemstone.GemFiatOperation {
        Gemstone.GemFiatOperation(
            quoteType: quoteType,
            amount: amount,
            quotes: quotes,
            selectedProvider: selectedProvider,
            phase: phase,
        )
    }
}

public extension Gemstone.GemFiatQuoteRequest {
    static func mock(
        quoteType: Gemstone.FiatQuoteType = .buy,
        amount: Double = 0,
    ) -> Gemstone.GemFiatQuoteRequest {
        Gemstone.GemFiatQuoteRequest(
            quoteType: quoteType,
            amount: amount,
        )
    }
}

public extension Gemstone.GemFiatQuoteRow {
    static func mock(
        quoteId: String = "",
        provider: Gemstone.FiatProviderName = .mercuryo,
        providerName: String = "",
        cryptoAmount: Gemstone.GemFormattedNumber = .mock(),
        fiatAmount: Gemstone.GemFormattedNumber = .mock(),
        rate: Gemstone.GemAssetRate? = nil,
    ) -> Gemstone.GemFiatQuoteRow {
        Gemstone.GemFiatQuoteRow(
            quoteId: quoteId,
            provider: provider,
            providerName: providerName,
            cryptoAmount: cryptoAmount,
            fiatAmount: fiatAmount,
            rate: rate,
        )
    }
}

public extension Gemstone.GemFiatQuotesResult {
    static func mock(
        request: Gemstone.GemFiatQuoteRequest = .mock(),
        quotes: [Gemstone.FiatQuote] = [],
        error: Gemstone.GemServiceError? = nil,
    ) -> Gemstone.GemFiatQuotesResult {
        Gemstone.GemFiatQuotesResult(
            request: request,
            quotes: quotes,
            error: error,
        )
    }
}

public extension Gemstone.GemFiatSession {
    static func mock(
        quoteType: Gemstone.FiatQuoteType = .buy,
        buy: Gemstone.GemFiatOperation = .mock(),
        sell: Gemstone.GemFiatOperation = .mock(),
        available: BigUInt = 0,
    ) -> Gemstone.GemFiatSession {
        Gemstone.GemFiatSession(
            quoteType: quoteType,
            buy: buy,
            sell: sell,
            available: available,
        )
    }
}

public extension Gemstone.GemFormattedNumber {
    static func mock(
        value: Double = 0,
        unit: Gemstone.GemNumberUnit = .mock(),
        display: Gemstone.GemNumberDisplay = .mock(),
        notation: Gemstone.GemNumberNotation = .plain,
        tone: Gemstone.GemValueTone = .plain,
        rounding: Gemstone.GemNumberRounding = .toNearest,
        exact: String? = nil,
    ) -> Gemstone.GemFormattedNumber {
        Gemstone.GemFormattedNumber(
            value: value,
            unit: unit,
            display: display,
            notation: notation,
            tone: tone,
            rounding: rounding,
            exact: exact,
        )
    }
}

public extension Gemstone.GemHeaderAmount {
    static func mock(
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        amount: Gemstone.GemFormattedNumber = .mock(),
        fiat: Gemstone.GemFormattedNumber? = nil,
        icon: Gemstone.GemAssetIcon = .mock(),
    ) -> Gemstone.GemHeaderAmount {
        Gemstone.GemHeaderAmount(
            asset: asset,
            amount: amount,
            fiat: fiat,
            icon: icon,
        )
    }
}

public extension Gemstone.GemHeaderButton {
    static func mock(
        kind: Gemstone.GemHeaderButtonKind = .send,
        action: Gemstone.GemHeaderButtonAction = .mock(),
        isEnabled: Bool = false,
    ) -> Gemstone.GemHeaderButton {
        Gemstone.GemHeaderButton(
            kind: kind,
            action: action,
            isEnabled: isEnabled,
        )
    }
}

public extension Gemstone.GemHeaderButtonAction {
    static func mock() -> Gemstone.GemHeaderButtonAction {
        .send(assetId: nil)
    }
}

public extension Gemstone.GemInfoTopic {
    static func mock() -> Gemstone.GemInfoTopic {
        .networkFee(asset: Primitives.Asset.mock().toGem())
    }
}

public extension Gemstone.GemLocalizedText {
    static func mock() -> Gemstone.GemLocalizedText {
        .walletDefaultName(index: 0)
    }
}

public extension Gemstone.GemNetworkFeeScreen {
    static func mock(
        fee: Gemstone.GemFeeAmount? = nil,
        additionalFees: [Gemstone.GemFeeOptionItem] = [],
        rates: Gemstone.GemFeeRateRows? = nil,
        feeAsset: Gemstone.GemFeeAsset? = nil,
        feeAssets: [Gemstone.GemFeeAsset] = [],
        custom: Gemstone.GemCustomFeeSession? = nil,
    ) -> Gemstone.GemNetworkFeeScreen {
        Gemstone.GemNetworkFeeScreen(
            fee: fee,
            additionalFees: additionalFees,
            rates: rates,
            feeAsset: feeAsset,
            feeAssets: feeAssets,
            custom: custom,
        )
    }
}

public extension Gemstone.GemNftEntry {
    static func mock(
        item: Gemstone.GemNftItem = .mock(),
        row: Gemstone.GemNftRow = .mock(),
    ) -> Gemstone.GemNftEntry {
        Gemstone.GemNftEntry(
            item: item,
            row: row,
        )
    }
}

public extension Gemstone.GemNftItem {
    static func mock() -> Gemstone.GemNftItem {
        .collection(data: Primitives.NFTData.mock().toGem())
    }
}

public extension Gemstone.GemNftRow {
    static func mock(
        id: String = "",
        title: String = "",
        imageUrl: String = "",
        countText: String? = nil,
        isVerified: Bool = false,
    ) -> Gemstone.GemNftRow {
        Gemstone.GemNftRow(
            id: id,
            title: title,
            imageUrl: imageUrl,
            countText: countText,
            isVerified: isVerified,
        )
    }
}

public extension Gemstone.GemNodeCheck {
    static func mock(
        url: String = "",
        chainId: String? = nil,
        latestBlockNumber: UInt64 = 0,
        isInSync: Bool = false,
        latency: Gemstone.Latency = Primitives.Latency.mock().toGem(),
    ) -> Gemstone.GemNodeCheck {
        Gemstone.GemNodeCheck(
            url: url,
            chainId: chainId,
            latestBlockNumber: latestBlockNumber,
            isInSync: isInSync,
            latency: latency,
        )
    }
}

public extension Gemstone.GemNodeSelection {
    static func mock(
        url: String = "",
        host: String = "",
        isSelected: Bool = false,
        gemNodeFlag: String? = nil,
    ) -> Gemstone.GemNodeSelection {
        Gemstone.GemNodeSelection(
            url: url,
            host: host,
            isSelected: isSelected,
            gemNodeFlag: gemNodeFlag,
        )
    }
}

public extension Gemstone.GemNodeStatusState {
    static func mock() -> Gemstone.GemNodeStatusState {
        .loading
    }
}

public extension Gemstone.GemNumberDisplay {
    static func mock() -> Gemstone.GemNumberDisplay {
        .number(precision: .mock())
    }
}

public extension Gemstone.GemNumberFormat {
    static func mock(
        decimalSeparator: String = "",
    ) -> Gemstone.GemNumberFormat {
        Gemstone.GemNumberFormat(
            decimalSeparator: decimalSeparator,
        )
    }
}

public extension Gemstone.GemNumberUnit {
    static func mock() -> Gemstone.GemNumberUnit {
        .currency(code: "USD")
    }
}

public extension Gemstone.GemPaymentRecipient {
    static func mock(
        recipient: Gemstone.GemRecipient = .mock(),
        amount: String? = nil,
    ) -> Gemstone.GemPaymentRecipient {
        Gemstone.GemPaymentRecipient(
            recipient: recipient,
            amount: amount,
        )
    }
}

public extension Gemstone.GemPerpetualDetails {
    static func mock(
        title: String = "",
        sections: [Gemstone.GemPerpetualSection] = [],
        modifyButtons: [Gemstone.GemPerpetualButtonRow] = [],
        position: Gemstone.PerpetualPosition? = nil,
        positionRow: Gemstone.GemPerpetualPositionRow? = nil,
    ) -> Gemstone.GemPerpetualDetails {
        Gemstone.GemPerpetualDetails(
            title: title,
            sections: sections,
            modifyButtons: modifyButtons,
            position: position,
            positionRow: positionRow,
        )
    }
}

public extension Gemstone.GemPerpetualTransferData {
    static func mock(
        provider: Gemstone.PerpetualProvider = .hypercore,
        direction: Gemstone.PerpetualDirection = .short,
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        baseAsset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        assetIndex: Int32 = 0,
        price: Double = 0,
        leverage: UInt8 = 0,
        marginType: Gemstone.PerpetualMarginType = .cross,
    ) -> Gemstone.GemPerpetualTransferData {
        Gemstone.GemPerpetualTransferData(
            provider: provider,
            direction: direction,
            asset: asset,
            baseAsset: baseAsset,
            assetIndex: assetIndex,
            price: price,
            leverage: leverage,
            marginType: marginType,
        )
    }
}

public extension Gemstone.GemPrecision {
    static func mock() -> Gemstone.GemPrecision {
        .fraction(min: 0, max: 0)
    }
}

public extension Gemstone.GemRecipient {
    static func mock(
        address: String = "",
        name: String? = nil,
        memo: String? = nil,
        references: [String] = [],
    ) -> Gemstone.GemRecipient {
        Gemstone.GemRecipient(
            address: address,
            name: name,
            memo: memo,
            references: references,
        )
    }
}

public extension Gemstone.GemRewardsRedemption {
    static func mock(
        id: String = "",
        assetId: String = Primitives.AssetId.mock().identifier,
        icon: Gemstone.GemAssetIcon = .mock(),
        title: Gemstone.GemLocalizedText = .mock(),
        canRedeem: Bool = false,
        points: Gemstone.GemFormattedNumber = .mock(),
        value: Gemstone.GemFormattedNumber = .mock(),
        confirmation: Gemstone.GemLocalizedText = .mock(),
    ) -> Gemstone.GemRewardsRedemption {
        Gemstone.GemRewardsRedemption(
            id: id,
            assetId: assetId,
            icon: icon,
            title: title,
            canRedeem: canRedeem,
            points: points,
            value: value,
            confirmation: confirmation,
        )
    }
}

public extension Gemstone.GemRewardsResult {
    static func mock(
        walletId: String = Primitives.WalletId.mock().id,
        state: Gemstone.GemLoadState = .noData,
        rewards: Gemstone.Rewards? = nil,
    ) -> Gemstone.GemRewardsResult {
        Gemstone.GemRewardsResult(
            walletId: walletId,
            state: state,
            rewards: rewards,
        )
    }
}

public extension Gemstone.GemRewardsState {
    static func mock(
        actions: [Gemstone.GemRewardsAction] = [],
        errorNotice: Gemstone.GemListRow? = nil,
        statusNotice: Gemstone.GemListRow? = nil,
        sections: [Gemstone.GemListSection] = [],
        inviteDescription: Gemstone.GemLocalizedText = .mock(),
        referralCode: String? = nil,
        referralLink: String? = nil,
        shareText: Gemstone.GemLocalizedText? = nil,
        usedReferralCode: String? = nil,
        redemptions: [Gemstone.GemRewardsRedemption] = [],
    ) -> Gemstone.GemRewardsState {
        Gemstone.GemRewardsState(
            actions: actions,
            errorNotice: errorNotice,
            statusNotice: statusNotice,
            sections: sections,
            inviteDescription: inviteDescription,
            referralCode: referralCode,
            referralLink: referralLink,
            shareText: shareText,
            usedReferralCode: usedReferralCode,
            redemptions: redemptions,
        )
    }
}

public extension Gemstone.GemRowText {
    static func mock(
        text: Gemstone.GemLocalizedText = .mock(),
        tone: Gemstone.GemValueTone = .plain,
    ) -> Gemstone.GemRowText {
        Gemstone.GemRowText(
            text: text,
            tone: tone,
        )
    }
}

public extension Gemstone.GemSignMessagePreview {
    static func mock(
        title: Gemstone.GemLocalizedText = .mock(),
        text: String = "",
        primaryFields: [Gemstone.GemSimulationPayloadRow] = [],
        secondaryFields: [Gemstone.GemSimulationPayloadRow] = [],
        hasCriticalWarning: Bool = false,
        header: Gemstone.GemSimulationValue? = nil,
        rows: [Gemstone.GemListRow] = [],
        warnings: [Gemstone.GemListRow] = [],
    ) -> Gemstone.GemSignMessagePreview {
        Gemstone.GemSignMessagePreview(
            title: title,
            text: text,
            primaryFields: primaryFields,
            secondaryFields: secondaryFields,
            hasCriticalWarning: hasCriticalWarning,
            header: header,
            rows: rows,
            warnings: warnings,
        )
    }
}

public extension Gemstone.GemSocialLink {
    static func mock(
        linkType: Gemstone.LinkType = .x,
        url: String = "",
        host: String? = nil,
    ) -> Gemstone.GemSocialLink {
        Gemstone.GemSocialLink(
            linkType: linkType,
            url: url,
            host: host,
        )
    }
}

public extension Gemstone.GemStakeValidatorOptions {
    static func mock(
        recommended: [Gemstone.GemValidatorRow] = [],
        options: [Gemstone.GemValidatorRow] = [],
    ) -> Gemstone.GemStakeValidatorOptions {
        Gemstone.GemStakeValidatorOptions(
            recommended: recommended,
            options: options,
        )
    }
}

public extension Gemstone.GemSwapPairSuggestion {
    static func mock(
        payAssetId: String = Primitives.AssetId.mock().identifier,
        receiveAssetId: String? = nil,
    ) -> Gemstone.GemSwapPairSuggestion {
        Gemstone.GemSwapPairSuggestion(
            payAssetId: payAssetId,
            receiveAssetId: receiveAssetId,
        )
    }
}

public extension Gemstone.GemSwapQuoteInput {
    static func mock(
        request: Gemstone.GemSwapRequest = .mock(),
        useMaxAmount: Bool = false,
    ) -> Gemstone.GemSwapQuoteInput {
        Gemstone.GemSwapQuoteInput(
            request: request,
            useMaxAmount: useMaxAmount,
        )
    }
}

public extension Gemstone.GemSwapQuotesResult {
    static func mock(
        request: Gemstone.GemSwapRequest = .mock(),
        quotes: [Gemstone.SwapperQuote] = [],
        error: Gemstone.SwapperError? = nil,
    ) -> Gemstone.GemSwapQuotesResult {
        Gemstone.GemSwapQuotesResult(
            request: request,
            quotes: quotes,
            error: error,
        )
    }
}

public extension Gemstone.GemSwapRequest {
    static func mock(
        payAssetId: String = Primitives.AssetId.mock().identifier,
        receiveAssetId: String = Primitives.AssetId.mock().identifier,
        value: BigUInt = 0,
        slippageBps: UInt32? = nil,
    ) -> Gemstone.GemSwapRequest {
        Gemstone.GemSwapRequest(
            payAssetId: payAssetId,
            receiveAssetId: receiveAssetId,
            value: value,
            slippageBps: slippageBps,
        )
    }
}

public extension Gemstone.GemSwapSession {
    static func mock(
        quotes: Gemstone.GemSwapQuotesResult? = nil,
        selectedProvider: Gemstone.SwapProvider? = nil,
        selectedQuote: Gemstone.SwapperQuote? = nil,
        quotePhase: Gemstone.GemSwapQuotePhase = .noInput,
        transferPhase: Gemstone.GemSwapTransferPhase = .idle,
        refreshPausedUntilRestart: Bool = false,
        input: Gemstone.GemSwapQuoteInput? = nil,
        payValue: BigUInt? = nil,
    ) -> Gemstone.GemSwapSession {
        Gemstone.GemSwapSession(
            quotes: quotes,
            selectedProvider: selectedProvider,
            selectedQuote: selectedQuote,
            quotePhase: quotePhase,
            transferPhase: transferPhase,
            refreshPausedUntilRestart: refreshPausedUntilRestart,
            input: input,
            payValue: payValue,
        )
    }
}

public extension Gemstone.GemSwapTransfer {
    static func mock(
        quote: Gemstone.SwapQuote = .mock(),
        data: Gemstone.SwapQuoteData = .mock(),
        recipient: String = "",
        value: BigUInt = 0,
        useMaxAmount: Bool = false,
    ) -> Gemstone.GemSwapTransfer {
        Gemstone.GemSwapTransfer(
            quote: quote,
            data: data,
            recipient: recipient,
            value: value,
            useMaxAmount: useMaxAmount,
        )
    }
}

public extension Gemstone.GemTransactionAmount {
    static func mock(
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        value: BigUInt = 0,
        sign: Gemstone.GemAmountSign = .none,
        price: Gemstone.AssetPrice? = nil,
    ) -> Gemstone.GemTransactionAmount {
        Gemstone.GemTransactionAmount(
            asset: asset,
            value: value,
            sign: sign,
            price: price,
        )
    }
}

public extension Gemstone.GemTransactionDetailRows {
    static func mock(
        id: String = Primitives.TransactionId.mock().identifier,
        asset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        transactionType: Gemstone.TransactionType = .transfer,
        direction: Gemstone.TransactionDirection = .selfTransfer,
        state: Gemstone.TransactionState = .pending,
        createdAt: Date = Date(timeIntervalSince1970: 0),
        status: Gemstone.GemTransactionStatus = .mock(),
        title: Gemstone.GemTransactionTitle = .received,
        header: Gemstone.GemTransactionHeader = .mock(),
        headerAction: Gemstone.GemTransactionHeaderAction? = nil,
        swapProgress: Gemstone.GemSwapProgress? = nil,
        swapAgain: Gemstone.GemSwapAgain? = nil,
        estimatedConfirmationSeconds: UInt32? = nil,
        participant: Gemstone.GemAddressRow? = nil,
        providerName: String? = nil,
        providerContract: String? = nil,
        memo: String? = nil,
        resource: Gemstone.Resource? = nil,
        rate: Gemstone.GemSwapRate? = nil,
        pnl: Gemstone.GemFormattedNumber? = nil,
        price: Gemstone.GemFormattedNumber? = nil,
        fee: Gemstone.GemTransactionAmount = .mock(),
        feeRow: Gemstone.GemTransactionFeeRow = .mock(),
        explorer: Gemstone.BlockExplorerLink = Primitives.BlockExplorerLink.mock().toGem(),
    ) -> Gemstone.GemTransactionDetailRows {
        Gemstone.GemTransactionDetailRows(
            id: id,
            asset: asset,
            transactionType: transactionType,
            direction: direction,
            state: state,
            createdAt: createdAt,
            status: status,
            title: title,
            header: header,
            headerAction: headerAction,
            swapProgress: swapProgress,
            swapAgain: swapAgain,
            estimatedConfirmationSeconds: estimatedConfirmationSeconds,
            participant: participant,
            providerName: providerName,
            providerContract: providerContract,
            memo: memo,
            resource: resource,
            rate: rate,
            pnl: pnl,
            price: price,
            fee: fee,
            feeRow: feeRow,
            explorer: explorer,
        )
    }
}

public extension Gemstone.GemTransactionFeeRow {
    static func mock(
        title: Gemstone.GemListRowTitle = .api,
        text: Gemstone.GemFeeText = .mock(),
        fee: Gemstone.GemFeeAmount = .mock(),
        info: Gemstone.GemInfoTopic = .mock(),
    ) -> Gemstone.GemTransactionFeeRow {
        Gemstone.GemTransactionFeeRow(
            title: title,
            text: text,
            fee: fee,
            info: info,
        )
    }
}

public extension Gemstone.GemTransactionHeader {
    static func mock() -> Gemstone.GemTransactionHeader {
        .amount(header: .mock())
    }
}

public extension Gemstone.GemTransactionStatus {
    static func mock(
        tone: Gemstone.GemTransactionStateTone = .pending,
        showsBadge: Bool = false,
        showsProgress: Bool = false,
    ) -> Gemstone.GemTransactionStatus {
        Gemstone.GemTransactionStatus(
            tone: tone,
            showsBadge: showsBadge,
            showsProgress: showsProgress,
        )
    }
}

public extension Gemstone.GemTransferAmount {
    static func mock(
        value: BigInt = 0,
        networkFee: BigInt = 0,
        isMaxAmount: Bool = false,
    ) -> Gemstone.GemTransferAmount {
        Gemstone.GemTransferAmount(
            value: value,
            networkFee: networkFee,
            isMaxAmount: isMaxAmount,
        )
    }
}

public extension Gemstone.GemTransferAmountResult {
    static func mock() -> Gemstone.GemTransferAmountResult {
        .amount(amount: .mock())
    }
}

public extension Gemstone.GemTransferData {
    static func mock(
        inputType: Gemstone.TransactionInputType = .mock(),
        recipient: Gemstone.GemRecipient = .mock(),
        value: BigInt = 0,
        useMaxAmount: Bool = false,
    ) -> Gemstone.GemTransferData {
        Gemstone.GemTransferData(
            inputType: inputType,
            recipient: recipient,
            value: value,
            useMaxAmount: useMaxAmount,
        )
    }
}

public extension Gemstone.GemValidatorRow {
    static func mock(
        validator: Gemstone.DelegationValidator = Primitives.DelegationValidator.mock().toGem(),
        name: String = "",
        imageUrl: String = "",
        placeholder: String = "",
        provider: Gemstone.YieldProvider? = nil,
        apr: Gemstone.GemLocalizedText = .mock(),
        explorer: Gemstone.BlockExplorerLink? = nil,
    ) -> Gemstone.GemValidatorRow {
        Gemstone.GemValidatorRow(
            validator: validator,
            name: name,
            imageUrl: imageUrl,
            placeholder: placeholder,
            provider: provider,
            apr: apr,
            explorer: explorer,
        )
    }
}

public extension Gemstone.GemValueHeader {
    static func mock(
        icon: Gemstone.GemValueHeaderIcon? = nil,
        title: Gemstone.GemLocalizedText = .mock(),
        subtitle: Gemstone.GemRowText? = nil,
        subtitleIcon: Gemstone.GemValueHeaderSubtitleIcon? = nil,
        actions: Gemstone.GemHeaderActions? = nil,
    ) -> Gemstone.GemValueHeader {
        Gemstone.GemValueHeader(
            icon: icon,
            title: title,
            subtitle: subtitle,
            subtitleIcon: subtitleIcon,
            actions: actions,
        )
    }
}

public extension Gemstone.GemWalletConnectAuthAccount {
    static func mock(
        account: Gemstone.Account = Primitives.Account.mock().toGem(),
        chainId: String = "",
        issuer: String = "",
    ) -> Gemstone.GemWalletConnectAuthAccount {
        Gemstone.GemWalletConnectAuthAccount(
            account: account,
            chainId: chainId,
            issuer: issuer,
        )
    }
}

public extension Gemstone.GemWalletConnectMessageRequest {
    static func mock(
        sessionId: String = "",
        chain: String = Primitives.Chain.bitcoin.rawValue,
        wallet: Gemstone.Wallet = Primitives.Wallet.mock().toGem(),
        account: Gemstone.Account = Primitives.Account.mock().toGem(),
        session: Gemstone.WalletConnectionSession = Primitives.WalletConnectionSession.mock().toGem(),
        simulation: Gemstone.SimulationResult = .mock(),
        message: Gemstone.SignMessage = .mock(),
        assets: [Gemstone.Asset] = [],
    ) -> Gemstone.GemWalletConnectMessageRequest {
        Gemstone.GemWalletConnectMessageRequest(
            sessionId: sessionId,
            chain: chain,
            wallet: wallet,
            account: account,
            session: session,
            simulation: simulation,
            message: message,
            assets: assets,
        )
    }
}

public extension Gemstone.GemWalletConnectTransactionRequest {
    static func mock(
        sessionId: String = "",
        chain: String = Primitives.Chain.bitcoin.rawValue,
        wallet: Gemstone.Wallet = Primitives.Wallet.mock().toGem(),
        account: Gemstone.Account = Primitives.Account.mock().toGem(),
        session: Gemstone.WalletConnectionSession = Primitives.WalletConnectionSession.mock().toGem(),
        simulation: Gemstone.SimulationResult = .mock(),
        transfer: Gemstone.GemTransferData = .mock(),
        action: Gemstone.GemWalletConnectTransactionAction = .sign,
    ) -> Gemstone.GemWalletConnectTransactionRequest {
        Gemstone.GemWalletConnectTransactionRequest(
            sessionId: sessionId,
            chain: chain,
            wallet: wallet,
            account: account,
            session: session,
            simulation: simulation,
            transfer: transfer,
            action: action,
        )
    }
}

public extension Gemstone.GemWalletHomeViewState {
    static func mock(
        header: Gemstone.GemValueHeader = .mock(),
        showCollections: Bool = false,
        showsPerpetuals: Bool = false,
        banner: Gemstone.GemBannerRow? = nil,
    ) -> Gemstone.GemWalletHomeViewState {
        Gemstone.GemWalletHomeViewState(
            header: header,
            showCollections: showCollections,
            showsPerpetuals: showsPerpetuals,
            banner: banner,
        )
    }
}

public extension Gemstone.GemWalletRow {
    static func mock(
        id: String = "",
        name: String = "",
        subtitle: Gemstone.GemWalletSubtitle = .multicoin,
        placeholder: Gemstone.GemWalletPlaceholder = .multicoin,
        showsWatchBadge: Bool = false,
        isPinned: Bool = false,
        isCurrent: Bool = false,
        hasAvatar: Bool = false,
        imageUrl: String? = nil,
        deletePrompt: Gemstone.GemLocalizedText = .mock(),
    ) -> Gemstone.GemWalletRow {
        Gemstone.GemWalletRow(
            id: id,
            name: name,
            subtitle: subtitle,
            placeholder: placeholder,
            showsWatchBadge: showsWatchBadge,
            isPinned: isPinned,
            isCurrent: isCurrent,
            hasAvatar: hasAvatar,
            imageUrl: imageUrl,
            deletePrompt: deletePrompt,
        )
    }
}

public extension Gemstone.NameRecord {
    static func mock(
        name: String = "",
        chain: String = Primitives.Chain.bitcoin.rawValue,
        address: String = "",
        provider: Gemstone.NameProvider = .ud,
    ) -> Gemstone.NameRecord {
        Gemstone.NameRecord(
            name: name,
            chain: chain,
            address: address,
            provider: provider,
        )
    }
}

public extension Gemstone.PaymentInvoice {
    static func mock(
        link: Gemstone.PaymentLink = .mock(),
        merchant: Gemstone.PaymentMerchant = .mock(),
        price: Gemstone.PaymentPrice? = nil,
        quotes: [Gemstone.PaymentQuote] = [],
        verification: Gemstone.PaymentVerification? = nil,
    ) -> Gemstone.PaymentInvoice {
        Gemstone.PaymentInvoice(
            link: link,
            merchant: merchant,
            price: price,
            quotes: quotes,
            verification: verification,
        )
    }
}

public extension Gemstone.PaymentLink {
    static func mock() -> Gemstone.PaymentLink {
        .solanaPay(url: "")
    }
}

public extension Gemstone.PaymentMerchant {
    static func mock(
        name: String = "",
        icon: String = "",
    ) -> Gemstone.PaymentMerchant {
        Gemstone.PaymentMerchant(
            name: name,
            icon: icon,
        )
    }
}

public extension Gemstone.PaymentPrice {
    static func mock(
        currency: String = "",
        amount: Double = 0,
    ) -> Gemstone.PaymentPrice {
        Gemstone.PaymentPrice(
            currency: currency,
            amount: amount,
        )
    }
}

public extension Gemstone.PaymentQuote {
    static func mock(
        id: String = "",
        assetId: String = Primitives.AssetId.mock().identifier,
        value: BigUInt = 0,
    ) -> Gemstone.PaymentQuote {
        Gemstone.PaymentQuote(
            id: id,
            assetId: assetId,
            value: value,
        )
    }
}

public extension Gemstone.PaymentRequest {
    static func mock(
        address: String = "",
        amount: Gemstone.PaymentAmount? = nil,
        memo: String? = nil,
        label: String? = nil,
        references: [String]? = nil,
        assetId: String? = nil,
    ) -> Gemstone.PaymentRequest {
        Gemstone.PaymentRequest(
            address: address,
            amount: amount,
            memo: memo,
            label: label,
            references: references,
            assetId: assetId,
        )
    }
}

public extension Gemstone.PerpetualConfirmData {
    static func mock(
        direction: Gemstone.PerpetualDirection = .short,
        marginType: Gemstone.PerpetualMarginType = .cross,
        baseAsset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        assetIndex: Int32 = 0,
        price: String = "",
        fiatValue: Double = 0,
        size: String = "",
        slippage: Double = 0,
        leverage: UInt8 = 0,
        pnl: Double? = nil,
        entryPrice: Double? = nil,
        marketPrice: Double = 0,
        marginAmount: Double = 0,
        takeProfit: String? = nil,
        stopLoss: String? = nil,
    ) -> Gemstone.PerpetualConfirmData {
        Gemstone.PerpetualConfirmData(
            direction: direction,
            marginType: marginType,
            baseAsset: baseAsset,
            assetIndex: assetIndex,
            price: price,
            fiatValue: fiatValue,
            size: size,
            slippage: slippage,
            leverage: leverage,
            pnl: pnl,
            entryPrice: entryPrice,
            marketPrice: marketPrice,
            marginAmount: marginAmount,
            takeProfit: takeProfit,
            stopLoss: stopLoss,
        )
    }
}

public extension Gemstone.PerpetualModifyConfirmData {
    static func mock(
        baseAsset: Gemstone.Asset = Primitives.Asset.mock().toGem(),
        assetIndex: Int32 = 0,
        modifyTypes: [Gemstone.PerpetualModifyPositionType] = [],
        takeProfitOrderId: UInt64? = nil,
        stopLossOrderId: UInt64? = nil,
    ) -> Gemstone.PerpetualModifyConfirmData {
        Gemstone.PerpetualModifyConfirmData(
            baseAsset: baseAsset,
            assetIndex: assetIndex,
            modifyTypes: modifyTypes,
            takeProfitOrderId: takeProfitOrderId,
            stopLossOrderId: stopLossOrderId,
        )
    }
}

public extension Gemstone.PerpetualPortfolioTimeframeData {
    static func mock(
        accountValueHistory: [Gemstone.ChartDateValue] = [],
        pnlHistory: [Gemstone.ChartDateValue] = [],
        volume: Double = 0,
    ) -> Gemstone.PerpetualPortfolioTimeframeData {
        Gemstone.PerpetualPortfolioTimeframeData(
            accountValueHistory: accountValueHistory,
            pnlHistory: pnlHistory,
            volume: volume,
        )
    }
}

public extension Gemstone.PerpetualReduceData {
    static func mock(
        data: Gemstone.PerpetualConfirmData = .mock(),
        positionDirection: Gemstone.PerpetualDirection = .short,
    ) -> Gemstone.PerpetualReduceData {
        Gemstone.PerpetualReduceData(
            data: data,
            positionDirection: positionDirection,
        )
    }
}

public extension Gemstone.PortfolioChartData {
    static func mock(
        chartType: Gemstone.PortfolioChartType = .value,
        values: [Gemstone.ChartDateValue] = [],
    ) -> Gemstone.PortfolioChartData {
        Gemstone.PortfolioChartData(
            chartType: chartType,
            values: values,
        )
    }
}

public extension Gemstone.PortfolioData {
    static func mock(
        charts: [Gemstone.PortfolioChartData] = [],
        statistics: [Gemstone.PortfolioStatistic] = [],
        availablePeriods: [Gemstone.ChartPeriod] = [],
    ) -> Gemstone.PortfolioData {
        Gemstone.PortfolioData(
            charts: charts,
            statistics: statistics,
            availablePeriods: availablePeriods,
        )
    }
}

public extension Gemstone.PortfolioMarginUsage {
    static func mock(
        accountValue: Double = 0,
        usage: Double = 0,
        usedValue: Double = 0,
        usagePercent: Double = 0,
    ) -> Gemstone.PortfolioMarginUsage {
        Gemstone.PortfolioMarginUsage(
            accountValue: accountValue,
            usage: usage,
            usedValue: usedValue,
            usagePercent: usagePercent,
        )
    }
}

public extension Gemstone.RedelegateData {
    static func mock(
        delegation: Gemstone.Delegation = Primitives.Delegation.mock().toGem(),
        toValidator: Gemstone.DelegationValidator = Primitives.DelegationValidator.mock().toGem(),
    ) -> Gemstone.RedelegateData {
        Gemstone.RedelegateData(
            delegation: delegation,
            toValidator: toValidator,
        )
    }
}

public extension Gemstone.RedemptionResult {
    static func mock(
        redemption: Gemstone.RewardRedemption = .mock(),
    ) -> Gemstone.RedemptionResult {
        Gemstone.RedemptionResult(
            redemption: redemption,
        )
    }
}

public extension Gemstone.ReferralAllowance {
    static func mock(
        daily: Gemstone.ReferralQuota = .mock(),
        weekly: Gemstone.ReferralQuota = .mock(),
    ) -> Gemstone.ReferralAllowance {
        Gemstone.ReferralAllowance(
            daily: daily,
            weekly: weekly,
        )
    }
}

public extension Gemstone.ReferralQuota {
    static func mock(
        limit: Int32 = 0,
        available: Int32 = 0,
    ) -> Gemstone.ReferralQuota {
        Gemstone.ReferralQuota(
            limit: limit,
            available: available,
        )
    }
}

public extension Gemstone.RewardRedemption {
    static func mock(
        id: Int32 = 0,
        option: Gemstone.RewardRedemptionOption = .mock(),
        status: Gemstone.RedemptionStatus = .pending,
        transactionId: String? = nil,
        createdAt: Date = Date(timeIntervalSince1970: 0),
    ) -> Gemstone.RewardRedemption {
        Gemstone.RewardRedemption(
            id: id,
            option: option,
            status: status,
            transactionId: transactionId,
            createdAt: createdAt,
        )
    }
}

public extension Gemstone.RewardRedemptionOption {
    static func mock(
        id: String = "",
        redemptionType: Gemstone.RewardRedemptionType = .asset,
        points: Int32 = 0,
        asset: Gemstone.Asset? = nil,
        value: BigUInt = 0,
        remaining: Int32? = nil,
    ) -> Gemstone.RewardRedemptionOption {
        Gemstone.RewardRedemptionOption(
            id: id,
            redemptionType: redemptionType,
            points: points,
            asset: asset,
            value: value,
            remaining: remaining,
        )
    }
}

public extension Gemstone.Rewards {
    static func mock(
        code: String? = nil,
        inviteRewardPoints: Int32 = 0,
        referralCount: Int32 = 0,
        points: Int32 = 0,
        usedReferralCode: String? = nil,
        status: Gemstone.RewardStatus = .unverified,
        createdAt: Int64 = 0,
        verifyAfter: Date? = nil,
        redemptionOptions: [Gemstone.RewardRedemptionOption] = [],
        disableReason: String? = nil,
        referralAllowance: Gemstone.ReferralAllowance = .mock(),
        useReferralCodeUntil: Date? = nil,
    ) -> Gemstone.Rewards {
        Gemstone.Rewards(
            code: code,
            inviteRewardPoints: inviteRewardPoints,
            referralCount: referralCount,
            points: points,
            usedReferralCode: usedReferralCode,
            status: status,
            createdAt: createdAt,
            verifyAfter: verifyAfter,
            redemptionOptions: redemptionOptions,
            disableReason: disableReason,
            referralAllowance: referralAllowance,
            useReferralCodeUntil: useReferralCodeUntil,
        )
    }
}

public extension Gemstone.SignMessage {
    static func mock(
        chain: String = Primitives.Chain.bitcoin.rawValue,
        signType: Gemstone.SignDigestType = .eip191,
        data: Data = Data(),
    ) -> Gemstone.SignMessage {
        Gemstone.SignMessage(
            chain: chain,
            signType: signType,
            data: data,
        )
    }
}

public extension Gemstone.SimulationPayloadField {
    static func mock(
        kind: Gemstone.SimulationPayloadFieldKind = .contract,
        label: String? = nil,
        value: String = "",
        fieldType: Gemstone.SimulationPayloadFieldType = .text,
        display: Gemstone.SimulationPayloadFieldDisplay = .primary,
    ) -> Gemstone.SimulationPayloadField {
        Gemstone.SimulationPayloadField(
            kind: kind,
            label: label,
            value: value,
            fieldType: fieldType,
            display: display,
        )
    }
}

public extension Gemstone.SimulationResult {
    static func mock(
        warnings: [Gemstone.SimulationWarning] = [],
        balanceChanges: [Gemstone.SimulationBalanceChange] = [],
        payload: [Gemstone.SimulationPayloadField] = [],
        header: Gemstone.SimulationHeader? = nil,
    ) -> Gemstone.SimulationResult {
        Gemstone.SimulationResult(
            warnings: warnings,
            balanceChanges: balanceChanges,
            payload: payload,
            header: header,
        )
    }
}

public extension Gemstone.SimulationWarning {
    static func mock(
        severity: Gemstone.SimulationSeverity = .low,
        warning: Gemstone.SimulationWarningType = .mock(),
        message: String? = nil,
    ) -> Gemstone.SimulationWarning {
        Gemstone.SimulationWarning(
            severity: severity,
            warning: warning,
            message: message,
        )
    }
}

public extension Gemstone.SimulationWarningApproval {
    static func mock(
        assetId: String = Primitives.AssetId.mock().identifier,
        value: BigInt? = nil,
    ) -> Gemstone.SimulationWarningApproval {
        Gemstone.SimulationWarningApproval(
            assetId: assetId,
            value: value,
        )
    }
}

public extension Gemstone.SimulationWarningType {
    static func mock() -> Gemstone.SimulationWarningType {
        .tokenApproval(.mock())
    }
}

public extension Gemstone.SwapData {
    static func mock(
        quote: Gemstone.SwapQuote = .mock(),
        data: Gemstone.SwapQuoteData = .mock(),
    ) -> Gemstone.SwapData {
        Gemstone.SwapData(
            quote: quote,
            data: data,
        )
    }
}

public extension Gemstone.SwapProviderData {
    static func mock(
        provider: Gemstone.SwapProvider = .uniswapV3,
        name: String = "",
        protocolName: String = "",
    ) -> Gemstone.SwapProviderData {
        Gemstone.SwapProviderData(
            provider: provider,
            name: name,
            protocolName: protocolName,
        )
    }
}

public extension Gemstone.SwapQuote {
    static func mock(
        fromAddress: String = "",
        fromValue: BigUInt = 0,
        minFromValue: BigUInt? = nil,
        toAddress: String = "",
        toValue: BigUInt = 0,
        providerData: Gemstone.SwapProviderData = .mock(),
        slippageBps: UInt32 = 0,
        etaInSeconds: UInt32? = nil,
        useMaxAmount: Bool? = nil,
    ) -> Gemstone.SwapQuote {
        Gemstone.SwapQuote(
            fromAddress: fromAddress,
            fromValue: fromValue,
            minFromValue: minFromValue,
            toAddress: toAddress,
            toValue: toValue,
            providerData: providerData,
            slippageBps: slippageBps,
            etaInSeconds: etaInSeconds,
            useMaxAmount: useMaxAmount,
        )
    }
}

public extension Gemstone.SwapQuoteData {
    static func mock(
        to: String = "",
        dataType: Gemstone.SwapQuoteDataType = .contract,
        value: BigUInt = 0,
        data: String = "",
        memo: String? = nil,
        approval: Gemstone.ApprovalData? = nil,
        gasLimit: String? = nil,
    ) -> Gemstone.SwapQuoteData {
        Gemstone.SwapQuoteData(
            to: to,
            dataType: dataType,
            value: value,
            data: data,
            memo: memo,
            approval: approval,
            gasLimit: gasLimit,
        )
    }
}

public extension Gemstone.SwapperOptions {
    static func mock(
        slippage: Gemstone.SwapperSlippage = .mock(),
        useMaxAmount: Bool = false,
    ) -> Gemstone.SwapperOptions {
        Gemstone.SwapperOptions(
            slippage: slippage,
            useMaxAmount: useMaxAmount,
        )
    }
}

public extension Gemstone.SwapperProviderData {
    static func mock(
        provider: Gemstone.SwapperProviderType = .mock(),
        slippageBps: UInt32 = 0,
        routes: [Gemstone.SwapperRoute] = [],
    ) -> Gemstone.SwapperProviderData {
        Gemstone.SwapperProviderData(
            provider: provider,
            slippageBps: slippageBps,
            routes: routes,
        )
    }
}

public extension Gemstone.SwapperProviderType {
    static func mock(
        id: Gemstone.SwapProvider = .uniswapV3,
        name: String = "",
        protocol: String = "",
        protocolId: String = "",
        mode: Gemstone.SwapperProviderMode = .onChain,
        slippageMode: Gemstone.SwapperSlippageMode = .auto,
    ) -> Gemstone.SwapperProviderType {
        Gemstone.SwapperProviderType(
            id: id,
            name: name,
            protocol: `protocol`,
            protocolId: protocolId,
            mode: mode,
            slippageMode: slippageMode,
        )
    }
}

public extension Gemstone.SwapperQuote {
    static func mock(
        fromValue: BigUInt = 0,
        minFromValue: BigUInt? = nil,
        toValue: BigUInt = 0,
        data: Gemstone.SwapperProviderData = .mock(),
        request: Gemstone.SwapperQuoteRequest = .mock(),
        etaInSeconds: UInt32? = nil,
    ) -> Gemstone.SwapperQuote {
        Gemstone.SwapperQuote(
            fromValue: fromValue,
            minFromValue: minFromValue,
            toValue: toValue,
            data: data,
            request: request,
            etaInSeconds: etaInSeconds,
        )
    }
}

public extension Gemstone.SwapperQuoteAsset {
    static func mock(
        id: String = "",
        symbol: String = "",
        decimals: UInt32 = 0,
        assetType: Gemstone.AssetType = .native,
    ) -> Gemstone.SwapperQuoteAsset {
        Gemstone.SwapperQuoteAsset(
            id: id,
            symbol: symbol,
            decimals: decimals,
            assetType: assetType,
        )
    }
}

public extension Gemstone.SwapperQuoteRequest {
    static func mock(
        fromAsset: Gemstone.SwapperQuoteAsset = .mock(),
        toAsset: Gemstone.SwapperQuoteAsset = .mock(),
        walletAddress: String = "",
        destinationAddress: String = "",
        value: BigUInt = 0,
        options: Gemstone.SwapperOptions = .mock(),
    ) -> Gemstone.SwapperQuoteRequest {
        Gemstone.SwapperQuoteRequest(
            fromAsset: fromAsset,
            toAsset: toAsset,
            walletAddress: walletAddress,
            destinationAddress: destinationAddress,
            value: value,
            options: options,
        )
    }
}

public extension Gemstone.SwapperRoute {
    static func mock(
        input: String = Primitives.AssetId.mock().identifier,
        output: String = Primitives.AssetId.mock().identifier,
        routeData: String = "",
    ) -> Gemstone.SwapperRoute {
        Gemstone.SwapperRoute(
            input: input,
            output: output,
            routeData: routeData,
        )
    }
}

public extension Gemstone.SwapperSlippage {
    static func mock(
        bps: UInt32 = 0,
        mode: Gemstone.SwapperSlippageMode = .auto,
    ) -> Gemstone.SwapperSlippage {
        Gemstone.SwapperSlippage(
            bps: bps,
            mode: mode,
        )
    }
}

public extension Gemstone.TransactionInputType {
    static func mock() -> Gemstone.TransactionInputType {
        .transfer(asset: Primitives.Asset.mock().toGem())
    }
}

public extension Gemstone.TransferDataExtra {
    static func mock(
        to: String = "",
        gasLimit: BigInt? = nil,
        gasPrice: Gemstone.GasPriceType? = nil,
        data: Data? = nil,
        outputType: Gemstone.TransferDataOutputType = .encodedTransaction,
        outputAction: Gemstone.TransferDataOutputAction = .sign,
        transactionType: Gemstone.TransactionType = .transfer,
        approval: Gemstone.ApprovalData? = nil,
    ) -> Gemstone.TransferDataExtra {
        Gemstone.TransferDataExtra(
            to: to,
            gasLimit: gasLimit,
            gasPrice: gasPrice,
            data: data,
            outputType: outputType,
            outputAction: outputAction,
            transactionType: transactionType,
            approval: approval,
        )
    }
}
