/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import com.gemwallet.android.serializer.WalletIdSerializer
import kotlinx.serialization.Serializable

@Serializable(with = WalletIdSerializer::class)
data class WalletId (
	val id: String
)

