name: Android Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UNIT_TESTS: "true"
  JAVA_HOME: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
  ANDROID_HOME: /opt/homebrew/share/android-commandlinetools

jobs:
  unit_test:
    name: Build and Test
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Bootstrap
        working-directory: android
        run: just bootstrap

      - name: Build
        working-directory: android
        run: just build
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        working-directory: android
        run: just unit-test
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start emulator
        working-directory: android
        run: just start-emulator

      - name: Build instrumented tests
        working-directory: android
        run: just build-test
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run instrumented tests
        working-directory: android
        run: just test
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop emulator
        if: always()
        working-directory: android
        run: just stop-emulator
